part of 'package:gc_wizard/tools/miscellaneous/gcwizardscript/logic/gcwizard_script.dart';

const _COORD_DEC = 0;
const _COORD_DMM = 1;
const _COORD_DMS = 2;
const _COORD_UTM = 3;
const _COORD_MGRS = 4;
const _COORD_XYZ = 5;
const _COORD_SWISS_GRID = 6;
const _COORD_SWISS_GRID_PLUS = 7;
const _COORD_DUTCH_GRID = 8;
//const _COORD_GAUSS_KRUEGER = 9;
const _COORD_GAUSS_KRUEGER_GK1 = 901;
const _COORD_GAUSS_KRUEGER_GK2 = 902;
const _COORD_GAUSS_KRUEGER_GK3 = 903;
const _COORD_GAUSS_KRUEGER_GK4 = 904;
const _COORD_GAUSS_KRUEGER_GK5 = 905;
//const _COORD_LAMBERT = 10;
const _COORD_LAMBERT93 = 1093;
const _COORD_LAMBERT2008 = 1008;
const _COORD_ETRS89LCC = 1089;
const _COORD_LAMBERT72 = 1072;
const _COORD_LAMBERT93_CC42 = 1042;
const _COORD_LAMBERT93_CC43 = 1043;
const _COORD_LAMBERT93_CC44 = 1044;
const _COORD_LAMBERT93_CC45 = 1045;
const _COORD_LAMBERT93_CC46 = 1046;
const _COORD_LAMBERT93_CC47 = 1047;
const _COORD_LAMBERT93_CC48 = 1048;
const _COORD_LAMBERT93_CC49 = 1049;
const _COORD_LAMBERT93_CC50 = 1050;
const _COORD_MAIDENHEAD = 11;
const _COORD_MERCATOR = 12;
const _COORD_NATURAL_AREA_CODE = 13;
//const _COORD_SLIPPY_MAP = 14;
const _COORD_SLIPPYMAP_0 = 1400;
const _COORD_SLIPPYMAP_1 = 1401;
const _COORD_SLIPPYMAP_2 = 1402;
const _COORD_SLIPPYMAP_3 = 1403;
const _COORD_SLIPPYMAP_4 = 1404;
const _COORD_SLIPPYMAP_5 = 1405;
const _COORD_SLIPPYMAP_6 = 1406;
const _COORD_SLIPPYMAP_7 = 1407;
const _COORD_SLIPPYMAP_8 = 1408;
const _COORD_SLIPPYMAP_9 = 1409;
const _COORD_SLIPPYMAP_10 = 1410;
const _COORD_SLIPPYMAP_11 = 1411;
const _COORD_SLIPPYMAP_12 = 1412;
const _COORD_SLIPPYMAP_13 = 1413;
const _COORD_SLIPPYMAP_14 = 1414;
const _COORD_SLIPPYMAP_15 = 1415;
const _COORD_SLIPPYMAP_16 = 1416;
const _COORD_SLIPPYMAP_17 = 1417;
const _COORD_SLIPPYMAP_18 = 1418;
const _COORD_SLIPPYMAP_19 = 1419;
const _COORD_SLIPPYMAP_20 = 1420;
const _COORD_SLIPPYMAP_21 = 1421;
const _COORD_SLIPPYMAP_22 = 1422;
const _COORD_SLIPPYMAP_23 = 1423;
const _COORD_SLIPPYMAP_24 = 1424;
const _COORD_SLIPPYMAP_25 = 1425;
const _COORD_SLIPPYMAP_26 = 1426;
const _COORD_SLIPPYMAP_27 = 1427;
const _COORD_SLIPPYMAP_28 = 1428;
const _COORD_SLIPPYMAP_29 = 1429;
const _COORD_SLIPPYMAP_30 = 1430;
const _COORD_GEOHASH = 15;
const _COORD_GEO3X3 = 16;
const _COORD_GEOHEX = 17;
const _COORD_OPEN_LOCATION_CODE = 18;
const _COORD_MAKANEY = 19;
const _COORD_QUADTREE = 20;
const _COORD_REVERSE_WIG_WALDMEISTER = 21;
const _COORD_REVERSE_WIG_DAY1976 = 22;
//const _COORD_MAPCODE = 23;
const _COORD_MAPCODE_LOCAL = 2301;
const _COORD_MAPCODE_INTERNATIONAL = 2302;

const Map<int, CoordinateFormatKey> _GCW_SCRIPT_COORD_CONVERTER = {
  _COORD_DEC: CoordinateFormatKey.DEC,
  _COORD_DMM: CoordinateFormatKey.DMM,
  _COORD_DMS: CoordinateFormatKey.DMS,
  _COORD_UTM: CoordinateFormatKey.UTM,
  _COORD_MGRS: CoordinateFormatKey.MGRS,
  _COORD_XYZ: CoordinateFormatKey.XYZ,
  _COORD_SWISS_GRID: CoordinateFormatKey.SWISS_GRID,
  _COORD_SWISS_GRID_PLUS: CoordinateFormatKey.SWISS_GRID_PLUS,
  _COORD_DUTCH_GRID: CoordinateFormatKey.DUTCH_GRID,
  _COORD_LAMBERT93: CoordinateFormatKey.LAMBERT93,
  _COORD_LAMBERT2008: CoordinateFormatKey.LAMBERT2008,
  _COORD_ETRS89LCC: CoordinateFormatKey.ETRS89LCC,
  _COORD_LAMBERT72: CoordinateFormatKey.LAMBERT72,
  _COORD_LAMBERT93_CC42: CoordinateFormatKey.LAMBERT93_CC42,
  _COORD_LAMBERT93_CC43: CoordinateFormatKey.LAMBERT93_CC43,
  _COORD_LAMBERT93_CC44: CoordinateFormatKey.LAMBERT93_CC44,
  _COORD_LAMBERT93_CC45: CoordinateFormatKey.LAMBERT93_CC45,
  _COORD_LAMBERT93_CC46: CoordinateFormatKey.LAMBERT93_CC46,
  _COORD_LAMBERT93_CC47: CoordinateFormatKey.LAMBERT93_CC47,
  _COORD_LAMBERT93_CC48: CoordinateFormatKey.LAMBERT93_CC48,
  _COORD_LAMBERT93_CC49: CoordinateFormatKey.LAMBERT93_CC49,
  _COORD_LAMBERT93_CC50: CoordinateFormatKey.LAMBERT93_CC50,
  _COORD_MAIDENHEAD: CoordinateFormatKey.MAIDENHEAD,
  _COORD_MERCATOR: CoordinateFormatKey.MERCATOR,
  _COORD_NATURAL_AREA_CODE: CoordinateFormatKey.NATURAL_AREA_CODE,
  _COORD_GEOHASH: CoordinateFormatKey.GEOHASH,
  _COORD_GEO3X3: CoordinateFormatKey.GEO3X3,
  _COORD_GEOHEX: CoordinateFormatKey.GEOHEX,
  _COORD_OPEN_LOCATION_CODE: CoordinateFormatKey.OPEN_LOCATION_CODE,
  _COORD_MAKANEY: CoordinateFormatKey.MAKANEY,
  _COORD_QUADTREE: CoordinateFormatKey.QUADTREE,
  _COORD_REVERSE_WIG_WALDMEISTER: CoordinateFormatKey.REVERSE_WIG_WALDMEISTER,
  _COORD_REVERSE_WIG_DAY1976: CoordinateFormatKey.REVERSE_WIG_DAY1976,
  _COORD_SLIPPYMAP_0: CoordinateFormatKey.SLIPPYMAP_0,
  _COORD_SLIPPYMAP_1: CoordinateFormatKey.SLIPPYMAP_1,
  _COORD_SLIPPYMAP_2: CoordinateFormatKey.SLIPPYMAP_2,
  _COORD_SLIPPYMAP_3: CoordinateFormatKey.SLIPPYMAP_3,
  _COORD_SLIPPYMAP_4: CoordinateFormatKey.SLIPPYMAP_4,
  _COORD_SLIPPYMAP_5: CoordinateFormatKey.SLIPPYMAP_5,
  _COORD_SLIPPYMAP_6: CoordinateFormatKey.SLIPPYMAP_6,
  _COORD_SLIPPYMAP_7: CoordinateFormatKey.SLIPPYMAP_7,
  _COORD_SLIPPYMAP_8: CoordinateFormatKey.SLIPPYMAP_8,
  _COORD_SLIPPYMAP_9: CoordinateFormatKey.SLIPPYMAP_9,
  _COORD_SLIPPYMAP_10: CoordinateFormatKey.SLIPPYMAP_10,
  _COORD_SLIPPYMAP_11: CoordinateFormatKey.SLIPPYMAP_11,
  _COORD_SLIPPYMAP_12: CoordinateFormatKey.SLIPPYMAP_12,
  _COORD_SLIPPYMAP_13: CoordinateFormatKey.SLIPPYMAP_13,
  _COORD_SLIPPYMAP_14: CoordinateFormatKey.SLIPPYMAP_14,
  _COORD_SLIPPYMAP_15: CoordinateFormatKey.SLIPPYMAP_15,
  _COORD_SLIPPYMAP_16: CoordinateFormatKey.SLIPPYMAP_16,
  _COORD_SLIPPYMAP_17: CoordinateFormatKey.SLIPPYMAP_17,
  _COORD_SLIPPYMAP_18: CoordinateFormatKey.SLIPPYMAP_18,
  _COORD_SLIPPYMAP_19: CoordinateFormatKey.SLIPPYMAP_19,
  _COORD_SLIPPYMAP_20: CoordinateFormatKey.SLIPPYMAP_20,
  _COORD_SLIPPYMAP_21: CoordinateFormatKey.SLIPPYMAP_21,
  _COORD_SLIPPYMAP_22: CoordinateFormatKey.SLIPPYMAP_22,
  _COORD_SLIPPYMAP_23: CoordinateFormatKey.SLIPPYMAP_23,
  _COORD_SLIPPYMAP_24: CoordinateFormatKey.SLIPPYMAP_24,
  _COORD_SLIPPYMAP_25: CoordinateFormatKey.SLIPPYMAP_25,
  _COORD_SLIPPYMAP_26: CoordinateFormatKey.SLIPPYMAP_26,
  _COORD_SLIPPYMAP_27: CoordinateFormatKey.SLIPPYMAP_27,
  _COORD_SLIPPYMAP_28: CoordinateFormatKey.SLIPPYMAP_28,
  _COORD_SLIPPYMAP_29: CoordinateFormatKey.SLIPPYMAP_29,
  _COORD_SLIPPYMAP_30: CoordinateFormatKey.SLIPPYMAP_30,
  _COORD_GAUSS_KRUEGER_GK1: CoordinateFormatKey.GAUSS_KRUEGER_GK1,
  _COORD_GAUSS_KRUEGER_GK2: CoordinateFormatKey.GAUSS_KRUEGER_GK2,
  _COORD_GAUSS_KRUEGER_GK3: CoordinateFormatKey.GAUSS_KRUEGER_GK3,
  _COORD_GAUSS_KRUEGER_GK4: CoordinateFormatKey.GAUSS_KRUEGER_GK4,
  _COORD_GAUSS_KRUEGER_GK5: CoordinateFormatKey.GAUSS_KRUEGER_GK5,
  _COORD_MAPCODE_LOCAL:CoordinateFormatKey.MAPCODE_LOCAL,
  _COORD_MAPCODE_INTERNATIONAL: CoordinateFormatKey.MAPCODE_INTERNATIONAL,
};
