// https://www.code-knacker.de/eiscode.htm
//
// EU     https://eur-lex.europa.eu/legal-content/DE/TXT/PDF/?uri=CELEX:32007R0416
//        S.  83 Ice condition code
//        S.  89 Ice_accessibility_code
//        S.  92 Ice_classification_code
//
// BALTIC https://www.bsh.de/EN/TOPICS/Marine_environment/Ice/Ice_observations/Ice_observations_node.html
//        https://www.bsh.de/DE/THEMEN/Meeresumwelt/Eis/Eisbeobachtungen/eisbeobachtungen_node.html
//
// WMO    https://library.wmo.int/doc_num.php?explnum_id=4651
//        S. 115 Concentration
//        S. 116 Stage of development and thickness - Symbols
//        S. 117 Form of ice
//        S. 118 Stage of melting (ms)
//        S. 119 Snow depth (s)
//
// SIGRID http://www.aari.ru/gdsidb/format/sigrid-1.pdf
//        S. 16 Concentration

// enum IceCodeLanguage { DE, EN, FR }
// Map<IceCodeLanguage, String> ICECODE_LANGUAGES = {
//   IceCodeLanguage.DE: 'common_language_german',
//   IceCodeLanguage.EN: 'common_language_english',
//   IceCodeLanguage.FR: 'common_language_french',
// };

enum IceCodeSystem {
  EU,
  BALTIC,
  WMO,
  SIGRID,
}
Map<IceCodeSystem, String> ICECODE_SYSTEM = {
  IceCodeSystem.EU: 'icecodes_system_eu',
  IceCodeSystem.BALTIC: 'icecodes_system_baltic',
  IceCodeSystem.WMO: 'icecodes_system_wmo',
  IceCodeSystem.SIGRID: 'icecodes_system_sigrid',
};

enum IceCodeSubSystem {
  CONDITION,
  ACCESSIBILITY,
  CLASSIFICATION,
  CONCENTRATION,
  DEVELOPMENT,
  FORM,
  MELTING,
  SNOW,
  A,
  S,
  T,
  K,
  SIGRID
}
Map<IceCodeSubSystem, String> ICECODE_SUBSYSTEM_EU = {
  IceCodeSubSystem.CONDITION: 'icecodes_system_eu_condition',
  IceCodeSubSystem.ACCESSIBILITY: 'icecodes_system_eu_accessibility',
  IceCodeSubSystem.CLASSIFICATION: 'icecodes_system_eu_classification',
};

Map<IceCodeSubSystem, String> ICECODE_SUBSYSTEM_BALTIC = {
  IceCodeSubSystem.A: 'icecodes_system_baltic_a',
  IceCodeSubSystem.S: 'icecodes_system_baltic_s',
  IceCodeSubSystem.T: 'icecodes_system_baltic_t',
  IceCodeSubSystem.K: 'icecodes_system_baltic_k',
};

Map<IceCodeSubSystem, String> ICECODE_SUBSYSTEM_WMO = {
  IceCodeSubSystem.CONCENTRATION: 'icecodes_system_wmo_concentration',
  IceCodeSubSystem.DEVELOPMENT: 'icecodes_system_wmo_development',
  IceCodeSubSystem.FORM: 'icecodes_system_wmo_form',
  IceCodeSubSystem.MELTING: 'icecodes_system_wmo_melting',
  IceCodeSubSystem.SNOW: 'icecodes_system_wmo_snow',
};

final Map<IceCodeSystem, Map<IceCodeSubSystem, Map<String, String>>> ICECODES = {
  IceCodeSystem.EU: {
    IceCodeSubSystem.CONDITION: {
      'A': 'icecodes_system_eu_condition_a',
      'B': 'icecodes_system_eu_condition_b',
      'C': 'icecodes_system_eu_condition_c',
      'D': 'icecodes_system_eu_condition_d',
      'E': 'icecodes_system_eu_condition_e',
      'F': 'icecodes_system_eu_condition_f',
      'G': 'icecodes_system_eu_condition_g',
      'H': 'icecodes_system_eu_condition_h',
      'K': 'icecodes_system_eu_condition_k',
      'L': 'icecodes_system_eu_condition_l',
      'M': 'icecodes_system_eu_condition_m',
      'P': 'icecodes_system_eu_condition_p',
      'R': 'icecodes_system_eu_condition_r',
      'S': 'icecodes_system_eu_condition_s',
      'U': 'icecodes_system_eu_condition_u',
      'O': 'icecodes_system_eu_condition_o',
      'V': 'icecodes_system_eu_condition_v',
    },
    IceCodeSubSystem.ACCESSIBILITY: {
      'A': 'icecodes_system_eu_accessibility_a',
      'B': 'icecodes_system_eu_accessibility_b',
      'F': 'icecodes_system_eu_accessibility_f',
      'L': 'icecodes_system_eu_accessibility_l',
      'C': 'icecodes_system_eu_accessibility_c',
      'D': 'icecodes_system_eu_accessibility_d',
      'E': 'icecodes_system_eu_accessibility_e',
      'G': 'icecodes_system_eu_accessibility_g',
      'H': 'icecodes_system_eu_accessibility_h',
      'K': 'icecodes_system_eu_accessibility_k',
      'M': 'icecodes_system_eu_accessibility_m',
      'P': 'icecodes_system_eu_accessibility_p',
      'T': 'icecodes_system_eu_accessibility_t',
      'X': 'icecodes_system_eu_accessibility_x',
      'V': 'icecodes_system_eu_accessibility_v',
    },
    IceCodeSubSystem.CLASSIFICATION: {
      'A': 'icecodes_system_eu_classification_a',
      'B': 'icecodes_system_eu_classification_b',
      'C': 'icecodes_system_eu_classification_c',
      'D': 'icecodes_system_eu_classification_d',
      'E': 'icecodes_system_eu_classification_e',
    }
  },
  IceCodeSystem.BALTIC: {
    IceCodeSubSystem.A: {
      '0': 'icecodes_system_baltic_a_0',
      '1': 'icecodes_system_baltic_a_1',
      '2': 'icecodes_system_baltic_a_2',
      '3': 'icecodes_system_baltic_a_3',
      '4': 'icecodes_system_baltic_a_4',
      '5': 'icecodes_system_baltic_a_5',
      '6': 'icecodes_system_baltic_a_6',
      '7': 'icecodes_system_baltic_a_7',
      '8': 'icecodes_system_baltic_a_8',
      '9': 'icecodes_system_baltic_a_9',
      '/': 'icecodes_system_baltic_a_/',
    },
    IceCodeSubSystem.S: {
      '0': 'icecodes_system_baltic_s_0',
      '1': 'icecodes_system_baltic_s_1',
      '2': 'icecodes_system_baltic_s_2',
      '3': 'icecodes_system_baltic_s_3',
      '4': 'icecodes_system_baltic_s_4',
      '5': 'icecodes_system_baltic_s_5',
      '6': 'icecodes_system_baltic_s_6',
      '7': 'icecodes_system_baltic_s_7',
      '8': 'icecodes_system_baltic_s_8',
      '9': 'icecodes_system_baltic_s_9',
      '/': 'icecodes_system_baltic_s_/',
    },
    IceCodeSubSystem.T: {
      '0': 'icecodes_system_baltic_t_0',
      '1': 'icecodes_system_baltic_t_1',
      '2': 'icecodes_system_baltic_t_2',
      '3': 'icecodes_system_baltic_t_3',
      '4': 'icecodes_system_baltic_t_4',
      '5': 'icecodes_system_baltic_t_5',
      '6': 'icecodes_system_baltic_t_6',
      '7': 'icecodes_system_baltic_t_7',
      '8': 'icecodes_system_baltic_t_8',
      '9': 'icecodes_system_baltic_t_9',
      '/': 'icecodes_system_baltic_t_/',
    },
    IceCodeSubSystem.K: {
      '0': 'icecodes_system_baltic_k_0',
      '1': 'icecodes_system_baltic_k_1',
      '2': 'icecodes_system_baltic_k_2',
      '3': 'icecodes_system_baltic_k_3',
      '4': 'icecodes_system_baltic_k_4',
      '5': 'icecodes_system_baltic_k_5',
      '6': 'icecodes_system_baltic_k_6',
      '7': 'icecodes_system_baltic_k_7',
      '8': 'icecodes_system_baltic_k_8',
      '9': 'icecodes_system_baltic_k_9',
      '/': 'icecodes_system_baltic_k_/',
    },
},
  IceCodeSystem.WMO: {
    IceCodeSubSystem.CONCENTRATION: {
      ' ': 'icecodes_system_wmo_concentration_-',
      '0': 'icecodes_system_wmo_concentration_0',
      '1': 'icecodes_system_wmo_concentration_1',
      '2': 'icecodes_system_wmo_concentration_2',
      '3': 'icecodes_system_wmo_concentration_3',
      '4': 'icecodes_system_wmo_concentration_4',
      '5': 'icecodes_system_wmo_concentration_5',
      '6': 'icecodes_system_wmo_concentration_6',
      '7': 'icecodes_system_wmo_concentration_7',
      '8': 'icecodes_system_wmo_concentration_8',
      '9': 'icecodes_system_wmo_concentration_9',
      '9+': 'icecodes_system_wmo_concentration_9+',
      '10': 'icecodes_system_wmo_concentration_10',
      'x': 'icecodes_system_wmo_concentration_x'
    },
    IceCodeSubSystem.DEVELOPMENT: {
      '0': 'icecodes_system_wmo_development_0',
      '1': 'icecodes_system_wmo_development_1',
      '2': 'icecodes_system_wmo_development_2',
      '3': 'icecodes_system_wmo_development_3',
      '4': 'icecodes_system_wmo_development_4',
      '5': 'icecodes_system_wmo_development_5',
      '6': 'icecodes_system_wmo_development_6',
      '7': 'icecodes_system_wmo_development_7',
      '8': 'icecodes_system_wmo_development_8',
      '9': 'icecodes_system_wmo_development_9',
      '1•': 'icecodes_system_wmo_development_10',
      '4•': 'icecodes_system_wmo_development_40',
      '7•': 'icecodes_system_wmo_development_70',
      '8•': 'icecodes_system_wmo_development_80',
      '9•': 'icecodes_system_wmo_development_90',
      '▲•': 'icecodes_system_wmo_development_D',
      'x': 'icecodes_system_wmo_development_x'
    },
    IceCodeSubSystem.FORM: {
      '0': 'icecodes_system_wmo_form_0',
      '1': 'icecodes_system_wmo_form_1',
      '2': 'icecodes_system_wmo_form_2',
      '3': 'icecodes_system_wmo_form_3',
      '4': 'icecodes_system_wmo_form_4',
      '5': 'icecodes_system_wmo_form_5',
      '6': 'icecodes_system_wmo_form_6',
      '7': 'icecodes_system_wmo_form_7',
      '8': 'icecodes_system_wmo_form_8',
      '9': 'icecodes_system_wmo_form_9',
      'x': 'icecodes_system_wmo_form_x'
    },
    IceCodeSubSystem.MELTING: {
      '0': 'icecodes_system_wmo_melting_0',
      '1': 'icecodes_system_wmo_melting_1',
      '2': 'icecodes_system_wmo_melting_2',
      '3': 'icecodes_system_wmo_melting_3',
      '4': 'icecodes_system_wmo_melting_4',
      '5': 'icecodes_system_wmo_melting_5',
      '6': 'icecodes_system_wmo_melting_6',
      '7': 'icecodes_system_wmo_melting_7',
      '8': 'icecodes_system_wmo_melting_8',
      '9': 'icecodes_system_wmo_melting_9',
    },
    IceCodeSubSystem.SNOW: {
      '0': 'icecodes_system_wmo_snow_0',
      '1': 'icecodes_system_wmo_snow_1',
      '2': 'icecodes_system_wmo_snow_2',
      '3': 'icecodes_system_wmo_snow_3',
      '4': 'icecodes_system_wmo_snow_4',
      '5': 'icecodes_system_wmo_snow_5',
      '6': 'icecodes_system_wmo_snow_6',
      '7': 'icecodes_system_wmo_snow_7',
      '8': 'icecodes_system_wmo_snow_8',
      '9': 'icecodes_system_wmo_snow_9',
    },
  },
  IceCodeSystem.SIGRID: {
    IceCodeSubSystem.SIGRID: {
      '00': 'icecodes_system_sigrid_00',
      '01': 'icecodes_system_sigrid_01',
      '02': 'icecodes_system_sigrid_02',
      '10': 'icecodes_system_sigrid_10',
      '20': 'icecodes_system_sigrid_20',
      '30': 'icecodes_system_sigrid_30',
      '40': 'icecodes_system_sigrid_40',
      '50': 'icecodes_system_sigrid_50',
      '60': 'icecodes_system_sigrid_60',
      '70': 'icecodes_system_sigrid_70',
      '80': 'icecodes_system_sigrid_80',
      '90': 'icecodes_system_sigrid_90',
      '91': 'icecodes_system_sigrid_91',
      '92': 'icecodes_system_sigrid_92',
      '99': 'icecodes_system_sigrid_99',
    },
  }
};

/*final Map<IceCodeLanguage, Map<IceCodeSystem, Map<IceCodeSubSystem, Map<String, String>>>> ICECODES = {
  IceCodeLanguage.EN: {
    IceCodeSystem.EU: {
      IceCodeSubSystem.CONDITION: {
        'A': 'clear water; thickness unknown',
        'B': 'light spread floating ice; thickness 0-4 cm',
        'C': 'ligth floating ice; thickness 0-4 cm',
        'D': 'light solid ice; thickness 0-4 cm',
        'E': 'medium spread floating ice to 40 % covered; thickness 4-8 cm',
        'F': 'medium spread floating ice 40 to 75 % covered; thickness 4-8 cm',
        'G': 'medium floating ice more than 75 % in sludge or leadcovered; thickness 4-8 cm',
        'H': 'medium vast ice; thickness 4-8 cm',
        'K': 'medium spread floating ice to 40 % covered; thickness 8-12 cm',
        'L': 'heavy spread floating ice 40 to 75 % covered; thickness 8-12 cm',
        'M': 'heavy dense floating ice with more than 75 % chance on coagulation; thickness 8-12 cm',
        'P': 'heavy floating ice with more than 75 % in sludge or lead currently broken sludge; thickness 8-12cm',
        'R': 'heavy vast ice; thickness 8-12cm',
        'S': 'very heavy floating ice en solid ice nearly 100 % covered; thickness > 12cm',
        'U': 'ice dam or drifting ice; thickness > 40cm',
        'O': 'disappearing (pap)ice, no longer obstructing; thickness unknown',
        'V': 'navigation interrupted',
      },
      IceCodeSubSystem.ACCESSIBILITY: {
        'A': 'navigation normal',
        'B': 'navigation not yet hindered',
        'C': 'navigation possible for motorvessels with more than 0,74 Kw (1 hp) per 2 tons',
        'D': 'navigation possible for motorvessels with more than 0,74 Kw (1 hp) per ton',
        'E': 'navigation possibilities remain constant',
        'F': 'low traffic',
        'G': 'navigation possibilities may deteriorate rapidly',
        'H': 'no navigation but no obstruction',
        'K': 'navigation possible in convoy or towage',
        'L': 'no navigation without breaking',
        'M': 'navigation possible with the aid of ice breakers',
        'P': 'inland ports can hardly be reached',
        'T': 'navigation possibilities may improve rapidly',
        'X': 'navigation in convoys compulsory',
        'V': 'no navigation allowed',
      },
      IceCodeSubSystem.CLASSIFICATION: {
        'A': 'navigable',
        'B': 'fairly navigable',
        'C': 'navigable with difficulty',
        'D': 'navigable only with great difficulty',
        'E': 'no navigation allowed',
      },
    },
    IceCodeSystem.BALTIC: {
      IceCodeSubSystem.A: {
        '0': 'Ice-free',
        '1': 'Open water - concentration less than 1/10',
        '2': 'Very open ice - concentration 1/10 to 3/10',
        '3': 'Open ice - concentration 4/10 to 6/10',
        '4': 'Close ice - concentration 7/10 to 8/10',
        '5': 'Very close ice - concentration 9/10 to 9+/10',
        '6': 'Compact ice, including consolidated ice - concentration 10/10',
        '7': 'Fast ice with ice outside',
        '8': 'Fast ice',
        '9': 'Lead in very close or compact drift ice or along the fast ice edge',
        '/': 'Unable to report',
      },
      IceCodeSubSystem.S: {
        '0': 'New ice or dark nilas (less than 5 cm thick)',
        '1': 'Light nilas or ice rind ( 5-10 cm thick)',
        '2': 'Grey ice (10-15 cm thick)',
        '3': 'Grey-white ice (15-30 cm thick)',
        '4': 'White ice, first stage (30-50 cm thick)',
        '5': 'White ice, second stage (50-70 cm thick)',
        '6': 'Medium first year ice (70-120 cm thick)',
        '7': 'Ice predominantly thinner than 15 cm with some thicker ice',
        '8': 'Ice predominantly grey–white (15-30 cm thick) with some ice thicker than 30 cm',
        '9': 'Ice predominantly thicker than 30 cm with some thinner ice',
        '/': 'No information or unable to report',
      },
      IceCodeSubSystem.T: {
        '0': 'Pancake ice, ice cakes, brash ice -less than 20 m across',
        '1': 'Small ice floes - 20 - 100 m across',
        '2': 'Medium ice floes - 100 - 500 m across',
        '3': 'Big ice floes - 500 - 2000 m across',
        '4': 'Vast or giant ice floes or level ice - more than 2000 m across',
        '5': 'Rafted ice',
        '6': 'Compacted slush or shuga, or compacted brash ice',
        '7': 'Hummocked or ridged ice',
        '8': 'Thaw holes or many puddles on the ice',
        '9': 'Rotten ice',
        '/': 'No information or unable to report',
      },
      IceCodeSubSystem.K: {
        '0': 'Navigation unobstructed',
        '1': 'Navigation difficult or dangerous for wooden vessels without ice sheathing',
        '2':
            'Navigation difficult for unstrengthened or low-powered vessels built on iron or steel. Navigation for wooden vessels even with ice sheathing not advisable',
        '3':
            'Navigation without icebreaker assistance possible only for high-powered vessels of strong construction and suitable for navigation in ice',
        '4': 'Navigation proceeds in lead or broken ice-channel without the assistance of an icebreaker',
        '5': 'Icebreaker assistance can only be given to vessels suitable for navigation in ice and of special size',
        '6': 'Icebreaker assistance can only be given to vessels of special ice class and of special size',
        '7': 'Icebreaker assistance can only be given to vessels after special permission',
        '8': 'Navigation temporarily closed',
        '9': 'Navigation has ceased',
        '/': 'Unknown',
      },
    },
    IceCodeSystem.WMO: {
      IceCodeSubSystem.CONCENTRATION: {
        ' ': 'Ice free',
        '0': 'Less than 1/10',
        '1': '1/10',
        '2': '2/10',
        '3': '3/10',
        '4': '4/10',
        '5': '5/10',
        '6': '6/10',
        '7': '7/10',
        '8': '8/10',
        '9': '9/10',
        '9+': 'More than 9/10 less than 10/10',
        '10': '10/10',
        'x': 'Undetermined or unknown'
      },
      IceCodeSubSystem.DEVELOPMENT: {
        '0': 'No stage of development',
        '1': 'New ice',
        '2': 'Nilas; ice rind',
        '3': 'Young ice ',
        '4': 'Gray ice',
        '5': 'Gray-white ice',
        '6': 'First-year ice',
        '7': 'Thin first-year ice',
        '8': 'Thin first-year ice, first stage',
        '9': 'Thin first-year ice, second stage',
        '1•': 'Medium first-year ice',
        '4•': 'Thick first-year ice',
        '7•': 'Old ice',
        '8•': 'Second-year ice',
        '9•': 'Multi-year ice',
        '▲•': 'Ice of land origin',
        'x': 'Undetermined of unknown'
      },
      IceCodeSubSystem.FORM: {
        '0': 'Pancake ice',
        '1': 'Small ice cake; brash ice',
        '2': 'Ice cake ',
        '3': 'Small floe',
        '4': 'Medium floe',
        '5': 'Big floe ',
        '6': 'Vast floe',
        '7': 'Giant floe',
        '8': 'Fast ice, growlers or floebergs',
        '9': 'Icebergs',
        'x': 'Undetermined or unknown',
      },
      IceCodeSubSystem.MELTING: {
        '0': 'No melt',
        '1': 'Few puddles',
        '2': 'Many puddles',
        '3': 'Flooded ice ',
        '4': 'Few thawholes',
        '5': 'Many thawholes ',
        '6': 'Dried ice',
        '7': 'Rotten ice',
        '8': 'Few frozen puddles',
        '9': 'All puddles frozen',
      },
      IceCodeSubSystem.SNOW: {
        '0': 'No snow',
        '1': 'Up to 5 cm',
        '2': 'Up to 10 cm',
        '3': 'Up to 20 cm',
        '4': 'Up to 30 cm',
        '5': 'Up to 50 cm',
        '6': 'Up to 75 cm',
        '7': 'Up to 100 cm',
        '8': 'More than 100 cm',
        '9': 'Unknown',
      },
    },
    IceCodeSystem.SIGRID: {
      IceCodeSubSystem.SIGRID: {
        '00': 'Ice free',
        '01': 'Less than 1/10 (open water)',
        '02': 'Bergy Water',
        '10': '1/10',
        '20': '2/10',
        '30': '3/10',
        '40': '4/10',
        '50': '5/10',
        '60': '6/10',
        '70': '7/10',
        '80': '8/10',
        '90': '9/10',
        '91': 'More than 9/10 less than 10/10',
        '92': '10/10',
        '99': 'Unknown',
      },
    }
  },
  IceCodeLanguage.FR: {
    IceCodeSystem.EU: {
      IceCodeSubSystem.CONDITION: {
        'A': 'eaux normales; épaisseur inconnu',
        'B': 'glaces légères dispersées; épaisseur 0-4 cm',
        'C': 'glaces légères flottantes; épaisseur 0-4 cm',
        'D': 'glace légère; thickness 0-4 cm',
        'E': 'glaces moyennes dispersées couvrant 40 %; épaisseur 4-8 cm',
        'F': 'glaces moyennes flottantes dispersées couvrant 40 à 75 %; épaisseur 4-8 cm',
        'G': 'glaces moyennes flottantes dispersées couvrant plus de 75 % du chenal; épaisseur 4-8 cm',
        'H': 'glace moyenne; épaisseur 4-8 cm',
        'K': 'glaces lourdes flottantes dispersées couvrant jusqu\'à 40 %; épaisseur 8-12 cm',
        'L': 'glaces lourdes flottantes dispersées couvrant 40 à 75 %; épaisseur 8-12 cm',
        'M': 'glaces lourdes flottantes dispersées couvrant plus de 75 % et chance de coagulation; épaisseur 8-12 cm',
        'P': 'glaces lourdes flottantes couvrant plus de 75 % du chenal, chenal brisé récemment; épaisseur 8-12cm',
        'R': 'glace solide épaisse; épaisseur 8-12cm',
        'S': 'glaces flottantes très lourdes et banquise couvrant presque 100 %; épaisseur > 12cm',
        'U': 'barrage de glace ou débâcle; épaisseur > 40cm',
        'O': 'glaces fondantes, aucune gêne; épaisseur inconnu',
        'V': 'navigation interrompue',
      },
      IceCodeSubSystem.ACCESSIBILITY: {
        'A': 'navigation normale',
        'B': 'navigation possible',
        'C': 'la navigation est possible pour automoteurs de plus de 0,74 Kw (1 ch) par 2 tonnes',
        'D': 'la navigation est possible pour automoteurs de plus de 0,74 Kw (1 ch) par tonne',
        'E': 'les possibilités de navigation sont constantes',
        'F': 'trafic faible',
        'G': 'les possibilités de navigation peuvent se détériorer rapidement',
        'H': 'interruption de navigation même sans obstacle',
        'K': 'la navigation est possible en convois ou avec remorqueur',
        'L': 'navigation seulement derrière briseglace',
        'M': 'la navigation est possible à l\'aide d\'un brise-glace',
        'P': 'l\'arrivée aux ports intérieurs est très difficile',
        'T': 'les possibilités de navigation peuvent s\'améliorer rapidement',
        'X': 'navigation en convois obligatoire',
        'V': 'navigation interrompue',
      },
      IceCodeSubSystem.CLASSIFICATION: {
        'A': 'navigable',
        'B': 'raisonnablement navigable',
        'C': 'navigable pénible',
        'D': 'navigable très pénible',
        'E': 'navigation interrompue',
      },
    },
    IceCodeSystem.BALTIC: {
      IceCodeSubSystem.A: {
        '0': 'Ice-free',
        '1': 'Open water - concentration less than 1/10',
        '2': 'Very open ice - concentration 1/10 to 3/10',
        '3': 'Open ice - concentration 4/10 to 6/10',
        '4': 'Close ice - concentration 7/10 to 8/10',
        '5': 'Very close ice - concentration 9/10 to 9+/10',
        '6': 'Compact ice, including consolidated ice - concentration 10/10',
        '7': 'Fast ice with ice outside',
        '8': 'Fast ice',
        '9': 'Lead in very close or compact drift ice or along the fast ice edge',
        '/': 'Unable to report',
      },
      IceCodeSubSystem.S: {
        '0': 'New ice or dark nilas (less than 5 cm thick)',
        '1': 'Light nilas or ice rind ( 5-10 cm thick)',
        '2': 'Grey ice (10-15 cm thick)',
        '3': 'Grey-white ice (15-30 cm thick)',
        '4': 'White ice, first stage (30-50 cm thick)',
        '5': 'White ice, second stage (50-70 cm thick)',
        '6': 'Medium first year ice (70-120 cm thick)',
        '7': 'Ice predominantly thinner than 15 cm with some thicker ice',
        '8': 'Ice predominantly grey–white (15-30 cm thick) with some ice thicker than 30 cm',
        '9': 'Ice predominantly thicker than 30 cm with some thinner ice',
        '/': 'No information or unable to report',
      },
      IceCodeSubSystem.T: {
        '0': 'Pancake ice, ice cakes, brash ice -less than 20 m across',
        '1': 'Small ice floes - 20 - 100 m across',
        '2': 'Medium ice floes - 100 - 500 m across',
        '3': 'Big ice floes - 500 - 2000 m across',
        '4': 'Vast or giant ice floes or level ice - more than 2000 m across',
        '5': 'Rafted ice',
        '6': 'Compacted slush or shuga, or compacted brash ice',
        '7': 'Hummocked or ridged ice',
        '8': 'Thaw holes or many puddles on the ice',
        '9': 'Rotten ice',
        '/': 'No information or unable to report',
      },
      IceCodeSubSystem.K: {
        '0': 'Navigation unobstructed',
        '1': 'Navigation difficult or dangerous for wooden vessels without ice sheathing',
        '2':
        'Navigation difficult for unstrengthened or low-powered vessels built on iron or steel. Navigation for wooden vessels even with ice sheathing not advisable',
        '3':
        'Navigation without icebreaker assistance possible only for high-powered vessels of strong construction and suitable for navigation in ice',
        '4': 'Navigation proceeds in lead or broken ice-channel without the assistance of an icebreaker',
        '5': 'Icebreaker assistance can only be given to vessels suitable for navigation in ice and of special size',
        '6': 'Icebreaker assistance can only be given to vessels of special ice class and of special size',
        '7': 'Icebreaker assistance can only be given to vessels after special permission',
        '8': 'Navigation temporarily closed',
        '9': 'Navigation has ceased',
        '/': 'Unknown',
      },
    },
    IceCodeSystem.WMO: {
      IceCodeSubSystem.CONCENTRATION: {
        ' ': 'sans glace',
        '0': 'moins de 1/10',
        '1': '1/10',
        '2': '2/10',
        '3': '3/10',
        '4': '4/10',
        '5': '5/10',
        '6': '6/10',
        '7': '7/10',
        '8': '8/10',
        '9': '9/10',
        '9+': 'plus de 9/10 moins de 10/10',
        '10': '10/10',
        'x': 'indéterminé ou inconnu'
      },
      IceCodeSubSystem.DEVELOPMENT: {
        '0': 'pas de stade de développement',
        '1': 'nouvelle glace',
        '2': 'nilas; croûte de glace',
        '3': 'jeune glace ',
        '4': 'glace grise',
        '5': 'glace gris-blanc',
        '6': 'glace de première année',
        '7': 'glace mince de première année',
        '8': 'glace mince de première année, première stade',
        '9': 'glace mince de première année, deuxième stade',
        '1•': 'glace moyenne de première année',
        '4•': 'une glace épaisse de première année',
        '7•': 'vieille glace',
        '8•': 'glace de deuxième année',
        '9•': 'glace pluriannuelle',
        '▲•': 'glace d\'origine terrestre',
        'x': 'indéterminé ou inconnu'
      },
      IceCodeSubSystem.FORM: {
        '0': 'glace à crêpes',
        '1': 'petit gâteau de glace ; glace cinglante',
        '2': 'gâteau glacé',
        '3': 'petit floe de glace',
        '4': 'floe de glace moyenne',
        '5': 'grande floe de glace',
        '6': 'vaste floe de glace',
        '7': 'floe géant de glace',
        '8': 'glace rapide, growlers ou floebergs',
        '9': 'icebergs',
        'x': 'indéterminé ou inconnu',
      },
      IceCodeSubSystem.MELTING: {
        '0': 'pas de fonte',
        '1': 'peu de flaques d\'eau',
        '2': 'plusieurs flaques d\'eau',
        '3': 'glace inondée',
        '4': 'peu de trous de dégel',
        '5': 'beaucoup de trous de dégel',
        '6': 'glace séchée',
        '7': 'glace pourrie',
        '8': 'peu de flaques d\'eau gelées',
        '9': 'toutes les flaques d\'eau sont gelées',
      },
      IceCodeSubSystem.SNOW: {
        '0': 'pas de neige',
        '1': 'jusqu\'à 5 cm',
        '2': 'jusqu\'à 10 cm',
        '3': 'jusqu\'à 20 cm',
        '4': 'jusqu\'à 30 cm',
        '5': 'jusqu\'à 50 cm',
        '6': 'jusqu\'à 75 cm',
        '7': 'jusqu\'à 100 cm',
        '8': 'More than 100 cm',
        '9': 'inconnu',
      },
    },
    IceCodeSystem.SIGRID: {
      IceCodeSubSystem.SIGRID: {
        '00': 'sans glace',
        '01': 'moins de 1/10 (eaux normales)',
        '02': 'eau bergère',
        '10': '1/10',
        '20': '2/10',
        '30': '3/10',
        '40': '4/10',
        '50': '5/10',
        '60': '6/10',
        '70': '7/10',
        '80': '8/10',
        '90': '9/10',
        '91': 'plus de 9/10 moins de 10/10',
        '92': '10/10',
        '99': 'inconnu',
      },
    }
  },
};*/
