enum CoordinateFormatKey {BASE_FORMAT, ALL, DEC, DMM, DMS, UTM, MGRS, XYZ, SWISS_GRID, SWISS_GRID_PLUS, DUTCH_GRID,
  GAUSS_KRUEGER, LAMBERT, MAIDENHEAD, MERCATOR, NATURAL_AREA_CODE, SLIPPY_MAP, GEOHASH, GEO3X3,
  GEOHEX, OPEN_LOCATION_CODE, MAKANEY, QUADTREE, REVERSE_WIG_WALDMEISTER, REVERSE_WIG_DAY1976,
  //GaussKrueger Subtypes
  GAUSS_KRUEGER_GK1, GAUSS_KRUEGER_GK2, GAUSS_KRUEGER_GK3, GAUSS_KRUEGER_GK4, GAUSS_KRUEGER_GK5,
  //Lambert Subtypes
  LAMBERT93, LAMBERT2008, ETRS89LCC, LAMBERT72, LAMBERT93_CC42, LAMBERT93_CC43,
  LAMBERT93_CC44, LAMBERT93_CC45, LAMBERT93_CC46, LAMBERT93_CC47, LAMBERT93_CC48, LAMBERT93_CC49, LAMBERT93_CC50,
  //SlippyMap Subtypes
  SLIPPYMAP_0, SLIPPYMAP_1, SLIPPYMAP_2, SLIPPYMAP_3, SLIPPYMAP_4, SLIPPYMAP_5, SLIPPYMAP_6, SLIPPYMAP_7, SLIPPYMAP_8
  , SLIPPYMAP_9, SLIPPYMAP_10, SLIPPYMAP_11, SLIPPYMAP_12, SLIPPYMAP_13, SLIPPYMAP_14, SLIPPYMAP_15, SLIPPYMAP_16, SLIPPYMAP_17
  , SLIPPYMAP_18, SLIPPYMAP_19, SLIPPYMAP_20, SLIPPYMAP_21, SLIPPYMAP_22, SLIPPYMAP_23, SLIPPYMAP_24, SLIPPYMAP_25, SLIPPYMAP_26
  , SLIPPYMAP_27, SLIPPYMAP_28, SLIPPYMAP_29, SLIPPYMAP_30
}

const Map<int, CoordinateFormatKey> SLIPPY_MAP_ZOOM = {
  0: CoordinateFormatKey.SLIPPYMAP_0,
  1: CoordinateFormatKey.SLIPPYMAP_1,
  2: CoordinateFormatKey.SLIPPYMAP_2,
  3: CoordinateFormatKey.SLIPPYMAP_3,
  4: CoordinateFormatKey.SLIPPYMAP_4,
  5: CoordinateFormatKey.SLIPPYMAP_5,
  6: CoordinateFormatKey.SLIPPYMAP_6,
  7: CoordinateFormatKey.SLIPPYMAP_7,
  8: CoordinateFormatKey.SLIPPYMAP_8,
  9: CoordinateFormatKey.SLIPPYMAP_9,
  10: CoordinateFormatKey.SLIPPYMAP_10,
  11: CoordinateFormatKey.SLIPPYMAP_11,
  12: CoordinateFormatKey.SLIPPYMAP_12,
  13: CoordinateFormatKey.SLIPPYMAP_13,
  14: CoordinateFormatKey.SLIPPYMAP_14,
  15: CoordinateFormatKey.SLIPPYMAP_15,
  16: CoordinateFormatKey.SLIPPYMAP_16,
  17: CoordinateFormatKey.SLIPPYMAP_17,
  18: CoordinateFormatKey.SLIPPYMAP_18,
  19: CoordinateFormatKey.SLIPPYMAP_19,
  20: CoordinateFormatKey.SLIPPYMAP_20,
  21: CoordinateFormatKey.SLIPPYMAP_21,
  22: CoordinateFormatKey.SLIPPYMAP_22,
  23: CoordinateFormatKey.SLIPPYMAP_23,
  24: CoordinateFormatKey.SLIPPYMAP_24,
  25: CoordinateFormatKey.SLIPPYMAP_25,
  26: CoordinateFormatKey.SLIPPYMAP_26,
  27: CoordinateFormatKey.SLIPPYMAP_27,
  28: CoordinateFormatKey.SLIPPYMAP_28,
  29: CoordinateFormatKey.SLIPPYMAP_29,
  30: CoordinateFormatKey.SLIPPYMAP_30
};

const Map<int, CoordinateFormatKey> GAUSS_KRUEGER_CODE = {
  1: CoordinateFormatKey.GAUSS_KRUEGER_GK1,
  2: CoordinateFormatKey.GAUSS_KRUEGER_GK2,
  3: CoordinateFormatKey.GAUSS_KRUEGER_GK3,
  4: CoordinateFormatKey.GAUSS_KRUEGER_GK4,
  5: CoordinateFormatKey.GAUSS_KRUEGER_GK5,
};