enum CoordinateFormatKey {
  ALL,
  DEC,
  DMM,
  DMS,
  UTM,
  MGRS,
  XYZ,
  SWISS_GRID,
  SWISS_GRID_PLUS,
  DUTCH_GRID,
  GAUSS_KRUEGER,
  LAMBERT,
  MAIDENHEAD,
  MERCATOR,
  NATURAL_AREA_CODE,
  SLIPPY_MAP,
  GC8K7RC,
  GEOHASH,
  GEO3X3,
  GEOHEX,
  OPEN_LOCATION_CODE,
  MAKANEY,
  QUADTREE,
  REVERSE_WIG_WALDMEISTER,
  REVERSE_WIG_DAY1976,
  WHAT3WORDS,
  //GaussKrueger Subtypes
  GAUSS_KRUEGER_GK1,
  GAUSS_KRUEGER_GK2,
  GAUSS_KRUEGER_GK3,
  GAUSS_KRUEGER_GK4,
  GAUSS_KRUEGER_GK5,
  //Lambert Subtypes
  LAMBERT93,
  LAMBERT2008,
  ETRS89LCC,
  LAMBERT72,
  LAMBERT93_CC42,
  LAMBERT93_CC43,
  LAMBERT93_CC44,
  LAMBERT93_CC45,
  LAMBERT93_CC46,
  LAMBERT93_CC47,
  LAMBERT93_CC48,
  LAMBERT93_CC49,
  LAMBERT93_CC50,
  //SlippyMap Subtypes
  SLIPPYMAP_0,
  SLIPPYMAP_1,
  SLIPPYMAP_2,
  SLIPPYMAP_3,
  SLIPPYMAP_4,
  SLIPPYMAP_5,
  SLIPPYMAP_6,
  SLIPPYMAP_7,
  SLIPPYMAP_8,
  SLIPPYMAP_9,
  SLIPPYMAP_10,
  SLIPPYMAP_11,
  SLIPPYMAP_12,
  SLIPPYMAP_13,
  SLIPPYMAP_14,
  SLIPPYMAP_15,
  SLIPPYMAP_16,
  SLIPPYMAP_17,
  SLIPPYMAP_18,
  SLIPPYMAP_19,
  SLIPPYMAP_20,
  SLIPPYMAP_21,
  SLIPPYMAP_22,
  SLIPPYMAP_23,
  SLIPPYMAP_24,
  SLIPPYMAP_25,
  SLIPPYMAP_26,
  SLIPPYMAP_27,
  SLIPPYMAP_28,
  SLIPPYMAP_29,
  SLIPPYMAP_30,
//What3Words Subtypes
  WHAT3WORDS_DE,
  WHAT3WORDS_EN,
  WHAT3WORDS_FR,
  WHAT3WORDS_IT,
  WHAT3WORDS_RU,
  WHAT3WORDS_PL,
  WHAT3WORDS_NL,
  WHAT3WORDS_SP,
  WHAT3WORDS_KO,
  WHAT3WORDS_JA,
  WHAT3WORDS_ZH,
  WHAT3WORDS_DK,
  WHAT3WORDS_CZ,
}

const Map<int, CoordinateFormatKey> SLIPPY_MAP_ZOOM = {
  0: CoordinateFormatKey.SLIPPYMAP_0,
  1: CoordinateFormatKey.SLIPPYMAP_1,
  2: CoordinateFormatKey.SLIPPYMAP_2,
  3: CoordinateFormatKey.SLIPPYMAP_3,
  4: CoordinateFormatKey.SLIPPYMAP_4,
  5: CoordinateFormatKey.SLIPPYMAP_5,
  6: CoordinateFormatKey.SLIPPYMAP_6,
  7: CoordinateFormatKey.SLIPPYMAP_7,
  8: CoordinateFormatKey.SLIPPYMAP_8,
  9: CoordinateFormatKey.SLIPPYMAP_9,
  10: CoordinateFormatKey.SLIPPYMAP_10,
  11: CoordinateFormatKey.SLIPPYMAP_11,
  12: CoordinateFormatKey.SLIPPYMAP_12,
  13: CoordinateFormatKey.SLIPPYMAP_13,
  14: CoordinateFormatKey.SLIPPYMAP_14,
  15: CoordinateFormatKey.SLIPPYMAP_15,
  16: CoordinateFormatKey.SLIPPYMAP_16,
  17: CoordinateFormatKey.SLIPPYMAP_17,
  18: CoordinateFormatKey.SLIPPYMAP_18,
  19: CoordinateFormatKey.SLIPPYMAP_19,
  20: CoordinateFormatKey.SLIPPYMAP_20,
  21: CoordinateFormatKey.SLIPPYMAP_21,
  22: CoordinateFormatKey.SLIPPYMAP_22,
  23: CoordinateFormatKey.SLIPPYMAP_23,
  24: CoordinateFormatKey.SLIPPYMAP_24,
  25: CoordinateFormatKey.SLIPPYMAP_25,
  26: CoordinateFormatKey.SLIPPYMAP_26,
  27: CoordinateFormatKey.SLIPPYMAP_27,
  28: CoordinateFormatKey.SLIPPYMAP_28,
  29: CoordinateFormatKey.SLIPPYMAP_29,
  30: CoordinateFormatKey.SLIPPYMAP_30,
};

const Map<int, CoordinateFormatKey> GAUSS_KRUEGER_CODE = {
  1: CoordinateFormatKey.GAUSS_KRUEGER_GK1,
  2: CoordinateFormatKey.GAUSS_KRUEGER_GK2,
  3: CoordinateFormatKey.GAUSS_KRUEGER_GK3,
  4: CoordinateFormatKey.GAUSS_KRUEGER_GK4,
  5: CoordinateFormatKey.GAUSS_KRUEGER_GK5,
};

const Map<int, CoordinateFormatKey> WHAT3WORDS_CODE = {
  1: CoordinateFormatKey.WHAT3WORDS_DE,
  2: CoordinateFormatKey.WHAT3WORDS_EN,
  3: CoordinateFormatKey.WHAT3WORDS_FR,
  4: CoordinateFormatKey.WHAT3WORDS_IT,
  5: CoordinateFormatKey.WHAT3WORDS_RU,
  6: CoordinateFormatKey.WHAT3WORDS_NL,
  7: CoordinateFormatKey.WHAT3WORDS_SP,
  8: CoordinateFormatKey.WHAT3WORDS_KO,
  9: CoordinateFormatKey.WHAT3WORDS_JA,
  10: CoordinateFormatKey.WHAT3WORDS_ZH,
  11: CoordinateFormatKey.WHAT3WORDS_DK,
  12: CoordinateFormatKey.WHAT3WORDS_CZ,
  13: CoordinateFormatKey.WHAT3WORDS_PL,
};

const Map<CoordinateFormatKey, String> WHAT3WORDS_LANGUAGE = {
  CoordinateFormatKey.WHAT3WORDS_DE: 'common_language_german',
  CoordinateFormatKey.WHAT3WORDS_EN: 'common_language_english',
  CoordinateFormatKey.WHAT3WORDS_FR: 'common_language_french',
  CoordinateFormatKey.WHAT3WORDS_IT: 'common_language_italian',
  CoordinateFormatKey.WHAT3WORDS_RU: 'common_language_russian',
  CoordinateFormatKey.WHAT3WORDS_NL: 'common_language_dutch',
  CoordinateFormatKey.WHAT3WORDS_SP: 'common_language_spanish',
  CoordinateFormatKey.WHAT3WORDS_KO: 'common_language_korean',
  CoordinateFormatKey.WHAT3WORDS_JA: 'common_language_japanese',
  CoordinateFormatKey.WHAT3WORDS_ZH: 'common_language_chinese',
  CoordinateFormatKey.WHAT3WORDS_DK: 'common_language_danish',
  CoordinateFormatKey.WHAT3WORDS_CZ: 'common_language_czech',
  CoordinateFormatKey.WHAT3WORDS_PL: 'common_language_polish',
};
