const PREFERENCE_ALPHABET_CUSTOM_ALPHABETS = 'alphabetvalues_custom_alphabets';
const PREFERENCE_ALPHABET_DEFAULT_ALPHABET = 'alphabetvalues_default_alphabet';
const PREFERENCE_APP_COUNT_OPENED = 'app_count_opened';
const PREFERENCE_CHANGELOG_DISPLAYED = 'changelog_displayed';
const PREFERENCE_CLIPBOARD_MAX_ITEMS = 'clipboard_max_items';
const PREFERENCE_CLIPBOARD_KEEP_ENTRIES_IN_DAYS = 'clipboard_keep_entries_in_days';
const PREFERENCE_CLIPBOARD_ITEMS = 'clipboard_items';
const PREFERENCE_COORD_DEFAULT_ELLIPSOID_A = 'coord_default_ellipsoid_a';
const PREFERENCE_COORD_DEFAULT_ELLIPSOID_INVF = 'coord_default_ellipsoid_invf';
const PREFERENCE_COORD_DEFAULT_ELLIPSOID_NAME = 'coord_default_ellipsoid_name';
const PREFERENCE_COORD_DEFAULT_ELLIPSOID_TYPE = 'coord_default_ellipsoid_type';
const PREFERENCE_COORD_DEFAULT_FORMAT = 'coord_default_format';
const PREFERENCE_COORD_DEFAULT_FORMAT_SUBTYPE = 'coord_default_format_subtype';
const PREFERENCE_COORD_DEFAULT_HEMISPHERE_LATITUDE = 'coord_default_hemisphere_latitude';
const PREFERENCE_COORD_DEFAULT_HEMISPHERE_LONGITUDE = 'coord_default_hemisphere_longitude';
const PREFERENCE_COORD_PRECISION_DMM = 'coord_precision_dmm';
const PREFERENCE_COORD_VARIABLECOORDINATE_FORMULAS = 'coord_variablecoordinate_formulas';
const PREFERENCE_COORD_DEFAULT_W3W_APIKEY = 'coord_default_w3w_apikey';
const PREFERENCE_COORD_GC8K7RC_USE_DEFAULT_ELLIPSOID = 'coord_gc8k7rc_use_default_ellipsoid';
const PREFERENCE_DEFAULT_LENGTH_UNIT = 'default_length_unit';
const PREFERENCE_FAVORITES = 'favorites';
const PREFERENCE_FORMULASOLVER_FORMULAS = 'formulasolver_formulas';
const PREFERENCE_FORMULASOLVER_COLOREDFORMULAS = 'formulasolver_coloredformulas';
const PREFERENCE_IMAGECOLORCORRECTIONS_MAXPREVIEWHEIGHT = 'imagecolorcorrections_maxpreviewheight';
const PREFERENCE_LANGUAGE_CODE = 'language_code';
const PREFERENCE_MAPVIEW_CIRCLE_COLORFILLED = 'mapview_circle_colorfilled';
const PREFERENCE_MAPVIEW_MAPVIEWS = 'mapview_mapviews';
const PREFERENCE_MAYACALENDAR_CORRELATION = 'mayacalendar_correlation';
const PREFERENCE_MULTIDECODER_TOOLS = 'multidecoder_tools';
const PREFERENCE_SYMBOLTABLES_COUNTCOLUMNS_PORTRAIT = 'symboltables_countcolumns_portrait';
const PREFERENCE_SYMBOLTABLES_COUNTCOLUMNS_LANDSCAPE = 'symboltables_countcolumns_landscape';
const PREFERENCE_TABS_DEFAULT_TAB = 'tabs_default_tab';
const PREFERENCE_TABS_LAST_VIEWED_TAB = 'tabs_last_viewed_tab';
const PREFERENCE_TABS_USE_DEFAULT_TAB = 'tabs_use_default_tab';
const PREFERENCE_THEME_COLOR = 'theme_color';
const PREFERENCE_THEME_FONT_SIZE = 'theme_font_size';
const PREFERENCE_TOOL_COUNT = 'tool_count';
const PREFERENCE_TOOL_COUNT_SORT = 'tool_count_sort';
const PREFERENCE_TOOLLIST_SHOW_DESCRIPTIONS = 'toollist_show_descriptions';
const PREFERENCE_TOOLLIST_SHOW_EXAMPLES = 'toollist_show_examples';
const PREFERENCE_WHERIGOANALYZER_EXPERTMODE = 'wherigoanalyzer_expertmode';

final ALL_PREFERENCES = <String>[
  PREFERENCE_ALPHABET_CUSTOM_ALPHABETS,
  PREFERENCE_ALPHABET_DEFAULT_ALPHABET,
  PREFERENCE_APP_COUNT_OPENED,
  PREFERENCE_CHANGELOG_DISPLAYED,
  PREFERENCE_CLIPBOARD_MAX_ITEMS,
  PREFERENCE_CLIPBOARD_KEEP_ENTRIES_IN_DAYS,
  PREFERENCE_CLIPBOARD_ITEMS,
  PREFERENCE_COORD_DEFAULT_ELLIPSOID_A,
  PREFERENCE_COORD_DEFAULT_ELLIPSOID_INVF,
  PREFERENCE_COORD_DEFAULT_ELLIPSOID_NAME,
  PREFERENCE_COORD_DEFAULT_ELLIPSOID_TYPE,
  PREFERENCE_COORD_DEFAULT_FORMAT,
  PREFERENCE_COORD_DEFAULT_FORMAT_SUBTYPE,
  PREFERENCE_COORD_DEFAULT_HEMISPHERE_LATITUDE,
  PREFERENCE_COORD_DEFAULT_HEMISPHERE_LONGITUDE,
  PREFERENCE_COORD_PRECISION_DMM,
  PREFERENCE_COORD_VARIABLECOORDINATE_FORMULAS,
  PREFERENCE_DEFAULT_LENGTH_UNIT,
  PREFERENCE_FAVORITES,
  PREFERENCE_FORMULASOLVER_FORMULAS,
  PREFERENCE_FORMULASOLVER_COLOREDFORMULAS,
  PREFERENCE_IMAGECOLORCORRECTIONS_MAXPREVIEWHEIGHT,
  PREFERENCE_LANGUAGE_CODE,
  PREFERENCE_MAPVIEW_CIRCLE_COLORFILLED,
  PREFERENCE_MAPVIEW_MAPVIEWS,
  PREFERENCE_MAYACALENDAR_CORRELATION,
  PREFERENCE_MULTIDECODER_TOOLS,
  PREFERENCE_SYMBOLTABLES_COUNTCOLUMNS_PORTRAIT,
  PREFERENCE_SYMBOLTABLES_COUNTCOLUMNS_LANDSCAPE,
  PREFERENCE_TABS_DEFAULT_TAB,
  PREFERENCE_TABS_LAST_VIEWED_TAB,
  PREFERENCE_TABS_USE_DEFAULT_TAB,
  PREFERENCE_THEME_COLOR,
  PREFERENCE_THEME_FONT_SIZE,
  PREFERENCE_TOOL_COUNT,
  PREFERENCE_TOOL_COUNT_SORT,
  PREFERENCE_TOOLLIST_SHOW_DESCRIPTIONS,
  PREFERENCE_TOOLLIST_SHOW_EXAMPLES,
  PREFERENCE_WHERIGOANALYZER_EXPERTMODE
];
