part of 'package:gc_wizard/tools/science_and_technology/checkdigits/logic/checkdigits.dart';

// http://www.pruefziffernberechnung.de/I/IBAN.shtml
// https://de.wikipedia.org/wiki/Internationale_Bankkontonummer
// https://en.wikipedia.org/wiki/International_Bank_Account_Number
// https://web.archive.org/web/20171220203336/http://www.europebanks.info/ibanguide.php#5

// GC7DCXZ => calculate checkDigit
//         => calculate Number
// GC4TKB5 => calculate checkDigit

const Map<String, String> IBAN_DATA_MEANING = {
  'b': 'checkdigits_iban_data_b_bank_number',
  's': 'checkdigits_iban_data_s_branch_code',
  'k': 'checkdigits_iban_data_k_account_number',
  'K': 'checkdigits_iban_data_K_control_digit',
  't': 'checkdigits_iban_data_t_type_of_account',
  'r': 'checkdigits_iban_data_r_regional_code',
  'X': 'checkdigits_iban_data_x_other',
  'p': 'checkdigits_iban_data_p_account_prefix',
};

enum IBAN_IDENTIFIER_TYPES {ALPHA, ALPHANUMERIC, NUMERIC}

const Map<String, List<Map<String, Object>>>IBAN_DATA = {
  // https://en.wikipedia.org/wiki/International_Bank_Account_Number
  // https://de.wikipedia.org/w/index.php?title=Internationale_Bankkontonummer&stable=0
  // https://www.swift.com/standards/data-standards/iban
  'AD': [
    {'country': 'common_country_Andorra'},
    {'length': 24},
    {'b': 4},
    {'s': 4},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'AE': [
    {'country': 'common_country_UnitedArabEmirates'},
    {'length': 23},
    {'b': 3},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'AL': [
    {'country': 'common_country_Albania'},
    {'length': 28},
    {'b': 4},
    {'s': 4},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'AT': [
    {'country': 'common_country_Austria'},
    {'length': 20},
    {'b': 5},
    {'k': 11},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'AO': [
    {'country': 'common_country_Angola'},
    {'length': 25},
    {'b': 4},
    {'s': 4},
    {'k': 11},
    {'k': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'AZ': [
    {'country': 'common_country_Azerbaijan'},
    {'length': 28},
    {'b': 4},
    {'k': 20},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BA': [
    {'country': 'common_country_BosniaandHerzegovina'},
    {'length': 20},
    {'b': 3},
    {'s': 3},
    {'k': 8},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BE': [
    {'country': 'common_country_Belgium'},
    {'length': 16},
    {'b': 3},
    {'k': 7},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BG': [
    {'country': 'common_country_Bulgaria'},
    {'length': 22},
    {'b': 4},
    {'s': 4},
    {'t': 2},
    {'k': 8},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BH': [
    {'country': 'common_country_Bahrain'},
    {'length': 22},
    {'b': 4},
    {'k': 14},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BY': [
    {'country': 'common_country_Belarus'},
    {'length': 28},
    {'b': 4},
    {'s': 4},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'BJ': [
    {'country': 'common_country_Benin'},
    {'length': 28},
    {'b': 5},
    {'s': 5},
    {'k': 12},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BR': [
    {'country': 'common_country_Brasil'},
    {'length': 29},
    {'b': 8},
    {'s': 5},
    {'k': 10},
    {'t': 1},
    {'n': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'nc': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'BF': [
    {'country': 'common_country_BurkinaFaso'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'BI': [
    {'country': 'common_country_Burundi'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CI': [
    {'country': 'common_country_CotedIvoire'},
    {'length': 28},
    {'b': 5},
    {'s': 5},
    {'k': 12},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CF': [
    {'country': 'common_country_CentralAfricanRepublic'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CG': [
    {'country': 'common_country_RepublicoftheCongo'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CH': [
    {'country': 'common_country_Switzerland'},
    {'length': 21},
    {'b': 5},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'CM': [
    {'country': 'common_country_Cameroon'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CR': [
    {'country': 'common_country_CostaRica'},
    {'length': 22},
    {'b': 4},
    {'k': 14},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CV': [
    {'country': 'common_country_CapeVerde'},
    {'length': 25},
    {'b': 5},
    {'s': 4},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'CY': [
    {'country': 'common_country_Cyprus'},
    {'length': 28},
    {'b': 3},
    {'s': 5},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'CZ': [
    {'country': 'common_country_CzechRepublic'},
    {'length': 24},
    {'b': 4},
    {'p': 6},
    {'k': 10},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'pc': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'DE': [
    {'country': 'common_country_Germany'},
    {'length': 22},
    {'b': 8},
    {'k': 10},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'DJ': [
    {'country': 'common_country_Djibouti'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'DK': [
    {'country': 'common_country_Denmark'},
    {'length': 18},
    {'b': 4},
    {'k': 9},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'DO': [
    {'country': 'common_country_DominicanRepublic'},
    {'length': 28},
    {'b': 4},
    {'k': 20},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'DZ': [
    {'country': 'common_country_Algeria'},
    {'length': 24},
    {'b': 3},
    {'s': 5},
    {'k': 10},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'EE': [
    {'country': 'common_country_Estonia'},
    {'length': 20},
    {'b': 2},
    {'s': 2},
    {'k': 11},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'EG': [
    {'country': 'common_country_Egypt'},
    {'length': 29},
    {'b': 4},
    {'s': 4},
    {'k': 17},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'ES': [
    {'country': 'common_country_Spain'},
    {'length': 24},
    {'b': 4},
    {'s': 4},
    {'K': 2},
    {'k': 10},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},  ],
  'FI': [
    {'country': 'common_country_Finland'},
    {'length': 18},
    {'b': 6},
    {'k': 7},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},  ],
  'FK': [
    {'country': 'common_country_FalklandIslands'},
    {'length': 18},
    {'b': 2},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'FO': [
    {'country': 'common_country_FaroeIslands'},
    {'length': 18},
    {'b': 4},
    {'k': 9},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'FR': [
    {'country': 'common_country_France'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'GA': [
    {'country': 'common_country_Gabon'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 3},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'GB': [
    {'country': 'common_country_UnitedKingdom'},
    {'length': 22},
    {'b': 4},
    {'s': 6},
    {'k': 8},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'GE': [
    {'country': 'common_country_Georgia'},
    {'length': 22},
    {'b': 2},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'GI': [
    {'country': 'common_country_Gibraltar'},
    {'length': 23},
    {'b': 4},
    {'k': 15},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'GL': [
    {'country': 'common_country_Greenland'},
    {'length': 18},
    {'b': 4},
    {'k': 9},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'GR': [
    {'country': 'common_country_Greece'},
    {'length': 27},
    {'b': 3},
    {'s': 4},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'GT': [
    {'country': 'common_country_Guatemala'},
    {'length': 28},
    {'b': 4},
    {'k': 20},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'HR': [
    {'country': 'common_country_Croatia'},
    {'length': 21},
    {'b': 7},
    {'k': 10},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'HU': [
    {'country': 'common_country_Hungary'},
    {'length': 28},
    {'b': 3},
    {'s': 4},
    {'K': 1},
    {'k': 15},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'IE': [
    {'country': 'common_country_Ireland'},
    {'length': 22},
    {'b': 4},
    {'s': 6},
    {'k': 8},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'IL': [
    {'country': 'common_country_Israel'},
    {'length': 23},
    {'b': 3},
    {'s': 3},
    {'k': 13},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'IQ': [
    {'country': 'common_country_Iraq'},
    {'length': 23},
    {'b': 4},
    {'s': 3},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'IR': [
    {'country': 'common_country_Iran'},
    {'length': 26},
    {'k': 22},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'IS': [
    {'country': 'common_country_Iceland'},
    {'length': 26},
    {'b': 4},
    {'s': 2},
    {'k': 6},
    {'X': 10},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'IT': [
    {'country': 'common_country_Italy'},
    {'length': 27},
    {'K': 1},
    {'b': 5},
    {'s': 5},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'JO': [
    {'country': 'common_country_Jordan'},
    {'length': 30},
    {'b': 4},
    {'s': 4},
    {'k': 18},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'KW': [
    {'country': 'common_country_Kuwait'},
    {'length': 30},
    {'b': 4},
    {'k': 22},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'KZ': [
    {'country': 'common_country_Kazakhstan'},
    {'length': 20},
    {'b': 3},
    {'k': 13},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'LB': [
    {'country': 'common_country_Lebanon'},
    {'length': 28},
    {'b': 4},
    {'k': 20},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'LC': [
    {'country': 'common_country_SaintLucia'},
    {'length': 32},
    {'b': 4},
    {'k': 24},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'LI': [
    {'country': 'common_country_Liechtenstein'},
    {'length': 21},
    {'b': 5},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'LT': [
    {'country': 'common_country_Lithuania'},
    {'length': 20},
    {'b': 5},
    {'k': 11},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'LU': [
    {'country': 'common_country_Luxembourg'},
    {'length': 20},
    {'b': 3},
    {'k': 13},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'LV': [
    {'country': 'common_country_Latvia'},
    {'length': 21},
    {'b': 4},
    {'k': 13},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'LY': [
    {'country': 'common_country_Libya'},
    {'length': 25},
    {'b': 3},
    {'s': 3},
    {'k': 15},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MC': [
    {'country': 'common_country_Monaco'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MD': [
    {'country': 'common_country_Moldova'},
    {'length': 24},
    {'b': 2},
    {'k': 18},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'ME': [
    {'country': 'common_country_Montenegro'},
    {'length': 22},
    {'b': 3},
    {'k': 13},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MG': [
    {'country': 'common_country_Madagascar'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MK': [
    {'country': 'common_country_NorthMacedonia'},
    {'length': 19},
    {'b': 3},
    {'k': 10},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'ML': [
    {'country': 'common_country_Mali'},
    {'length': 28},
    {'b': 5},
    {'s': 5},
    {'k': 12},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MN': [
    {'country': 'common_country_Mongolia'},
    {'length': 20},
    {'b': 4},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MR': [
    {'country': 'common_country_Mauritania'},
    {'length': 27},
    {'b': 5},
    {'s': 5},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'MT': [
    {'country': 'common_country_Malta'},
    {'length': 31},
    {'b': 4},
    {'s': 5},
    {'k': 18},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'MU': [
    {'country': 'common_country_Mauritius'},
    {'length': 30},
    {'b': 4},
    {'s': 2},
    {'t': 2},
    {'k': 15},
    {'K': 3},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
  ],
  'MZ': [
    {'country': 'common_country_Mozambique'},
    {'length': 25},
    {'b': 4},
    {'s': 4},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'NI': [
    {'country': 'common_country_Nicaragua'},
    {'length': 28},
    {'b': 4},
    {'k': 20},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'NL': [
    {'country': 'common_country_Netherlands'},
    {'length': 18},
    {'b': 4},
    {'k': 10},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'NO': [
    {'country': 'common_country_Norway'},
    {'length': 15},
    {'b': 4},
    {'k': 6},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'PK': [
    {'country': 'common_country_Pakistan'},
    {'length': 24},
    {'b': 4},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'PL': [
    {'country': 'common_country_Poland'},
    {'length': 28},
    {'b': 3},
    {'s': 4},
    {'K': 1},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'PS': [
    {'country': 'common_country_Palestine'},
    {'length': 29},
    {'b': 4},
    {'r': 9},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'PT': [
    {'country': 'common_country_Portugal'},
    {'length': 25},
    {'b': 4},
    {'s': 4},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'QA': [
    {'country': 'common_country_Qatar'},
    {'length': 29},
    {'b': 4},
    {'k': 21},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'RO': [
    {'country': 'common_country_Romania'},
    {'length': 24},
    {'b': 4},
    {'s': 16},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'RS': [
    {'country': 'common_country_Serbia'},
    {'length': 22},
    {'b': 3},
    {'k': 13},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'RU': [
    {'country': 'common_country_Russia'},
    {'length': 33},
    {'b': 9},
    {'s': 5},
    {'k': 15},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SA': [
    {'country': 'common_country_SaudiArabia'},
    {'length': 24},
    {'b': 2},
    {'k': 18},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'type': [
    {'country': 'common_country_Seychelles'},
    {'length': 31},
    {'b': 4},
    {'s': 4},
    {'k': 16},
    {'X': 3},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
  ],
  'SD': [
    {'country': 'common_country_Sudan'},
    {'length': 18},
    {'b': 2},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SE': [
    {'country': 'common_country_Sweden'},
    {'length': 24},
    {'b': 3},
    {'k': 16},
    {'K': 1},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SI': [
    {'country': 'common_country_Slovenia'},
    {'length': 19},
    {'b': 2},
    {'s': 3},
    {'k': 8},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SK': [
    {'country': 'common_country_Slovakia'},
    {'length': 24},
    {'b': 4},
    {'s': 6},
    {'k': 10},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SM': [
    {'country': 'common_country_SanMarino'},
    {'length': 27},
    {'K': 1},
    {'b': 5},
    {'s': 5},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'SN': [
    {'country': 'common_country_Senegal'},
    {'length': 28},
    {'b': 5},
    {'s': 5},
    {'k': 12},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SO': [
    {'country': 'common_country_Somalia'},
    {'length': 23},
    {'b': 4},
    {'s': 3},
    {'k': 12},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'ST': [
    {'country': 'common_country_SaoTomeandPrincipe'},
    {'length': 25},
    {'b': 4},
    {'s': 4},
    {'k': 11},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'SV': [
    {'country': 'common_country_ElSalvador'},
    {'length': 28},
    {'b': 4},
    {'k': 20},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'TL': [
    {'country': 'common_country_EastTimor'},
    {'length': 23},
    {'b': 3},
    {'k': 14},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'TN': [
    {'country': 'common_country_Tunisia'},
    {'length': 24},
    {'b': 2},
    {'s': 3},
    {'k': 13},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'TR': [
    {'country': 'common_country_Turkey'},
    {'length': 26},
    {'b': 5},
    {'r': 1},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'UA': [
    {'country': 'common_country_Ukraine'},
    {'length': 29},
    {'b': 6},
    {'k': 19},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHANUMERIC},
  ],
  'VA': [
    {'country': 'common_country_VaticanCity'},
    {'length': 22},
    {'b': 3},
    {'k': 15},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'VG': [
    {'country': 'common_country_BritishVirginIslands'},
    {'length': 24},
    {'b': 4},
    {'k': 16},
    {'type': IBAN_IDENTIFIER_TYPES.ALPHA},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
  'XK': [
    {'country': 'common_country_Kosovo'},
    {'length': 20},
    {'b': 4},
    {'k': 10},
    {'K': 2},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
    {'type': IBAN_IDENTIFIER_TYPES.NUMERIC},
  ],
};

const List<String> IBAN_NUMERIC = [
  'AD', 'AE', 'AL', 'AT', 'AO', 'BA', 'BE', 'BJ', 'BF', 'BI', 'CI', 'CF', 'CG', 'CM', 'CR', 'CV', 'CZ', 'DE', 'DJ', 'DK', 'DZ', 'EE', 'EG', 'ES', 'FI', 'FO', 'GA', 'GL', 'HR', 'HU', 'IL', 'IR', 'IS', 'LT', 'LY', 'ME', 'MG', 'ML', 'MN', 'MR', 'MZ', 'NO', 'PL', 'PT', 'RS', 'RU', 'SD', 'SE', 'SI', 'SK', 'SN', 'SO', 'ST', 'TL', 'TN', 'VA', 'XK',
];

const IBAN_LENGTH_UNKNOWN_COUNTRY = 4;

CheckDigitOutput _CheckIBANNumber(String number) {
  number = number.toUpperCase();
  int length = IBAN_LENGTH_UNKNOWN_COUNTRY;
  if (number == '' || number.length < 2) {
    return CheckDigitOutput(false, 'checkdigits_invalid_length', ['']);
  } else {
    if (IBAN_DATA[number.substring(0,2)] != null) {
      length = IBAN_DATA[number.substring(0,2)]![1]['length'] as int;
    }
    if (number.length < length) {
      return CheckDigitOutput(false, 'checkdigits_invalid_length', ['']);
    } else {
      if (_checkNumber(number, _checkIBAN)) {
        return CheckDigitOutput(true, '', ['']);
      } else {
        return CheckDigitOutput(
            false, _CalculateCheckDigitAndNumber(number, _CalculateIBANNumber), _CalculateGlitch(number, _checkIBAN));
      }
    }
  }
}

String _CalculateIBANNumber(String number) {
  int length = IBAN_LENGTH_UNKNOWN_COUNTRY;
  if (number.length < 2) {
    return ('checkdigits_invalid_length');
  } else {
    if (IBAN_DATA[number.substring(0,2)] != null) {
      length = (IBAN_DATA[number.substring(0,2)]![1]['length'] as int) - 2;
    }
    if (number.length < length) {
      return ('checkdigits_invalid_length');
    } else {
      return number.substring(0, 2) + _calculateIBANCheckDigit(number) + number.substring(2);
    }
  }
}

List<String> _CalculateIBANDigits(String number) {
  return _CalculateDigits(number, _checkIBAN);
}

bool _checkIBAN(String number) {
  number = number.substring(4) +
      ID_LETTERCODE[number[0]].toString() +
      ID_LETTERCODE[number[1]].toString() +
      number[2] +
      number[3];
  number = number.toUpperCase().split('').map((character) {
    if (ID_LETTERCODE[character] == null) {
      return character;
    } else {return ID_LETTERCODE[character].toString();
    }
  }).join('');
  return (BigInt.parse(number) % BigInt.from(97) == BigInt.one);
}

String _calculateIBANCheckDigit(String number) {
  number = number.substring(2) + ID_LETTERCODE[number[0]].toString() + ID_LETTERCODE[number[1]].toString() + '00';
  number = number.toUpperCase().split('').map((character) {
    if (ID_LETTERCODE[character] == null) {
      return character;
    } else {return ID_LETTERCODE[character].toString();
    }
  }).join('');
  BigInt checkDigit = BigInt.from(98) - BigInt.parse(number) % BigInt.from(97);
  if (checkDigit < BigInt.from(10)) {
    number = '0' + checkDigit.toString();
  } else {
    number = checkDigit.toString();
  }
  return number;
}
