part of 'package:gc_wizard/tools/science_and_technology/uic_wagoncode/logic/uic_wagoncode.dart';

class _UICWagonCodePassengerHeatingSystemValue {
  final String value;
  final bool onlyDomestic;
  final bool onlyInternational;
  final bool voltage1000OnlyOn16_23Or50Hz;
  
  const _UICWagonCodePassengerHeatingSystemValue({
    required this.value, this.onlyDomestic = false, this.onlyInternational = false, this.voltage1000OnlyOn16_23Or50Hz = false
  });
}

const Map<String, List<_UICWagonCodePassengerHeatingSystemValue>> _UICWagonCodePassengerHeatingSystemValues = {
  '00': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true)],
  '02': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '03': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true)],
  '05': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~')],
  '06': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_othervoltages')],
  '07': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '08': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '10': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '11': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '12': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '13': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '14': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '15': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '17': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam, onlyDomestic: true')],
  '18': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '19': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '20': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '21': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '22': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '23': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '24': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '25': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '26': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '27': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '28': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '29': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true)],
  '30': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '32': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '33': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyDomestic: true)],
  '34': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyDomestic: true)],
  '35': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '36': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '37': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '38': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '39': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '40': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '41': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '42': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '43': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyDomestic: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '44': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '45': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '46': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '47': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '48': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '50': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam')],
  '51': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '52': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '53': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '55': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '56': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_othervoltages')],
  '57': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '60': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '62': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '64': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '66': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '69': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true)],
  '70': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true)],
  '71': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '72': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', onlyDomestic: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', onlyDomestic: true)],
  '73': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true)],
  '74': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '75': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '76': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~')],
  '77': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '78': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '79': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '80': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '81': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '82': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '84': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '85': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam')],
  '86': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '87': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_othervoltages')],
  '88': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '89': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_airconditionseparate', onlyInternational: true)],
  '90': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true)],
  '91': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '92': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), _UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '93': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~')],
  '94': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '95': [_UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '97': [_UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), _UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '98': [_UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '99': [_UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyInternational: true), _UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_airconditionseparate', onlyInternational: true)],
};