part of 'package:gc_wizard/tools/science_and_technology/uic_wagoncode/logic/uic_wagoncode.dart';

class UICWagonCodePassengerHeatingSystemValue {
  final String value;
  final bool onlyDomestic;
  final bool onlyInternational;
  final bool voltage1000OnlyOn16_23Or50Hz;
  
  const UICWagonCodePassengerHeatingSystemValue({
    required this.value, this.onlyDomestic = false, this.onlyInternational = false, this.voltage1000OnlyOn16_23Or50Hz = false
  });
}

const Map<String, List<UICWagonCodePassengerHeatingSystemValue>> UICWagonCodePassengerHeatingSystemValues = {
  '00': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true)],
  '02': [UICWagonCodePassengerHeatingSystemValue(value: '3000 ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '03': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true)],
  '05': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~')],
  '06': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_othervoltages')],
  '07': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '08': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '10': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '11': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '12': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '13': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '14': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '15': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '17': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam, onlyDomestic: true')],
  '18': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '19': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '20': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '21': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '22': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '23': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '24': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '25': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '26': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '27': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '28': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '29': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true)],
  '30': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '32': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '33': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyDomestic: true)],
  '34': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyDomestic: true)],
  '35': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '36': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '37': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '38': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '39': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '40': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '41': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '42': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '43': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyDomestic: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '44': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '45': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '46': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '47': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '48': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '50': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam')],
  '51': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '52': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '53': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '55': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '56': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_othervoltages')],
  '57': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '60': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '62': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '64': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '66': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '69': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true)],
  '70': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true)],
  '71': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '72': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', onlyDomestic: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', onlyDomestic: true)],
  '73': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true)],
  '74': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '75': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '76': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~')],
  '77': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '78': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '79': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '80': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '81': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '82': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '84': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '85': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam')],
  '86': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '87': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_othervoltages')],
  '88': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '89': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_airconditionseparate', onlyInternational: true)],
  '90': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =', voltage1000OnlyOn16_23Or50Hz: true, onlyInternational: true)],
  '91': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '92': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ='), UICWagonCodePassengerHeatingSystemValue(value: '3000 V ='), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_steam', onlyDomestic: true)],
  '93': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~')],
  '94': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '95': [UICWagonCodePassengerHeatingSystemValue(value: '1000 V ~')],
  '97': [UICWagonCodePassengerHeatingSystemValue(value: '1500 V ~'), UICWagonCodePassengerHeatingSystemValue(value: '1500 V =')],
  '98': [UICWagonCodePassengerHeatingSystemValue(value: '3000 V =')],
  '99': [UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyDomestic: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_selfheating', onlyInternational: true), UICWagonCodePassengerHeatingSystemValue(value: 'uic_passenger_heatingsystem_airconditionseparate', onlyInternational: true)],
};