part of 'package:gc_wizard/tools/science_and_technology/uic_wagoncode/logic/uic_wagoncode.dart';

class UICCountryCode {
  final String numberCode;
  final String name;
  final String letterCode;

  const UICCountryCode(this.numberCode, this.name, this.letterCode);
}

const List<UICCountryCode> UICCountryCodes = [
  UICCountryCode('10', 'common_country_Finland', 'FIN'),
  UICCountryCode('20', 'common_country_Russia', 'RUS'),
  UICCountryCode('21', 'common_country_Belarus', 'BLR'),
  UICCountryCode('22', 'common_country_Ukraine', 'UA'),
  UICCountryCode('23', 'common_country_Moldova', 'MD'),
  UICCountryCode('24', 'common_country_Lithuania', 'LT'),
  UICCountryCode('25', 'common_country_Latvia', 'LV'),
  UICCountryCode('26', 'common_country_Estonia', 'EST'),
  UICCountryCode('27', 'common_country_Kazakhstan', 'KZ'),
  UICCountryCode('28', 'common_country_Georgia', 'GE'),
  UICCountryCode('29', 'common_country_Uzbekistan', 'UZ'),
  UICCountryCode('30', 'common_country_NorthKorea', 'PRK'),
  UICCountryCode('31', 'common_country_Mongolia', 'MGL'),
  UICCountryCode('32', 'common_country_Vietnam', 'VN'),
  UICCountryCode('33', 'common_country_PeoplesRepublicofChina', 'RC'),
  UICCountryCode('40', 'common_country_Cuba', 'C'),
  UICCountryCode('41', 'common_country_Albania', 'AL'),
  UICCountryCode('42', 'common_country_Japan', 'J'),
  UICCountryCode('44', 'common_country_BosniaandHerzegovina', 'BIH'),
  UICCountryCode('49', 'common_country_BosniaandHerzegovina', 'BIH'),
  UICCountryCode('50', 'common_country_BosniaandHerzegovina', 'BIH'),
  UICCountryCode('51', 'common_country_Poland', 'PL'),
  UICCountryCode('52', 'common_country_Bulgaria', 'BG'),
  UICCountryCode('53', 'common_country_Romania', 'RO'),
  UICCountryCode('54', 'common_country_CzechRepublic', 'CZ'),
  UICCountryCode('55', 'common_country_Hungary', 'H'),
  UICCountryCode('56', 'common_country_Slovakia', 'SK'),
  UICCountryCode('57', 'common_country_Azerbaijan', 'AZ'),
  UICCountryCode('58', 'common_country_Armenia', 'ARM'),
  UICCountryCode('59', 'common_country_Kyrgyzstan', 'KS'),
  UICCountryCode('60', 'common_country_Ireland', 'IRL'),
  UICCountryCode('61', 'common_country_SouthKorea', 'ROK'),
  UICCountryCode('62', 'common_country_Montenegro', ''),
  UICCountryCode('65', 'common_country_NorthMacedonia', 'MK'),
  UICCountryCode('66', 'common_country_Tajikistan', 'TJ'),
  UICCountryCode('67', 'common_country_Turkmenistan', 'TM'),
  UICCountryCode('68', 'common_country_Afghanistan', ''),
  UICCountryCode('70', 'common_country_UnitedKingdom', 'GB'),
  UICCountryCode('71', 'common_country_Spain', 'E'),
  UICCountryCode('72', 'common_country_Serbia', 'YU'),
  UICCountryCode('73', 'common_country_Greece', 'GR'),
  UICCountryCode('74', 'common_country_Sweden', 'S'),
  UICCountryCode('75', 'common_country_Turkey', 'TR'),
  UICCountryCode('76', 'common_country_Norway', 'N'),
  UICCountryCode('78', 'common_country_Croatia', 'HR'),
  UICCountryCode('79', 'common_country_Slovenia', 'SLO'),
  UICCountryCode('80', 'common_country_Germany', 'D'),
  UICCountryCode('81', 'common_country_Austria', 'A'),
  UICCountryCode('82', 'common_country_Luxembourg', 'L'),
  UICCountryCode('83', 'common_country_Italy', 'I'),
  UICCountryCode('84', 'common_country_Netherlands', 'NL'),
  UICCountryCode('85', 'common_country_Switzerland', 'CH'),
  UICCountryCode('86', 'common_country_Denmark', 'DK'),
  UICCountryCode('87', 'common_country_France', 'F'),
  UICCountryCode('88', 'common_country_Belgium', 'B'),
  UICCountryCode('90', 'common_country_Egypt', 'ET'),
  UICCountryCode('91', 'common_country_Tunisia', 'TN'),
  UICCountryCode('92', 'common_country_Algeria', 'DZ'),
  UICCountryCode('93', 'common_country_Morocco', 'MA'),
  UICCountryCode('94', 'common_country_Portugal', 'P'),
  UICCountryCode('95', 'common_country_Israel', 'IL'),
  UICCountryCode('96', 'common_country_Iran', 'IR'),
  UICCountryCode('97', 'common_country_Syria', 'SYR'),
  UICCountryCode('98', 'common_country_Lebanon', 'RL'),
  UICCountryCode('99', 'common_country_Iraq', 'IRQ'),
];