part of 'package:gc_wizard/application/webapi/deeplinks/deeplinks.dart';

const Map<String, TextStyle> _openApiHiglightMap = {
  '"get"'  : TextStyle(color: Colors.blue),
  '"parameters"'  : TextStyle(color: Colors.blue),
  '"summary"'  : TextStyle(color: Colors.purple),
  '"responses"'  : TextStyle(color: Colors.purple),
  '"in"'  : TextStyle(color: Colors.purple),
  '"name"'  : TextStyle(color: Colors.purple),
  '"required"'  : TextStyle(color: Colors.purple),
  '"description"'  : TextStyle(color: Colors.purple),
  '"schema"'  : TextStyle(color: Colors.purple),
  '"type"'  : TextStyle(color: Colors.purple),
  '"enum"'  : TextStyle(color: Colors.green),
  '"default"'  : TextStyle(color: Colors.purple),
  '"string"'  : TextStyle(color: Colors.green),
  '"integer"'  : TextStyle(color: Colors.green),
  '"number"'  : TextStyle(color: Colors.green),
  '"boolean"'  : TextStyle(color: Colors.green),
  '"array"'  : TextStyle(color: Colors.green),
  '"object"'  : TextStyle(color: Colors.green),
  '"float"'  : TextStyle(color: Colors.green),
  '"double"'  : TextStyle(color: Colors.green),
  '"int32"'  : TextStyle(color: Colors.green),
  '"int64"'  : TextStyle(color: Colors.green),
  'true'  : TextStyle(color: Colors.green),
  'false'  : TextStyle(color: Colors.green),
  'null'  : TextStyle(color: Colors.green),
};