import 'package:gc_wizard/utils/common_utils.dart';

const alphabet_09 = {'0' : 0, '1' : 1, '2' : 2, '3' : 3, '4' : 4, '5' : 5, '6' : 6, '7' : 7, '8' : 8, '9' : 9};
final alphabet_09Indexes = switchMapKeyValue(alphabet_09);

const alphabet_AZ = {
  'A' : 1, 'B' : 2, 'C' : 3, 'D' : 4, 'E' : 5, 'F' : 6, 'G' : 7, 'H' : 8, 'I' : 9, 'J' : 10, 'K' : 11, 'L' : 12, 'M' : 13,
  'N' : 14, 'O' : 15, 'P' : 16, 'Q' : 17, 'R' : 18, 'S' : 19, 'T' : 20, 'U' : 21, 'V' : 22, 'W' : 23, 'X' : 24, 'Y' : 25, 'Z' : 26,
};
final alphabet_AZIndexes = switchMapKeyValue(alphabet_AZ);
final alphabet_AZString = alphabet_AZ.keys.join();

final superscriptCharacters = {
    '0' : '\u2070',
    '1' : '\u00B9',
    '2' : '\u00B2',
    '3' : '\u00B3',
    '4' : '\u2074',
    '5' : '\u2075',
    '6' : '\u2076',
    '7' : '\u2077',
    '8' : '\u2078',
    '9' : '\u2079',
    'a' : '\u1d43',
    'b' : '\u1d47',
    'c' : '\u1d9c',
    'd' : '\u1d48',
    'e' : '\u1d49',
    'f' : '\u1da0',
    'g' : '\u1d4d',
    'h' : '\u02b0',
    'i' : '\u2071',
    'j' : '\u02b2',
    'k' : '\u1d4f',
    'l' : '\u02e1',
    'm' : '\u1d50',
    'n' : '\u207f',
    'o' : '\u1d52',
    'p' : '\u1d56',
    //    'q' : missing in Unicode
    'r' : '\u02b3',
    's' : '\u02e2',
    't' : '\u1d57',
    'u' : '\u1d58',
    'v' : '\u1d5b',
    'w' : '\u02b7',
    'x' : '\u02e3',
    'y' : '\u02b8',
    'z' : '\u1dbb',
    'A' : '\u1d2c',
    'B' : '\u1d2e',
    //    'C' : missing in Unicode
    'D' : '\u1d30',
    'E' : '\u1d31',
    //    'F' : missing in Unicode
    'G' : '\u1d33',
    'H' : '\u1d34',
    'I' : '\u1d35',
    'J' : '\u1d36',
    'K' : '\u1d37',
    'L' : '\u1d38',
    'M' : '\u1d39',
    'N' : '\u1d3a',
    'O' : '\u1d3c',
    'P' : '\u1d3e',
    //    'Q' : missing in Unicode
    'R' : '\u1d3f',
    //    'S' : missing in Unicode
    'T' : '\u1d40',
    'U' : '\u1d41',
    'V' : '\u2c7d',
    'W' : '\u1d42',
    //    'X' : missing in Unicode
    //    'Y' : missing in Unicode
    //    'Z' : missing in Unicode
    '+' : '\u207A',
    '-' : '\u207B',
    '=' : '\u207C',
    '(' : '\u207D',
    ')' : '\u207E',
};

final subscriptCharacters = {
    '0' : '\u2080',
    '1' : '\u2081',
    '2' : '\u2082',
    '3' : '\u2083',
    '4' : '\u2084',
    '5' : '\u2085',
    '6' : '\u2086',
    '7' : '\u2087',
    '8' : '\u2088',
    '9' : '\u2089',
    'a' : '\u2090',
//    'b' : missing in Unicode,
//    'c' : missing in Unicode,
//    'd' : missing in Unicode,
    'e' : '\u2091',
//    'f' : missing in Unicode,
//    'g' : missing in Unicode,
    'h' : '\u2095',
    'i' : '\u1d62',
    'j' : '\u2c7c',
    'k' : '\u2096',
    'l' : '\u2097',
    'm' : '\u2098',
    'n' : '\u2099',
    'o' : '\u2092',
    'p' : '\u209a',
//    'q' : missing in Unicode,
    'r' : '\u1d63',
    's' : '\u209b',
    't' : '\u209c',
    'u' : '\u1d64',
    'v' : '\u1d65',
//    'w' : missing in Unicode,
    'x' : '\u2093',
//    'y' : missing in Unicode,
//    'z' : missing in Unicode,
//    'A' : missing in Unicode,
//    'B' : missing in Unicode,
//    'C' : missing in Unicode,
//    'D' : missing in Unicode,
//    'E' : missing in Unicode,
//    'F' : missing in Unicode,
//    'G' : missing in Unicode,
//    'H' : missing in Unicode,
//    'I' : missing in Unicode,
//    'J' : missing in Unicode,
//    'K' : missing in Unicode,
//    'L' : missing in Unicode,
//    'M' : missing in Unicode,
//    'N' : missing in Unicode,
//    'O' : missing in Unicode,
//    'P' : missing in Unicode,
//    'Q' : missing in Unicode,
//    'R' : missing in Unicode,
//    'S' : missing in Unicode,
//    'T' : missing in Unicode,
//    'U' : missing in Unicode,
//    'V' : missing in Unicode,
//    'W' : missing in Unicode,
//    'X' : missing in Unicode,
//    'Y' : missing in Unicode,
//    'Z' : missing in Unicode,
    '+' : '\u208A',
    '-' : '\u208B',
    '=' : '\u208C',
    '(' : '\u208D',
    ')' : '\u208E',
};