// https://en.wikipedia.org/wiki/Spelling_alphabet
// https://en.wikipedia.org/wiki/Allied_military_phonetic_spelling_alphabets
// https://en.wikipedia.org/wiki/NATO_phonetic_alphabet
// https://jumk.de/alphabete/polnisch.shtml
// https://en.wikipedia.org/wiki/Russian_spelling_alphabet
// https://en.wikipedia.org/wiki/Greek_spelling_alphabet

import 'dart:ui';

enum SPELLING {
  ICAO1947,
  NATO,
  USNAVY1908_1,
  USNAVY1908_2,
  USNAVY1920,
  USNAVY1942,
  APCO1967,
  APCO1974,
  ARRL1930,
  ARRL1936,
  ARRL1946,
  ARRL1970,
  ARRLDX,
  EPO,
  FRA,
  FRABEL,
  CHE,
  FRACAN,
  DEU1950,
  DEU2022,
  DEUDDR,
  AUT,
  NLD,
  BEL,
  ITA,
  ESP,
  BRA,
  POR,
  SWE,
  DNK,
  NOR,
  FIN,
  TUR,
  ROU,
  CZE,
  YUG,
  SRB,
  SLO,
  POL,
  SVK,
  RUS,
  RUSLAT,
  GRC,
  GRCLAT,
}

const Map<SPELLING, String> SPELLING_LIST = {
  SPELLING.ICAO1947: "spelling_alphabets_language_ICAO1947",
  SPELLING.NATO: "spelling_alphabets_language_nato",
  SPELLING.USNAVY1908_1: "spelling_alphabets_language_usnavy_1908_1",
  SPELLING.USNAVY1908_2: "spelling_alphabets_language_usnavy_1908_2",
  SPELLING.USNAVY1920: "spelling_alphabets_language_usnavy_1920",
  SPELLING.USNAVY1942: "spelling_alphabets_language_usnavy_1942",
  SPELLING.APCO1967: "spelling_alphabets_language_APCO1967",
  SPELLING.APCO1974: "spelling_alphabets_language_APCO1974",
  SPELLING.ARRL1930: "spelling_alphabets_language_ARRL1930",
  SPELLING.ARRL1936: "spelling_alphabets_language_ARRL1936",
  SPELLING.ARRL1946: "spelling_alphabets_language_ARRL1946",
  SPELLING.ARRL1970: "spelling_alphabets_language_ARRL1970",
  SPELLING.ARRLDX: "spelling_alphabets_language_ARRLDX",
  SPELLING.FRA: "common_country_France",
  SPELLING.FRABEL: "common_country_Belgium",
  SPELLING.CHE: "common_country_Switzerland",
  SPELLING.FRACAN: "spelling_alphabets_language_quebec",
  SPELLING.DEU1950: "spelling_alphabets_language_deu1950",
  SPELLING.DEU2022: "spelling_alphabets_language_deu2022",
  SPELLING.AUT: "common_country_Austria",
  SPELLING.DEUDDR: "spelling_alphabets_language_gdr",
  SPELLING.NLD: "common_country_Netherlands",
  SPELLING.EPO: "spelling_alphabets_language_esperanto",
  SPELLING.BEL: "spelling_alphabets_language_belflemish",
  SPELLING.ITA: "common_country_Italy",
  SPELLING.ESP: "common_country_Spain",
  SPELLING.BRA: "common_country_Brazil",
  SPELLING.POR: "common_country_Portugal",
  SPELLING.SWE: "common_country_Sweden",
  SPELLING.DNK: "common_country_Denmark",
  SPELLING.NOR: "common_country_Norway",
  SPELLING.FIN: "common_country_Finland",
  SPELLING.TUR: "common_country_Turkey",
  SPELLING.ROU: "common_country_Romania",
  SPELLING.CZE: "common_country_CzechRepublic",
  SPELLING.YUG: "spelling_alphabets_language_yug",
  SPELLING.SRB: "common_country_Serbia",
  SPELLING.SLO: "common_country_Slovenia",
  SPELLING.POL: "common_country_Poland",
  SPELLING.RUS: "common_country_Russia",
  SPELLING.RUSLAT: "spelling_alphabets_language_ruslat",
  SPELLING.GRC: "common_country_Greece",
  SPELLING.GRCLAT: "spelling_alphabets_language_grclat",
};

const List<MapEntry<String, String>> _spellingARRL1930 = [
  MapEntry<String, String>("A", "Adams"),
  MapEntry<String, String>("B", "Boston"),
  MapEntry<String, String>("C", "Chicago"),
  MapEntry<String, String>("D", "Denver"),
  MapEntry<String, String>("E", "Edward"),
  MapEntry<String, String>("F", "Frank"),
  MapEntry<String, String>("G", "George"),
  MapEntry<String, String>("H", "Henry"),
  MapEntry<String, String>("I", "Ida"),
  MapEntry<String, String>("J", "John"),
  MapEntry<String, String>("K", "King"),
  MapEntry<String, String>("L", "Lincoln"),
  MapEntry<String, String>("M", "Mary"),
  MapEntry<String, String>("N", "New York"),
  MapEntry<String, String>("O", "Ocean"),
  MapEntry<String, String>("P", "Peter"),
  MapEntry<String, String>("Q", "Queen"),
  MapEntry<String, String>("R", "Robert"),
  MapEntry<String, String>("S", "Sugar"),
  MapEntry<String, String>("T", "Thomas"),
  MapEntry<String, String>("U", "Union"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Young"),
  MapEntry<String, String>("Z", "Zero"),
];
const List<MapEntry<String, String>> _spellingARRL1936 = [
  MapEntry<String, String>("A", "Able"),
  MapEntry<String, String>("B", "Boy"),
  MapEntry<String, String>("C", "Cast"),
  MapEntry<String, String>("D", "Dog"),
  MapEntry<String, String>("E", "Easy"),
  MapEntry<String, String>("F", "Fox"),
  MapEntry<String, String>("G", "George"),
  MapEntry<String, String>("H", "Have"),
  MapEntry<String, String>("I", "Item"),
  MapEntry<String, String>("J", "Jig"),
  MapEntry<String, String>("K", "King"),
  MapEntry<String, String>("L", "Love"),
  MapEntry<String, String>("M", "Mike"),
  MapEntry<String, String>("N", "Nan"),
  MapEntry<String, String>("O", "Oboe"),
  MapEntry<String, String>("P", "Pup"),
  MapEntry<String, String>("Q", "Quack"),
  MapEntry<String, String>("R", "Rot"),
  MapEntry<String, String>("S", "Sail"),
  MapEntry<String, String>("T", "Tare"),
  MapEntry<String, String>("U", "Unit"),
  MapEntry<String, String>("V", "Vice"),
  MapEntry<String, String>("W", "Watch"),
  MapEntry<String, String>("X", "X-ray"),
  MapEntry<String, String>("Y", "Yoke"),
  MapEntry<String, String>("Z", "Zed"),
];
const List<MapEntry<String, String>> _spellingARRL1946 = [
  MapEntry<String, String>("A", "ADAM"),
  MapEntry<String, String>("B", "BAKER"),
  MapEntry<String, String>("C", "CHARLIE"),
  MapEntry<String, String>("D", "DAVID"),
  MapEntry<String, String>("E", "EDWARD"),
  MapEntry<String, String>("F", "FRANK"),
  MapEntry<String, String>("G", "GEORGE"),
  MapEntry<String, String>("H", "HENRY"),
  MapEntry<String, String>("I", "IDA"),
  MapEntry<String, String>("J", "JOHN"),
  MapEntry<String, String>("K", "KING"),
  MapEntry<String, String>("L", "LEWIS"),
  MapEntry<String, String>("M", "MARY"),
  MapEntry<String, String>("N", "NANCY"),
  MapEntry<String, String>("O", "OTTO"),
  MapEntry<String, String>("P", "PETER"),
  MapEntry<String, String>("Q", "QUEEN"),
  MapEntry<String, String>("R", "ROBERT"),
  MapEntry<String, String>("S", "SUSAN"),
  MapEntry<String, String>("T", "THOMAS"),
  MapEntry<String, String>("U", "UNION"),
  MapEntry<String, String>("V", "VICTOR"),
  MapEntry<String, String>("W", "WILLIAM"),
  MapEntry<String, String>("X", "X-RAY"),
  MapEntry<String, String>("Y", "YOUNG"),
  MapEntry<String, String>("Z", "ZEBRA"),
];
const List<MapEntry<String, String>> _spellingARRLDX = [
  MapEntry<String, String>("A", "America"),
  MapEntry<String, String>("B", "Boston"),
  MapEntry<String, String>("C", "Canada"),
  MapEntry<String, String>("D", "Denmark"),
  MapEntry<String, String>("E", "England"),
  MapEntry<String, String>("F", "France"),
  MapEntry<String, String>("G", "Germany"),
  MapEntry<String, String>("H", "Honolulu"),
  MapEntry<String, String>("I", "Italy"),
  MapEntry<String, String>("J", "Japan"),
  MapEntry<String, String>("K", "Kilowatt"),
  MapEntry<String, String>("L", "London"),
  MapEntry<String, String>("M", "Mexico"),
  MapEntry<String, String>("N", "Norway"),
  MapEntry<String, String>("O", "Ontario"),
  MapEntry<String, String>("P", "Pacific"),
  MapEntry<String, String>("Q", "Quebec"),
  MapEntry<String, String>("R", "Radio"),
  MapEntry<String, String>("S", "Santiago"),
  MapEntry<String, String>("T", "Tokyo"),
  MapEntry<String, String>("U", "United"),
  MapEntry<String, String>("V", "Victoria"),
  MapEntry<String, String>("W", "Washington"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Yokohama"),
  MapEntry<String, String>("Z", "Zanzibar"),
];
const List<MapEntry<String, String>> _spellingUSNAVY1908_1 = [
  MapEntry<String, String>("A", "Actor"),
  MapEntry<String, String>("B", "Baker"),
  MapEntry<String, String>("C", "Canteen"),
  MapEntry<String, String>("D", "Diver"),
  MapEntry<String, String>("E", "Eagle"),
  MapEntry<String, String>("F", "Fisher"),
  MapEntry<String, String>("G", "Gangway"),
  MapEntry<String, String>("H", "Halliard"),
  MapEntry<String, String>("I", "Insect"),
  MapEntry<String, String>("J", "Jockey"),
  MapEntry<String, String>("K", "Knapsack"),
  MapEntry<String, String>("L", "Lugger"),
  MapEntry<String, String>("M", "Musket"),
  MapEntry<String, String>("N", "Neptune"),
  MapEntry<String, String>("O", "Oyster"),
  MapEntry<String, String>("P", "Pistol"),
  MapEntry<String, String>("Q", "Quadrant"),
  MapEntry<String, String>("R", "Reefer"),
  MapEntry<String, String>("S", "Shipmate"),
  MapEntry<String, String>("T", "Topsail"),
  MapEntry<String, String>("U", "Unload"),
  MapEntry<String, String>("V", "Vessel"),
  MapEntry<String, String>("W", "Windage"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Yeoman"),
  MapEntry<String, String>("Z", "Zebra"),
];
const List<MapEntry<String, String>> _spellingUSNAVY1908_2 = [
  MapEntry<String, String>("A", "Ash"),
  MapEntry<String, String>("B", "Back"),
  MapEntry<String, String>("C", "Chain"),
  MapEntry<String, String>("D", "Dog"),
  MapEntry<String, String>("E", "Egg"),
  MapEntry<String, String>("F", "Fox"),
  MapEntry<String, String>("G", "Gig"),
  MapEntry<String, String>("H", "Horse"),
  MapEntry<String, String>("I", "Ice"),
  MapEntry<String, String>("J", "Jake"),
  MapEntry<String, String>("K", "King"),
  MapEntry<String, String>("L", "Lash"),
  MapEntry<String, String>("M", "Mule"),
  MapEntry<String, String>("N", "Net"),
  MapEntry<String, String>("O", "Oak"),
  MapEntry<String, String>("P", "Page"),
  MapEntry<String, String>("Q", "Quail"),
  MapEntry<String, String>("R", "Raft"),
  MapEntry<String, String>("S", "Scout"),
  MapEntry<String, String>("T", "Tide"),
  MapEntry<String, String>("U", "Use"),
  MapEntry<String, String>("V", "Vast"),
  MapEntry<String, String>("W", "Winch"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Yacht"),
  MapEntry<String, String>("Z", "Zoo"),
];
const List<MapEntry<String, String>> _spellingUSNAVY1920 = [
  MapEntry<String, String>("A", "Argentine"),
  MapEntry<String, String>("B", "Brussels"),
  MapEntry<String, String>("C", "Canada"),
  MapEntry<String, String>("D", "Damascus"),
  MapEntry<String, String>("E", "Ecuador"),
  MapEntry<String, String>("F", "France"),
  MapEntry<String, String>("G", "Greece"),
  MapEntry<String, String>("H", "Hanover"),
  MapEntry<String, String>("I", "Italy"),
  MapEntry<String, String>("J", "Japan"),
  MapEntry<String, String>("K", "Khartoum"),
  MapEntry<String, String>("L", "Lima"),
  MapEntry<String, String>("M", "Madrid"),
  MapEntry<String, String>("N", "Nancy"),
  MapEntry<String, String>("O", "Ostend"),
  MapEntry<String, String>("P", "Paris"),
  MapEntry<String, String>("Q", "Quebec"),
  MapEntry<String, String>("R", "Rome"),
  MapEntry<String, String>("S", "Sardinia"),
  MapEntry<String, String>("T", "Tokio"),
  MapEntry<String, String>("U", "Uruguay"),
  MapEntry<String, String>("V", "Victoria"),
  MapEntry<String, String>("W", "Washington"),
  MapEntry<String, String>("X", "Xaintrie"),
  MapEntry<String, String>("Y", "Yokohama"),
  MapEntry<String, String>("Z", "Zanzibar"),
];
const List<MapEntry<String, String>> _spellingUSNAVY1942 = [
  MapEntry<String, String>("A", "Afirm"),
  MapEntry<String, String>("B", "Baker"),
  MapEntry<String, String>("C", "Cast"),
  MapEntry<String, String>("D", "Dog"),
  MapEntry<String, String>("E", "Easy"),
  MapEntry<String, String>("F", "Fox"),
  MapEntry<String, String>("G", "George"),
  MapEntry<String, String>("H", "Hypo"),
  MapEntry<String, String>("I", "Int"),
  MapEntry<String, String>("J", "Jig"),
  MapEntry<String, String>("K", "King"),
  MapEntry<String, String>("L", "Love"),
  MapEntry<String, String>("M", "Mike"),
  MapEntry<String, String>("N", "Negat"),
  MapEntry<String, String>("O", "Option"),
  MapEntry<String, String>("P", "Prep"),
  MapEntry<String, String>("Q", "Queen"),
  MapEntry<String, String>("R", "Roger"),
  MapEntry<String, String>("S", "Sail"),
  MapEntry<String, String>("T", "Tare"),
  MapEntry<String, String>("U", "Unit"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Yoke"),
  MapEntry<String, String>("Z", "Zed"),
];
const List<MapEntry<String, String>> _spellingICAO1947 = [
  MapEntry<String, String>("A", "Able"),
  MapEntry<String, String>("B", "Baker"),
  MapEntry<String, String>("C", "Charlie"),
  MapEntry<String, String>("D", "Dog"),
  MapEntry<String, String>("E", "Easy"),
  MapEntry<String, String>("F", "Fox"),
  MapEntry<String, String>("G", "George"),
  MapEntry<String, String>("H", "How"),
  MapEntry<String, String>("I", "Item"),
  MapEntry<String, String>("J", "Jig"),
  MapEntry<String, String>("K", "King"),
  MapEntry<String, String>("L", "Love"),
  MapEntry<String, String>("M", "Mike"),
  MapEntry<String, String>("N", "Nan"),
  MapEntry<String, String>("O", "Oboe"),
  MapEntry<String, String>("P", "Peter"),
  MapEntry<String, String>("Q", "Queen"),
  MapEntry<String, String>("R", "Roger"),
  MapEntry<String, String>("S", "Sugar"),
  MapEntry<String, String>("T", "Tare"),
  MapEntry<String, String>("U", "Uncle"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Yoke"),
  MapEntry<String, String>("Z", "Zebra"),
];
const List<MapEntry<String, String>> _spellingAPCO1967 = [
  MapEntry<String, String>("A", "Adam"),
  MapEntry<String, String>("B", "Boy"),
  MapEntry<String, String>("C", "Charles"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Edward"),
  MapEntry<String, String>("F", "Frank"),
  MapEntry<String, String>("G", "George"),
  MapEntry<String, String>("H", "Henry"),
  MapEntry<String, String>("I", "Ida"),
  MapEntry<String, String>("J", "John"),
  MapEntry<String, String>("K", "King"),
  MapEntry<String, String>("L", "Lincoln"),
  MapEntry<String, String>("M", "Mary"),
  MapEntry<String, String>("N", "Nora"),
  MapEntry<String, String>("O", "Ocean"),
  MapEntry<String, String>("P", "Paul"),
  MapEntry<String, String>("Q", "Queen"),
  MapEntry<String, String>("R", "Robert"),
  MapEntry<String, String>("S", "Sam"),
  MapEntry<String, String>("T", "Tom"),
  MapEntry<String, String>("U", "Union"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "X-Ray"),
  MapEntry<String, String>("Y", "Young"),
  MapEntry<String, String>("Z", "Zebra"),
];
const List<MapEntry<String, String>> _spellingNATO = [
  MapEntry<String, String>("A", "Alpha"),
  MapEntry<String, String>("A", "Alfa"),
  MapEntry<String, String>("B", "Bravo"),
  MapEntry<String, String>("C", "Charlie"),
  MapEntry<String, String>("D", "Delta"),
  MapEntry<String, String>("E", "Echo"),
  MapEntry<String, String>("F", "Foxtrot"),
  MapEntry<String, String>("G", "Golf"),
  MapEntry<String, String>("H", "Hotel"),
  MapEntry<String, String>("I", "India"),
  MapEntry<String, String>("J", "Juliet"),
  MapEntry<String, String>("K", "Kilo"),
  MapEntry<String, String>("L", "Lima"),
  MapEntry<String, String>("M", "Mike"),
  MapEntry<String, String>("N", "November"),
  MapEntry<String, String>("O", "Oscar"),
  MapEntry<String, String>("P", "Papa"),
  MapEntry<String, String>("Q", "Quebec"),
  MapEntry<String, String>("R", "Romeo"),
  MapEntry<String, String>("S", "Sierra"),
  MapEntry<String, String>("T", "Tango"),
  MapEntry<String, String>("U", "Uniform"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "Whiskey"),
  MapEntry<String, String>("X", "X-ray"),
  MapEntry<String, String>("Y", "Yankee"),
  MapEntry<String, String>("Z", "Zulu"),
];
const List<MapEntry<String, String>> _spellingFRA = [
  MapEntry<String, String>("A", "Anatole"),
  MapEntry<String, String>("B", "Berthe"),
  MapEntry<String, String>("C", "Célestin"),
  MapEntry<String, String>("D", "Désiré"),
  MapEntry<String, String>("E", "Eugène"),
  MapEntry<String, String>("F", "François"),
  MapEntry<String, String>("G", "Gaston"),
  MapEntry<String, String>("H", "Henri"),
  MapEntry<String, String>("I", "Irma"),
  MapEntry<String, String>("J", "Joseph"),
  MapEntry<String, String>("K", "Kléber"),
  MapEntry<String, String>("L", "Louis"),
  MapEntry<String, String>("M", "Marcel"),
  MapEntry<String, String>("N", "Nicolas"),
  MapEntry<String, String>("O", "Oscar"),
  MapEntry<String, String>("P", "Pierre"),
  MapEntry<String, String>("Q", "Quintal"),
  MapEntry<String, String>("R", "Raoul"),
  MapEntry<String, String>("S", "Suzanne"),
  MapEntry<String, String>("T", "Thérèse"),
  MapEntry<String, String>("U", "Ursule"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "Xavier"),
  MapEntry<String, String>("Y", "Yvonne"),
  MapEntry<String, String>("Z", "Zoé"),
];
const List<MapEntry<String, String>> _spellingFRABEL = [
  MapEntry<String, String>("A", "Arthur"),
  MapEntry<String, String>("B", "Bruxelles"),
  MapEntry<String, String>("C", "César"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Émile"),
  MapEntry<String, String>("F", "Frédéric"),
  MapEntry<String, String>("G", "Gustave"),
  MapEntry<String, String>("H", "Henri"),
  MapEntry<String, String>("I", "Isidor"),
  MapEntry<String, String>("J", "Joseph"),
  MapEntry<String, String>("K", "Kilogramme"),
  MapEntry<String, String>("L", "Léopold"),
  MapEntry<String, String>("M", "Marie"),
  MapEntry<String, String>("N", "Napoléon"),
  MapEntry<String, String>("O", "Oscar"),
  MapEntry<String, String>("P", "Piano"),
  MapEntry<String, String>("Q", "Quiévrain"),
  MapEntry<String, String>("R", "Robert"),
  MapEntry<String, String>("S", "Simon"),
  MapEntry<String, String>("T", "Téléphone"),
  MapEntry<String, String>("U", "Ursule"),
  MapEntry<String, String>("V", ""),
  MapEntry<String, String>("W", "Waterloo"),
  MapEntry<String, String>("X", "Xantippe"),
  MapEntry<String, String>("Y", ""),
  MapEntry<String, String>("Z", "Zéro"),
];
const List<MapEntry<String, String>> _spellingFRACAN = [
  MapEntry<String, String>("A", "Alice"),
  MapEntry<String, String>("B", "Berthe"),
  MapEntry<String, String>("C", "Charles"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Édouard"),
  MapEntry<String, String>("F", "François"),
  MapEntry<String, String>("G", "George"),
  MapEntry<String, String>("H", "Henri"),
  MapEntry<String, String>("I", "Isabelle"),
  MapEntry<String, String>("J", "Jacques"),
  MapEntry<String, String>("K", "Kilo"),
  MapEntry<String, String>("L", "Louis"),
  MapEntry<String, String>("M", "Marie"),
  MapEntry<String, String>("N", "Nicolas"),
  MapEntry<String, String>("O", "Olivier"),
  MapEntry<String, String>("P", "Pierre"),
  MapEntry<String, String>("Q", "Québec"),
  MapEntry<String, String>("R", "Robert"),
  MapEntry<String, String>("S", "Samuel"),
  MapEntry<String, String>("T", "Thomas"),
  MapEntry<String, String>("U", "Ursule"),
  MapEntry<String, String>("V", ""),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "Xavier"),
  MapEntry<String, String>("Y", ""),
  MapEntry<String, String>("Z", "Zoé"),
];
const List<MapEntry<String, String>> _spellingCHE = [
  MapEntry<String, String>("A", "Anna"),
  MapEntry<String, String>("B", "Berthe"),
  MapEntry<String, String>("C", "Cécile"),
  MapEntry<String, String>("D", "Daniel"),
  MapEntry<String, String>("E", "Émile"),
  MapEntry<String, String>("F", "François"),
  MapEntry<String, String>("G", "Gustave"),
  MapEntry<String, String>("H", "Henri"),
  MapEntry<String, String>("I", "Ida"),
  MapEntry<String, String>("J", "Jeanne"),
  MapEntry<String, String>("K", "Kilo"),
  MapEntry<String, String>("L", "Louise"),
  MapEntry<String, String>("M", "Marie"),
  MapEntry<String, String>("N", "Nicolas"),
  MapEntry<String, String>("O", "Olga"),
  MapEntry<String, String>("P", "Paul"),
  MapEntry<String, String>("Q", "Quittance"),
  MapEntry<String, String>("R", "Robert"),
  MapEntry<String, String>("S", "Suzanne"),
  MapEntry<String, String>("T", "Thérèse"),
  MapEntry<String, String>("U", "Ulysse"),
  MapEntry<String, String>("V", ""),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "Xavier"),
  MapEntry<String, String>("Y", ""),
  MapEntry<String, String>("Z", "Zurich"),
];
const List<MapEntry<String, String>> _spellingDEU1950 = [
  MapEntry<String, String>("A", "Anton"),
  MapEntry<String, String>("Ä", "Ärger"),
  MapEntry<String, String>("B", "Berta"),
  MapEntry<String, String>("C", "Cäsar"),
  MapEntry<String, String>("CH", "Charlotte"),
  MapEntry<String, String>("D", "Dora"),
  MapEntry<String, String>("E", "Emil"),
  MapEntry<String, String>("F", "Friedrich"),
  MapEntry<String, String>("G", "Gustav"),
  MapEntry<String, String>("H", "Heinrich"),
  MapEntry<String, String>("I", "Ida"),
  MapEntry<String, String>("J", "Julius"),
  MapEntry<String, String>("K", "Kaufmann"),
  MapEntry<String, String>("L", "Ludwig"),
  MapEntry<String, String>("M", "Martha"),
  MapEntry<String, String>("N", "Nordpol"),
  MapEntry<String, String>("O", "Otto"),
  MapEntry<String, String>("Ö", "Ökonom"),
  MapEntry<String, String>("P", "Paula"),
  MapEntry<String, String>("Q", "Quelle"),
  MapEntry<String, String>("R", "Richard"),
  MapEntry<String, String>("S", "Samuel"),
  MapEntry<String, String>("T", "Theodor"),
  MapEntry<String, String>("U", "Ulrich"),
  MapEntry<String, String>("Ü", "Übermut"),
  MapEntry<String, String>("V", "Viktor"),
  MapEntry<String, String>("W", "Wilhelm"),
  MapEntry<String, String>("X", "Xanthippe"),
  MapEntry<String, String>("Y", "Ypsilon"),
  MapEntry<String, String>("Z", "Zacharias"),
];
const List<MapEntry<String, String>> _spellingDEU2022 = [
  MapEntry<String, String>("A", "Aachen"),
  MapEntry<String, String>("B", "Berlin"),
  MapEntry<String, String>("C", "Chemnitz"),
  MapEntry<String, String>("D", "Düsseldorf"),
  MapEntry<String, String>("E", "Essen"),
  MapEntry<String, String>("F", "Frankfurt"),
  MapEntry<String, String>("G", "Goslar"),
  MapEntry<String, String>("H", "Hamburg"),
  MapEntry<String, String>("I", "Ingelheim"),
  MapEntry<String, String>("J", "Jena"),
  MapEntry<String, String>("K", "Köln"),
  MapEntry<String, String>("L", "Leipzig"),
  MapEntry<String, String>("M", "München"),
  MapEntry<String, String>("N", "Nürnberg"),
  MapEntry<String, String>("O", "Offenbach"),
  MapEntry<String, String>("P", "Potsdam"),
  MapEntry<String, String>("Q", "Quickborn"),
  MapEntry<String, String>("R", "Rostock"),
  MapEntry<String, String>("S", "Salzwedel"),
  MapEntry<String, String>("T", "Tübingen"),
  MapEntry<String, String>("U", "Unna"),
  MapEntry<String, String>("V", "Völklingen"),
  MapEntry<String, String>("W", "Wuppertal"),
  MapEntry<String, String>("X", "Xanten"),
  MapEntry<String, String>("Y", "Ypsilon"),
  MapEntry<String, String>("Z", "Zwickau"),
];
const List<MapEntry<String, String>> _spellingAUT = [
  MapEntry<String, String>("A", "Anton"),
  MapEntry<String, String>("Ä", "Ärger"),
  MapEntry<String, String>("B", "Berta"),
  MapEntry<String, String>("C", "Cäsar"),
  MapEntry<String, String>("CH", "Charlotte"),
  MapEntry<String, String>("D", "Dora"),
  MapEntry<String, String>("E", "Emil"),
  MapEntry<String, String>("F", "Friedrich"),
  MapEntry<String, String>("G", "Gustav"),
  MapEntry<String, String>("H", "Heinrich"),
  MapEntry<String, String>("I", "Ida"),
  MapEntry<String, String>("J", "Julius"),
  MapEntry<String, String>("K", "Konrad"),
  MapEntry<String, String>("L", "Ludwig"),
  MapEntry<String, String>("M", "Martha"),
  MapEntry<String, String>("N", "Nordpol"),
  MapEntry<String, String>("O", "Otto"),
  MapEntry<String, String>("Ö", "Österreich"),
  MapEntry<String, String>("P", "Paula"),
  MapEntry<String, String>("Q", "Quelle"),
  MapEntry<String, String>("R", "Richard"),
  MapEntry<String, String>("S", "Siegfried"),
  MapEntry<String, String>("T", "Theodor"),
  MapEntry<String, String>("U", "Ulrich"),
  MapEntry<String, String>("Ü", "Übel"),
  MapEntry<String, String>("V", "Viktor"),
  MapEntry<String, String>("W", "Wilhelm"),
  MapEntry<String, String>("X", "Xaver"),
  MapEntry<String, String>("Y", "Ypsilon"),
  MapEntry<String, String>("Z", "Zürich"),
];
const List<MapEntry<String, String>> _spellingEPO = [
  MapEntry<String, String>("A", "Asfalto"),
  MapEntry<String, String>("B", "Barbaro"),
  MapEntry<String, String>("C", "Centimetro"),
  MapEntry<String, String>("CH", "Charlotte"),
  MapEntry<String, String>("D", "Doktoro"),
  MapEntry<String, String>("E", "Elemento"),
  MapEntry<String, String>("F", "Fabriko"),
  MapEntry<String, String>("G", "Gumo"),
  MapEntry<String, String>("H", "Hotelo"),
  MapEntry<String, String>("I", "Insekto"),
  MapEntry<String, String>("J", "Jubileo"),
  MapEntry<String, String>("K", "Kilogramo"),
  MapEntry<String, String>("L", "Legendo"),
  MapEntry<String, String>("M", "Maŝino"),
  MapEntry<String, String>("N", "Naturo"),
  MapEntry<String, String>("O", "Omnibuso"),
  MapEntry<String, String>("P", "Papero"),
  MapEntry<String, String>("Q", "Kuo"),
  MapEntry<String, String>("R", "Rekordo"),
  MapEntry<String, String>("S", "Salato"),
  MapEntry<String, String>("T", "Triumfo"),
  MapEntry<String, String>("U", "Universo"),
  MapEntry<String, String>("V", "Vulkano"),
  MapEntry<String, String>("W", "Vo"),
  MapEntry<String, String>("X", "Ikso"),
  MapEntry<String, String>("Y", "Ipsilono"),
  MapEntry<String, String>("Z", "Zinko"),
];
const List<MapEntry<String, String>> _spellingNLD = [
  //http://www.spellingsalfabet.nl/
  MapEntry<String, String>("A", "Anna"),
  MapEntry<String, String>("B", "Bernhard"),
  MapEntry<String, String>("C", "Cornelis"),
  MapEntry<String, String>("D", "Dirk"),
  MapEntry<String, String>("E", "Eduard"),
  MapEntry<String, String>("F", "Ferdinand"),
  MapEntry<String, String>("G", "Gerard"),
  MapEntry<String, String>("H", "Hendrik"),
  MapEntry<String, String>("I", "Izaak"),
  MapEntry<String, String>("IJ", "IJmuiden"),
  MapEntry<String, String>("J", "Jan"),
  MapEntry<String, String>("K", "Karel"),
  MapEntry<String, String>("L", "Lodewijk"),
  MapEntry<String, String>("M", "Maria"),
  MapEntry<String, String>("N", "Nico"),
  MapEntry<String, String>("O", "Otto"),
  MapEntry<String, String>("P", "Pieter"),
  MapEntry<String, String>("Q", "Qutient"),
  MapEntry<String, String>("R", "Rudolf"),
  MapEntry<String, String>("S", "Simon"),
  MapEntry<String, String>("T", "Teunis"),
  MapEntry<String, String>("U", "Utrecht"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "Willem"),
  MapEntry<String, String>("X", "Xantippe"),
  MapEntry<String, String>("Y", "Ypsilon"),
  MapEntry<String, String>("Z", "Zaandam"),
];
const List<MapEntry<String, String>> _spellingBEL = [
  MapEntry<String, String>("A", "Arthur"),
  MapEntry<String, String>("B", "Brussel"),
  MapEntry<String, String>("C", "Carolina"),
  MapEntry<String, String>("D", "Desiré"),
  MapEntry<String, String>("E", "Emiel"),
  MapEntry<String, String>("F", "Frederik"),
  MapEntry<String, String>("G", "Gustaaf"),
  MapEntry<String, String>("H", "Hendrik"),
  MapEntry<String, String>("I", "Isidoor"),
  MapEntry<String, String>("J", "Jozef"),
  MapEntry<String, String>("K", "Kilogram"),
  MapEntry<String, String>("L", "Leopold"),
  MapEntry<String, String>("M", "Maria"),
  MapEntry<String, String>("N", "Napoleon"),
  MapEntry<String, String>("O", "Oscar"),
  MapEntry<String, String>("P", "Piano"),
  MapEntry<String, String>("Q", "Quotiënt"),
  MapEntry<String, String>("R", "Robert"),
  MapEntry<String, String>("S", "Sofie"),
  MapEntry<String, String>("T", "Telefoon"),
  MapEntry<String, String>("U", "Ursula"),
  MapEntry<String, String>("V", "Victor"),
  MapEntry<String, String>("W", "Waterloo"),
  MapEntry<String, String>("X", "Xavier"),
  MapEntry<String, String>("Y", "Yvonne"),
  MapEntry<String, String>("Z", "Zola"),
];
const List<MapEntry<String, String>> _spellingITA = [
  MapEntry<String, String>("A", "Ancona"),
  MapEntry<String, String>("B", "Bologna"),
  MapEntry<String, String>("C", "Como"),
  MapEntry<String, String>("D", "Domodossola"),
  MapEntry<String, String>("E", "Empoli"),
  MapEntry<String, String>("F", "Firenze"),
  MapEntry<String, String>("G", "Genova"),
  MapEntry<String, String>("H", "Hotel"),
  MapEntry<String, String>("I", "Imola"),
  MapEntry<String, String>("J", "Jolly, Juventus"),
  MapEntry<String, String>("K", "Kappa, Kiwi"),
  MapEntry<String, String>("L", "Livorno"),
  MapEntry<String, String>("M", "Milano"),
  MapEntry<String, String>("N", "Napoli"),
  MapEntry<String, String>("O", "Otranto"),
  MapEntry<String, String>("P", "Padova"),
  MapEntry<String, String>("Q", "Quadro"),
  MapEntry<String, String>("R", "Roma"),
  MapEntry<String, String>("S", "Savona"),
  MapEntry<String, String>("T", "Torino"),
  MapEntry<String, String>("U", "Udine"),
  MapEntry<String, String>("V", "Verona, Venezia"),
  MapEntry<String, String>("W", "Whiskey, Washington"),
  MapEntry<String, String>("X", "Ics, Xilofono"),
  MapEntry<String, String>("Y", "York, yogurt"),
  MapEntry<String, String>("Z", "Zara, Zorro"), 
];
const List<MapEntry<String, String>> _spellingESP = [
  MapEntry<String, String>("A", "Antonio"),
  MapEntry<String, String>("B", "Burgos"),
  MapEntry<String, String>("C", "Carmen"),
  MapEntry<String, String>("CH", "Chocolate"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "España"),
  MapEntry<String, String>("F", "Francia"),
  MapEntry<String, String>("G", "Granada"),
  MapEntry<String, String>("H", "Historia"),
  MapEntry<String, String>("I", "Inés"),
  MapEntry<String, String>("J", "José"),
  MapEntry<String, String>("K", "Kilo"),
  MapEntry<String, String>("L", "Lorenzo"),
  MapEntry<String, String>("M", "Madrid"),
  MapEntry<String, String>("N", "Navidad"),
  MapEntry<String, String>("O", "Oviedo"),
  MapEntry<String, String>("P", "París"),
  MapEntry<String, String>("Q", "Queso"),
  MapEntry<String, String>("R", "Ramón"),
  MapEntry<String, String>("S", "Sábado"),
  MapEntry<String, String>("T", "Toledo"),
  MapEntry<String, String>("U", "Ulises"),
  MapEntry<String, String>("V", "Valencia"),
  MapEntry<String, String>("W", "Washington"),
  MapEntry<String, String>("X", "Xilófono"),
  MapEntry<String, String>("Y", "Yolanda"),
  MapEntry<String, String>("Z", "Zaragoza"),
];
const List<MapEntry<String, String>> _spellingPOR = [
  MapEntry<String, String>("A", "Aveiro"),
  MapEntry<String, String>("B", "Braga"),
  MapEntry<String, String>("C", "Coimbra"),
  MapEntry<String, String>("D", "Dafundo"),
  MapEntry<String, String>("E", "Évora"),
  MapEntry<String, String>("F", "Faro"),
  MapEntry<String, String>("G", "Guarda"),
  MapEntry<String, String>("H", "Horta"),
  MapEntry<String, String>("I", "Itália"),
  MapEntry<String, String>("J", "José"),
  MapEntry<String, String>("K", "Kodak"),
  MapEntry<String, String>("L", "Lisboa"),
  MapEntry<String, String>("M", "Maria"),
  MapEntry<String, String>("N", "Nazaré"),
  MapEntry<String, String>("O", "Ovar"),
  MapEntry<String, String>("P", "Porto"),
  MapEntry<String, String>("Q", "Queluz"),
  MapEntry<String, String>("R", "Rossio"),
  MapEntry<String, String>("S", "Setúbal"),
  MapEntry<String, String>("T", "Tavira"),
  MapEntry<String, String>("U", "Unidade"),
  MapEntry<String, String>("V", "Vidago"),
  MapEntry<String, String>("W", "Waldemar"),
  MapEntry<String, String>("X", "Xavier"),
  MapEntry<String, String>("Y", "York"),
  MapEntry<String, String>("Z", "Zulmira"),
];
const List<MapEntry<String, String>> _spellingBRA = [
  MapEntry<String, String>("A", "Amor"),
  MapEntry<String, String>("B", "Bandeira"),
  MapEntry<String, String>("C", "Cobra"),
  MapEntry<String, String>("D", "Dado"),
  MapEntry<String, String>("E", "Estrela"),
  MapEntry<String, String>("F", "Feira"),
  MapEntry<String, String>("G", "Goiaba"),
  MapEntry<String, String>("H", "Hotel"),
  MapEntry<String, String>("I", "Índio"),
  MapEntry<String, String>("J", "José"),
  MapEntry<String, String>("K", "Kiwi"),
  MapEntry<String, String>("L", "Lua"),
  MapEntry<String, String>("M", "Maria"),
  MapEntry<String, String>("N", "Navio"),
  MapEntry<String, String>("O", "Ouro"),
  MapEntry<String, String>("P", "Pipa"),
  MapEntry<String, String>("Q", "Quilombo"),
  MapEntry<String, String>("R", "Raiz"),
  MapEntry<String, String>("S", "Saci"),
  MapEntry<String, String>("T", "Tatu"),
  MapEntry<String, String>("U", "Uva"),
  MapEntry<String, String>("V", "Vitória"),
  MapEntry<String, String>("W", "Wilson"),
  MapEntry<String, String>("X", "Xadrez"),
  MapEntry<String, String>("Y", "Yolanda"),
  MapEntry<String, String>("Z", "Zebra"),
];
const List<MapEntry<String, String>> _spellingDNK = [
  MapEntry<String, String>("A", "Anna"),
  MapEntry<String, String>("Æ", "Ægir"),
  MapEntry<String, String>("B", "Bernhard"),
  MapEntry<String, String>("C", "Cecilie"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Erik"),
  MapEntry<String, String>("F", "Frederik"),
  MapEntry<String, String>("G", "Georg"),
  MapEntry<String, String>("H", "Hans"),
  MapEntry<String, String>("I", "Ida"),
  MapEntry<String, String>("J", "Johan"),
  MapEntry<String, String>("K", "Karen"),
  MapEntry<String, String>("L", "Ludvig"),
  MapEntry<String, String>("M", "Mari"),
  MapEntry<String, String>("N", "Nikolaj"),
  MapEntry<String, String>("O", "Odin"),
  MapEntry<String, String>("Ø", "Øresund"),
  MapEntry<String, String>("P", "Peter"),
  MapEntry<String, String>("Q", "Quintus"),
  MapEntry<String, String>("R", "Rasmus"),
  MapEntry<String, String>("S", "Søren"),
  MapEntry<String, String>("T", "Theodor"),
  MapEntry<String, String>("U", "Ulla"),
  MapEntry<String, String>("V", "Viggo"),
  MapEntry<String, String>("W", "William"),
  MapEntry<String, String>("X", "Xerxes"),
  MapEntry<String, String>("Y", "Yrsa"),
  MapEntry<String, String>("Z", "Zackarias"),
];
const List<MapEntry<String, String>> _spellingNOR = [
  MapEntry<String, String>("A", "Anna"),
  MapEntry<String, String>("Æ", "Ærlig"),
  MapEntry<String, String>("B", "Bernhard"),
  MapEntry<String, String>("C", "Caesar"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Edith"),
  MapEntry<String, String>("F", "Fredrik"),
  MapEntry<String, String>("G", "Gustav"),
  MapEntry<String, String>("H", "Harald"),
  MapEntry<String, String>("I", "Ivar"),
  MapEntry<String, String>("J", "Johan"),
  MapEntry<String, String>("K", "Karin"),
  MapEntry<String, String>("L", "Ludvig"),
  MapEntry<String, String>("M", "Martin"),
  MapEntry<String, String>("N", "Nils"),
  MapEntry<String, String>("O", "Olivia"),
  MapEntry<String, String>("Ø", "Østen"),
  MapEntry<String, String>("P", "Petter"),
  MapEntry<String, String>("Q", "Quintus"),
  MapEntry<String, String>("R", "Rikard"),
  MapEntry<String, String>("S", "Sigrid"),
  MapEntry<String, String>("T", "Teodor"),
  MapEntry<String, String>("U", "Ulrik"),
  MapEntry<String, String>("V", "Enkelt-V"),
  MapEntry<String, String>("W", "Dobbelt-W"),
  MapEntry<String, String>("X", "Xerxes"),
  MapEntry<String, String>("Y", "Yngling"),
  MapEntry<String, String>("Z", "Zakarias"),
];
const List<MapEntry<String, String>> _spellingSWE = [
  MapEntry<String, String>("A", "Adam"),
  MapEntry<String, String>("B", "Bertil"),
  MapEntry<String, String>("C", "Caesar"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Erik"),
  MapEntry<String, String>("F", "Filip"),
  MapEntry<String, String>("G", "Gustav"),
  MapEntry<String, String>("H", "Helge"),
  MapEntry<String, String>("I", "Ivar"),
  MapEntry<String, String>("J", "Johan"),
  MapEntry<String, String>("K", "Kalle"),
  MapEntry<String, String>("L", "Ludvig"),
  MapEntry<String, String>("M", "Martin"),
  MapEntry<String, String>("N", "Niklas"),
  MapEntry<String, String>("O", "Olof"),
  MapEntry<String, String>("Ö", "Östen"),
  MapEntry<String, String>("P", "Petter"),
  MapEntry<String, String>("Q", "Quintus"),
  MapEntry<String, String>("R", "Rudolf"),
  MapEntry<String, String>("S", "Sigurd"),
  MapEntry<String, String>("T", "Tore"),
  MapEntry<String, String>("U", "Urban"),
  MapEntry<String, String>("V", "Viktor"),
  MapEntry<String, String>("W", "Wilhelm"),
  MapEntry<String, String>("X", "Xerxes"),
  MapEntry<String, String>("Y", "Yngve"),
  MapEntry<String, String>("Z", "Zäta"),
];
const List<MapEntry<String, String>> _spellingFIN = [
  MapEntry<String, String>("A", "Aarne"),
  MapEntry<String, String>("B", "Bertta"),
  MapEntry<String, String>("C", "Celsius"),
  MapEntry<String, String>("D", "Daavid"),
  MapEntry<String, String>("E", "Eemeli"),
  MapEntry<String, String>("F", "Faarao"),
  MapEntry<String, String>("G", "Gideon"),
  MapEntry<String, String>("H", "Heikki"),
  MapEntry<String, String>("I", "Iivari"),
  MapEntry<String, String>("J", "Jussi"),
  MapEntry<String, String>("K", "Kalle"),
  MapEntry<String, String>("L", "Lauri"),
  MapEntry<String, String>("M", "Matti"),
  MapEntry<String, String>("N", "Niilo"),
  MapEntry<String, String>("O", "Otto"),
  MapEntry<String, String>("Ö", "Öljy"),
  MapEntry<String, String>("P", "Paavo"),
  MapEntry<String, String>("Q", "Kuu"),
  MapEntry<String, String>("R", "Risto"),
  MapEntry<String, String>("S", "Sakari"),
  MapEntry<String, String>("T", "Tyyne"),
  MapEntry<String, String>("U", "Urho"),
  MapEntry<String, String>("V", "Vihtori"),
  MapEntry<String, String>("W", "Wiski"),
  MapEntry<String, String>("X", "Äksä"),
  MapEntry<String, String>("Y", "Yrjö"),
  MapEntry<String, String>("Z", "Tseta"),
];
const List<MapEntry<String, String>> _spellingTUR = [
  MapEntry<String, String>("A", "Adana"),
  MapEntry<String, String>("B", "Bolu"),
  MapEntry<String, String>("C", "Ceyhan"),
  MapEntry<String, String>("Ç", "Çanakkale"),
  MapEntry<String, String>("D", "Denizli"),
  MapEntry<String, String>("E", "Edirne"),
  MapEntry<String, String>("F", "Fatsa"),
  MapEntry<String, String>("G", "Giresun"),
  MapEntry<String, String>("Ğ", "Yumuşak G"),
  MapEntry<String, String>("H", "Hatay"),
  MapEntry<String, String>("I", "Isparta"),
  MapEntry<String, String>("İ", "İzmir"),
  MapEntry<String, String>("J", "Jandarma"),
  MapEntry<String, String>("K", "Kars"),
  MapEntry<String, String>("L", "Lüleburgaz"),
  MapEntry<String, String>("M", "Muş"),
  MapEntry<String, String>("N", "Niğde"),
  MapEntry<String, String>("O", "Ordu"),
  MapEntry<String, String>("Ö", "Ödemiş"),
  MapEntry<String, String>("P", "Polatlı"),
  MapEntry<String, String>("R", "Rize"),
  MapEntry<String, String>("S", "Sinop"),
  MapEntry<String, String>("Ş", "Şırnak"),
  MapEntry<String, String>("T", "Tokat"),
  MapEntry<String, String>("U", "Uşak"),
  MapEntry<String, String>("Ü", "Ünye"),
  MapEntry<String, String>("V", "Van"),
  MapEntry<String, String>("Y", "Yozgat"),
  MapEntry<String, String>("Z", "Zonguldak"),
];
const List<MapEntry<String, String>> _spellingCZE = [
  MapEntry<String, String>("A", "Adam"),
  MapEntry<String, String>("B", "Božena"),
  MapEntry<String, String>("C", "Cyril"),
  MapEntry<String, String>("CH", "Chrudim"),
  MapEntry<String, String>("D", "David"),
  MapEntry<String, String>("E", "Emil"),
  MapEntry<String, String>("F", "František"),
  MapEntry<String, String>("G", "Gustav"),
  MapEntry<String, String>("H", "Helena"),
  MapEntry<String, String>("I", "Ivan"),
  MapEntry<String, String>("J", "Josef"),
  MapEntry<String, String>("K", "Karel"),
  MapEntry<String, String>("L", "Ludvik"),
  MapEntry<String, String>("M", "Marie"),
  MapEntry<String, String>("N", "Norbert"),
  MapEntry<String, String>("O", "Otakar"),
  MapEntry<String, String>("P", "Petr"),
  MapEntry<String, String>("Q", "Quido"),
  MapEntry<String, String>("R", "Rudolf"),
  MapEntry<String, String>("S", "Svatopluk"),
  MapEntry<String, String>("T", "Tomáš"),
  MapEntry<String, String>("U", "Urban"),
  MapEntry<String, String>("V", "Václav"),
  MapEntry<String, String>("W", "dvojité V"),
  MapEntry<String, String>("X", "Xaver"),
  MapEntry<String, String>("Y", "Ypsilon"),
  MapEntry<String, String>("Z", "Zuzana"),
];
const List<MapEntry<String, String>> _spellingSLO = [
  MapEntry<String, String>("A", "Ankaran"),
  MapEntry<String, String>("B", "Bled"),
  MapEntry<String, String>("C", "Celje"),
  MapEntry<String, String>("Č", "Čatež"),
  MapEntry<String, String>("D", "Drava"),
  MapEntry<String, String>("E", "Evropa"),
  MapEntry<String, String>("F", "Fala"),
  MapEntry<String, String>("G", "Gorica"),
  MapEntry<String, String>("H", "Hrastnik"),
  MapEntry<String, String>("I", "Izola"),
  MapEntry<String, String>("J", "Jadran"),
  MapEntry<String, String>("K", "Kamnik"),
  MapEntry<String, String>("L", "Ljubljana"),
  MapEntry<String, String>("M", "Maribor"),
  MapEntry<String, String>("N", "Nanos"),
  MapEntry<String, String>("O", "Ormož"),
  MapEntry<String, String>("P", "Piran"),
  MapEntry<String, String>("Q", "Queen"),
  MapEntry<String, String>("R", "Ravne"),
  MapEntry<String, String>("S", "Soča"),
  MapEntry<String, String>("T", "Triglav"),
  MapEntry<String, String>("U", "Unec"),
  MapEntry<String, String>("V", "Velenje"),
  MapEntry<String, String>("W", "Dvojni v"),
  MapEntry<String, String>("X", "Iks"),
  MapEntry<String, String>("Y", "Ipsilon"),
  MapEntry<String, String>("Z", "Zalog"),
];
const List<MapEntry<String, String>> _spellingSRB = [
  MapEntry<String, String>("A", "Avala"),
  MapEntry<String, String>("B", "Beograd"),
  MapEntry<String, String>("C", "Cetinje"),
  MapEntry<String, String>("Č", "Čačak"),
  MapEntry<String, String>("Ć", "Ćuprija"),
  MapEntry<String, String>("D", "Drina"),
  MapEntry<String, String>("DŽ", "Džep	"),
  MapEntry<String, String>("Đ", "Đeravica"),
  MapEntry<String, String>("E", "Evropa"),
  MapEntry<String, String>("F", "Futog"),
  MapEntry<String, String>("G", "Golija"),
  MapEntry<String, String>("H", "Heroj"),
  MapEntry<String, String>("I", "Igalo"),
  MapEntry<String, String>("J", "Jadran"),
  MapEntry<String, String>("K", "Kosovo"),
  MapEntry<String, String>("L", "Lovćen"),
  MapEntry<String, String>("LJ", "Ljubovija"),
  MapEntry<String, String>("M", "Morava"),
  MapEntry<String, String>("N", "Niš"),
  MapEntry<String, String>("NJ", "Njegoš"),
  MapEntry<String, String>("O", "Obilić"),
  MapEntry<String, String>("P", "Pirot"),
  MapEntry<String, String>("Q", "Ku"),
  MapEntry<String, String>("R", "Ruma"),
  MapEntry<String, String>("S", "Sava"),
  MapEntry<String, String>("T", "Timok"),
  MapEntry<String, String>("U", "Užice"),
  MapEntry<String, String>("V", "Valjevo"),
  MapEntry<String, String>("W", "Duplo ve"),
  MapEntry<String, String>("X", "Iks"),
  MapEntry<String, String>("Y", "Ipsilon"),
  MapEntry<String, String>("Z", "Zemun"),
];
const List<MapEntry<String, String>> _spellingYUG = [
  MapEntry<String, String>("A", "Avala"),
  MapEntry<String, String>("B", "Beograd"),
  MapEntry<String, String>("C", "Cetinje"),
  MapEntry<String, String>("Č", "Čačak"),
  MapEntry<String, String>("Ć", "Ćuprija"),
  MapEntry<String, String>("D", "Dubrovnik"),
  MapEntry<String, String>("DŽ", "Džamija"),
  MapEntry<String, String>("Đ", "Đakovo"),
  MapEntry<String, String>("E", "Evropa"),
  MapEntry<String, String>("F", "Foča"),
  MapEntry<String, String>("G", "Gorica"),
  MapEntry<String, String>("H", "Hercegovina"),
  MapEntry<String, String>("I", "Istra"),
  MapEntry<String, String>("J", "Jadran"),
  MapEntry<String, String>("K", "Kosovo"),
  MapEntry<String, String>("L", "Lika"),
  MapEntry<String, String>("LJ", "Ljubljana"),
  MapEntry<String, String>("M", "Mostar"),
  MapEntry<String, String>("N", "Niš"),
  MapEntry<String, String>("NJ", "Njegoš"),
  MapEntry<String, String>("O", "Osijek"),
  MapEntry<String, String>("P", "Pirot"),
  MapEntry<String, String>("Q", "kvadrat"),
  MapEntry<String, String>("R", "Rijeka"),
  MapEntry<String, String>("S", "Skopje"),
  MapEntry<String, String>("T", "Tuzla"),
  MapEntry<String, String>("U", "Užice"),
  MapEntry<String, String>("V", "Valjevo"),
  MapEntry<String, String>("W", "duplo ve"),
  MapEntry<String, String>("X", "Iks"),
  MapEntry<String, String>("Y", "ipsilon"),
  MapEntry<String, String>("Z", "Zagreb"),
];
const List<MapEntry<String, String>> _spellingROU = [
  MapEntry<String, String>("A", "Ana"),
  MapEntry<String, String>("B", "Barbu"),
  MapEntry<String, String>("C", "Constantin"),
  MapEntry<String, String>("D", "Dumitru"),
  MapEntry<String, String>("E", "Elena"),
  MapEntry<String, String>("F", "Florea"),
  MapEntry<String, String>("G", "Gheorghe"),
  MapEntry<String, String>("H", "Haralambie"),
  MapEntry<String, String>("I", "Ion"),
  MapEntry<String, String>("J", "Jean"),
  MapEntry<String, String>("K", "Kilogram"),
  MapEntry<String, String>("L", "Lazăr"),
  MapEntry<String, String>("M", "Maria"),
  MapEntry<String, String>("N", "Nicolae"),
  MapEntry<String, String>("O", "Olga"),
  MapEntry<String, String>("P", "Petre"),
  MapEntry<String, String>("Q", "Qu (Chiu)"),
  MapEntry<String, String>("R", "Radu"),
  MapEntry<String, String>("S", "Sandu"),
  MapEntry<String, String>("T", "Tudor"),
  MapEntry<String, String>("U", "Udrea"),
  MapEntry<String, String>("V", "Vasile"),
  MapEntry<String, String>("W", "dublu v"),
  MapEntry<String, String>("X", "Xenia"),
  MapEntry<String, String>("Y", "I grec"),
  MapEntry<String, String>("Z", "Zahăr"),
];
const List<MapEntry<String, String>> _spellingPOL = [
  MapEntry<String, String>("A", "Adam"),
  MapEntry<String, String>("B", "Barbara"),
  MapEntry<String, String>("C", "Celina"),
  MapEntry<String, String>("Ć", "Ćma"),
  MapEntry<String, String>("D", "Dorota"),
  MapEntry<String, String>("E", "Edward"),
  MapEntry<String, String>("F", "Filip"),
  MapEntry<String, String>("G", "Gustaw"),
  MapEntry<String, String>("H", "Henryk"),
  MapEntry<String, String>("I", "Ignacy"),
  MapEntry<String, String>("J", "Józef"),
  MapEntry<String, String>("K", "Karol"),
  MapEntry<String, String>("L", "Ludwik"),
  MapEntry<String, String>("Ł", "Łucja"),
  MapEntry<String, String>("M", "Marian"),
  MapEntry<String, String>("N", "Nikodem"),
  MapEntry<String, String>("O", "Olga"),
  MapEntry<String, String>("P", "Paweł"),
  MapEntry<String, String>("Q", "Quantum"),
  MapEntry<String, String>("R", "Roman"),
  MapEntry<String, String>("S", "Stefan"),
  MapEntry<String, String>("Ś", "Światowid"),
  MapEntry<String, String>("T", "Tadeusz"),
  MapEntry<String, String>("U", "Urzula"),
  MapEntry<String, String>("V", "Wioletta"),
  MapEntry<String, String>("W", "Walenty"),
  MapEntry<String, String>("X", "Ksawery"),
  MapEntry<String, String>("Y", "Ypsylon"),
  MapEntry<String, String>("Z", "Zygmunt"),
  MapEntry<String, String>("Ż", "Żaba"),
  MapEntry<String, String>("Ź", "Źrebak"),
];
const List<MapEntry<String, String>> _spellingRUS = [
  MapEntry<String, String>("А", "Анна, Антон"),
  MapEntry<String, String>("Б", "Борис"),
  MapEntry<String, String>("В", "Василий"),
  MapEntry<String, String>("Г", "Григорий, Галина"),
  MapEntry<String, String>("Д", "Дмитрий"),
  MapEntry<String, String>("Е", "Елена"),
  MapEntry<String, String>("Ё", "Ёлка"),
  MapEntry<String, String>("Ж", "Женя, жук"),
  MapEntry<String, String>("З", "Зинаида, Зоя"),
  MapEntry<String, String>("И", "Иван"),
  MapEntry<String, String>("Й", "Иван краткий, йот"),
  MapEntry<String, String>("К", "Константин, киловатт"),
  MapEntry<String, String>("Л", "Леонид"),
  MapEntry<String, String>("М", "Михаил, Мария"),
  MapEntry<String, String>("Н", "Николай"),
  MapEntry<String, String>("О", "Ольга"),
  MapEntry<String, String>("П", "Павел"),
  MapEntry<String, String>("Р", "Роман, радио"),
  MapEntry<String, String>("С", "Семён, Сергей"),
  MapEntry<String, String>("Т", "Татьяна, Тамара"),
  MapEntry<String, String>("У", "Ульяна"),
  MapEntry<String, String>("Ф", "Фёдор"),
  MapEntry<String, String>("Х", "Харитон"),
  MapEntry<String, String>("Ц", "цапля, центр"),
  MapEntry<String, String>("Ч", "человек"),
  MapEntry<String, String>("Ш", "Шура, щука"),
  MapEntry<String, String>("Ъ", "твёрдый знак"),
  MapEntry<String, String>("Ы", "еры, игрек"),
  MapEntry<String, String>("Ь", "мягкий знак, знак"),
  MapEntry<String, String>("Э", "эхо, Эмма"),
  MapEntry<String, String>("Ю", "Юрий"),
  MapEntry<String, String>("Я", "Яков"),
];
const List<MapEntry<String, String>> _spellingRUSLAT = [
  MapEntry<String, String>("А", "Anna, Anton"),
  MapEntry<String, String>("Б", "Boris"),
  MapEntry<String, String>("В", "Vasily"),
  MapEntry<String, String>("Г", "Gregory, Galina"),
  MapEntry<String, String>("Д", "Dmitri"),
  MapEntry<String, String>("Е", "Yelena"),
  MapEntry<String, String>("Ё", "Yolka"),
  MapEntry<String, String>("Ж", "Zhenya, zhuk"),
  MapEntry<String, String>("З", "Zinaida, Zoya"),
  MapEntry<String, String>("И", "Ivan"),
  MapEntry<String, String>("Й", "Ivan kratkiy, yot"),
  MapEntry<String, String>("К", "Konstantin, kilovatt"),
  MapEntry<String, String>("Л", "Leonid"),
  MapEntry<String, String>("М", "Mikhail, Mariya"),
  MapEntry<String, String>("Н", "Nikolai"),
  MapEntry<String, String>("О", "Olga"),
  MapEntry<String, String>("П", "Pavel"),
  MapEntry<String, String>("Р", "Roman, radio"),
  MapEntry<String, String>("С", "Semyon, Sergei"),
  MapEntry<String, String>("Т", "Tatyana, Tamara"),
  MapEntry<String, String>("У", "Ulyana"),
  MapEntry<String, String>("Ф", "Fyodor"),
  MapEntry<String, String>("Х", "Khariton"),
  MapEntry<String, String>("Ц", "tsaplya, tsentr"),
  MapEntry<String, String>("Ч", "chelovek"),
  MapEntry<String, String>("Ш", "Shura, shchuka"),
  MapEntry<String, String>("Ъ", "tvyordiy znak"),
  MapEntry<String, String>("Ы", "yery, i grik"),
  MapEntry<String, String>("Ь", "myagkiy znak, znak"),
  MapEntry<String, String>("Э", "ekho, Emma"),
  MapEntry<String, String>("Ю", "Yuri"),
  MapEntry<String, String>("Я", "Yakov"),
];
const List<MapEntry<String, String>> _spellingGRC = [
  MapEntry<String, String>("Α,α", "αστήρ"),
  MapEntry<String, String>("Β,β", "Βύρων"),
  MapEntry<String, String>("Γ,γ", "γαλή"),
  MapEntry<String, String>("Δ,δ", "δόξα"),
  MapEntry<String, String>("Ε,ε", "Ερμής"),
  MapEntry<String, String>("Ζ,ζ", "Ζευς"),
  MapEntry<String, String>("Η,η", "Ηρώ"),
  MapEntry<String, String>("Θ,θ", "θεά"),
  MapEntry<String, String>("Ι,ι", "ίσκιος"),
  MapEntry<String, String>("Κ,κ", "κενόν"),
  MapEntry<String, String>("Λ,λ", "λάμα"),
  MapEntry<String, String>("Μ,μ", "μέλι"),
  MapEntry<String, String>("Ν,ν", "ναός"),
  MapEntry<String, String>("Ξ,ξ", "Ξέρξης"),
  MapEntry<String, String>("Ο,ο", "οσμή"),
  MapEntry<String, String>("Π,π", "Πέτρος"),
  MapEntry<String, String>("Ρ,ρ", "ρήγας"),
  MapEntry<String, String>("Σ,σ,-ς", "σοφός"),
  MapEntry<String, String>("Τ,τ", "τίγρης"),
  MapEntry<String, String>("Υ,υ", "ύμνος"),
  MapEntry<String, String>("Φ,φ", "Φωφώ"),
  MapEntry<String, String>("Χ,χ", "χαρά"),
  MapEntry<String, String>("Ψ,ψ", "ψυχή"),
  MapEntry<String, String>("Ω,ω", "ωμέγα"),
];
const List<MapEntry<String, String>> _spellingGRCLAT = [
  MapEntry<String, String>("Α,α", "astír"),
  MapEntry<String, String>("Β,β", "Víron"),
  MapEntry<String, String>("Γ,γ", "galí"),
  MapEntry<String, String>("Δ,δ", "dóxa"),
  MapEntry<String, String>("Ε,ε", "Ermís"),
  MapEntry<String, String>("Ζ,ζ", "Zefs"),
  MapEntry<String, String>("Η,η", "Iró"),
  MapEntry<String, String>("Θ,θ", "theá"),
  MapEntry<String, String>("Ι,ι", "ískios"),
  MapEntry<String, String>("Κ,κ", "kenón"),
  MapEntry<String, String>("Λ,λ", "láma"),
  MapEntry<String, String>("Μ,μ", "méli"),
  MapEntry<String, String>("Ν,ν", "naós"),
  MapEntry<String, String>("Ξ,ξ", "Xérxis"),
  MapEntry<String, String>("Ο,ο", "osmí"),
  MapEntry<String, String>("Π,π", "Pétros"),
  MapEntry<String, String>("Ρ,ρ", "rígas"),
  MapEntry<String, String>("Σ,σ,-ς", "sofós"),
  MapEntry<String, String>("Τ,τ", "tígris"),
  MapEntry<String, String>("Υ,υ", "ímnos"),
  MapEntry<String, String>("Φ,φ", "Fofó"),
  MapEntry<String, String>("Χ,χ", "chará"),
  MapEntry<String, String>("Ψ,ψ", "psichí"),
  MapEntry<String, String>("Ω,ω", "oméga"),
];

const Map<SPELLING, List<MapEntry<String, String>>> SPELLING_ALPHABETS = {
  SPELLING.ICAO1947: _spellingICAO1947,
  SPELLING.NATO: _spellingNATO,
  SPELLING.USNAVY1908_1: _spellingUSNAVY1908_1,
  SPELLING.USNAVY1908_2: _spellingUSNAVY1908_2,
  SPELLING.USNAVY1920: _spellingUSNAVY1920,
  SPELLING.USNAVY1942: _spellingUSNAVY1942,
  SPELLING.APCO1967: _spellingAPCO1967,
  SPELLING.APCO1974: _spellingNATO,
  SPELLING.ARRL1930: _spellingARRL1930,
  SPELLING.ARRL1936: _spellingARRL1936,
  SPELLING.ARRL1946: _spellingARRL1946,
  SPELLING.ARRL1970: _spellingNATO,
  SPELLING.ARRLDX: _spellingARRLDX,
  SPELLING.EPO: _spellingEPO,
  SPELLING.FRA: _spellingFRA,
  SPELLING.FRABEL: _spellingFRABEL,
  SPELLING.CHE: _spellingCHE,
  SPELLING.FRACAN: _spellingFRACAN,
  SPELLING.DEU1950: _spellingDEU1950,
  SPELLING.DEUDDR: _spellingDEU1950,
  SPELLING.DEU2022: _spellingDEU2022,
  SPELLING.AUT: _spellingAUT,
  SPELLING.NLD: _spellingNLD,
  SPELLING.BEL: _spellingBEL,
  SPELLING.ITA: _spellingITA,
  SPELLING.ESP: _spellingESP,
  SPELLING.BRA: _spellingBRA,
  SPELLING.POR: _spellingPOR,
  SPELLING.SWE: _spellingSWE,
  SPELLING.DNK: _spellingDNK,
  SPELLING.NOR: _spellingNOR,
  SPELLING.FIN: _spellingFIN,
  SPELLING.TUR: _spellingTUR,
  SPELLING.ROU: _spellingROU,
  SPELLING.CZE: _spellingCZE,
  SPELLING.YUG: _spellingYUG,
  SPELLING.SRB: _spellingSRB,
  SPELLING.SLO: _spellingSLO,
  SPELLING.POL: _spellingPOL,
  SPELLING.RUS: _spellingRUS,
  SPELLING.RUSLAT: _spellingRUSLAT,
  SPELLING.GRC: _spellingGRC,
  SPELLING.GRCLAT: _spellingGRCLAT,
};

final Map<Locale, SPELLING> SUPPORTED_SPELLING_LOCALES = {
  const Locale('cz'): SPELLING.CZE,
  const Locale('da'): SPELLING.DNK,
  const Locale('de'): SPELLING.DEU2022,
  const Locale('el'): SPELLING.GRC,
  const Locale('en'): SPELLING.NATO,
  const Locale('es'): SPELLING.ESP,
  const Locale('fi'): SPELLING.FIN,
  const Locale('fr'): SPELLING.FRA,
  const Locale('it'): SPELLING.ITA,
  const Locale('nl'): SPELLING.NLD,
  const Locale('pl'): SPELLING.POL,
  const Locale('pt'): SPELLING.POR,
  const Locale('ru'): SPELLING.RUS,
  const Locale('sv'): SPELLING.SWE,
  const Locale('tr'): SPELLING.TUR,
};
