part of 'package:gc_wizard/tools/uncategorized/wedding_anniversaries/logic/wedding_anniversaries.dart';


const Map<String, List<String>> _anniversariesDE =
{
  "0": ["wedding_element_green", "wedding_element_white"],
  "0.75": ["wedding_element_beer"],
  "1": ["wedding_element_paper", "wedding_element_cotton"],
  "2": ["wedding_element_cotton", "wedding_element_paper", "wedding_element_leather"],
  "3": ["wedding_element_leather", "wedding_element_fruit", "wedding_element_firs", "wedding_element_wheat"],
  "4": ["wedding_element_silk", "wedding_element_amber", "wedding_element_linen", "wedding_element_wine", "wedding_element_wax"],
  "5": ["wedding_element_wood", "wedding_element_gum", "wedding_element_creampuff", "wedding_element_diligence", "wedding_element_ox", "wedding_element_bull"],
  "6": ["wedding_element_sugar", "wedding_element_ox", "wedding_element_tin", "wedding_element_iron", "common_country_Cyprus"],
  "6.25": ["wedding_element_mutton", "wedding_element_tin"],
  "6.5": ["wedding_element_tin"],
  "7": ["wedding_element_copper", "wedding_element_brass", "wedding_element_wool", "wedding_element_friendship"],
  "8": ["wedding_element_sheetmetal", "wedding_element_poppy", "wedding_element_stoneware", "wedding_element_salt", "wedding_element_nickel", "wedding_element_bronze"],
  "9": [ "wedding_element_ceramics", "wedding_element_porcelain", "wedding_element_glass", "wedding_element_crystal", "wedding_element_ox", "wedding_element_water", "wedding_element_willows"],
  "10": ["wedding_element_bronze", "wedding_element_rose", "wedding_element_wood", "wedding_element_glass", "wedding_element_sheetmetal", "wedding_element_tin", "wedding_element_ox"],
  "11": ["wedding_element_steel", "wedding_element_corals", "wedding_element_shrovetide"],
  "12": ["wedding_element_silk", "wedding_element_soil", "wedding_element_linen", "wedding_element_tin", "wedding_element_nickel", "wedding_element_violet"],
  "12.5": ["wedding_element_sheetmetal", "wedding_element_copper", "wedding_element_nickel", "wedding_element_medium", "wedding_element_tin", "wedding_element_bronze", "wedding_element_violet", "wedding_element_parsley"],
  "13": ["wedding_element_violet", "wedding_element_liliesofthevalley", "wedding_element_salt", "wedding_element_lace"],
  "14": ["wedding_element_ivory", "wedding_element_agate", "wedding_element_lead", "wedding_element_blue"],
  "15": ["wedding_element_glass", "wedding_element_crystal", "Plünnen", "wedding_element_rags", "wedding_element_bottles", "wedding_element_violet"],
  "16": ["wedding_element_sapphire"],
  "17": ["wedding_element_orchid","wedding_element_rose", "wedding_element_soup"],
  "18": ["wedding_element_turquoise"],
  "19": ["wedding_element_motherofpearl", "wedding_element_cretonne"],
  "20": ["wedding_element_porcelain", "wedding_element_copper", "wedding_element_chrysanthemum", "wedding_element_thorns"],
  "21": ["wedding_element_beeches", "wedding_element_opal"],
  "22": ["wedding_element_bronze", "wedding_element_tourmaline"],
  "23": ["wedding_element_beryl", "wedding_element_titanium"],
  "24": ["wedding_element_satin", "wedding_element_silk"],
  "25": ["wedding_element_silver"],
  "26": ["wedding_element_jade", "wedding_element_oak"],
  "27": ["wedding_element_jute", "wedding_element_mahogany"],
  "28": ["wedding_element_nickel", "wedding_element_carnation"],
  "29": ["wedding_element_ebony", "wedding_element_velvet"],
  "30": ["wedding_element_pearl", "wedding_element_gingerbread", "wedding_element_lansquenet"],
  "31": ["wedding_element_limetree"],
  "32": ["wedding_element_copper", "wedding_element_soap", "wedding_element_lapislazuli"],
  "33": ["wedding_element_porphyry", "wedding_element_tin"],
  "33.3": ["wedding_element_garlic"],
  "34": ["wedding_element_tin"],
  "35": ["wedding_element_canvas", "wedding_element_corals", "wedding_element_linen"],
  "36": ["wedding_element_emerald"],
  "37": ["wedding_element_malachit"],
  "37.5": ["wedding_element_aluminium"],
  "38": ["wedding_element_fire", "wedding_element_mercury"],
  "39": ["wedding_element_sun", "wedding_element_krepp"],
  "40": ["wedding_element_ruby", "wedding_element_garnet", "wedding_element_ruby", "wedding_element_emerald"],
  "41": ["wedding_element_birches", "wedding_element_iron"],
  "42": ["wedding_element_garnet", "wedding_element_motherofpearl"],
  "43": ["wedding_element_lead", "wedding_element_flannel"],
  "44": ["wedding_element_stars", "wedding_element_topaz"],
  "45": ["wedding_element_brass", "wedding_element_sapphire", "wedding_element_edelweiss", "wedding_element_platinum", "wedding_element_tourmaline"],
  "46": ["wedding_element_lavender", "wedding_element_marble"],
  "47": ["wedding_element_cashmere", "wedding_element_sapphire"],
  "48": ["wedding_element_amethyst", "wedding_element_diadem"],
  "49": ["wedding_element_cedars", "wedding_element_uranus"],
  "50": ["wedding_element_gold"],
  "51": ["wedding_element_willows"],
  "52": ["wedding_element_topaz"],
  "53": ["wedding_element_uranium"],
  "54": ["wedding_element_zeus"],
  "55": ["wedding_element_platinum", "wedding_element_jewellery", "wedding_element_sapphire", "wedding_element_emerald"],
  "56": ["wedding_element_aster"],
  "57": ["wedding_element_jade"],
  "58": ["wedding_element_angels"],
  "59": ["wedding_element_tides"],
  "60": ["wedding_element_diamonds"],
  "61": ["wedding_element_elms"],
  "62": ["wedding_element_aquamarine"],
  "63": ["wedding_element_mercury"],
  "64": ["wedding_element_heaven"],
  "65": ["wedding_element_iron"],
  "66": ["wedding_element_chives"],
  "67": ["wedding_element_stone"],
  "68": ["wedding_element_granite"],
  "69": ["wedding_element_larches"],
  "70": ["wedding_element_graces", "wedding_element_platinum", "wedding_element_copper"],
  "71": ["wedding_element_ochre"],
  "72": ["wedding_element_graces"],
  "72.5": ["wedding_element_jewellery"],
  "73": ["wedding_element_castiron"],
  "74": ["wedding_element_apple"],
  "75": ["wedding_element_crownjewels", "wedding_element_radium", "wedding_element_stone", "wedding_element_alabaster", "wedding_element_graces", "wedding_element_iron"],
  "76": ["wedding_element_cypresses"],
  "77": ["wedding_element_lavender"],
  "78": ["wedding_element_ebony"],
  "79": ["wedding_element_coffee"],
  "80": ["wedding_element_oak"],
  "81":	["wedding_element_cocoa"],
  "82":	["wedding_element_carnation"],
  "83":	["wedding_element_begonias"],
  "84":	["wedding_element_chrysanthemum"],
  "85":	["wedding_element_angels"],
  "86":	["wedding_element_hydrangea"],
  "87":	["wedding_element_maplewood"],
  "88":	["wedding_element_pears"],
  "89":	["wedding_element_figs"],
  "90":	["wedding_element_marble"],
  "91":	["wedding_element_pines"],
  "92":	["wedding_element_lily"],
  "93":	["wedding_element_lapislazuli"],
  "94":	["wedding_element_palms"],
  "95":	["wedding_element_sandalwood"],
  "96":	["wedding_element_olives"],
  "97":	["wedding_element_firs"],
  "98":	["wedding_element_pines"],
  "99":	["wedding_element_willows"],
  "100": ["wedding_element_heaven"]
};

const Map<String, List<String>> _anniversariesUK =
{
  "1": ["wedding_element_paper"],
  "2": ["wedding_element_cotton"],
  "3": ["wedding_element_leather"],
  "4": ["wedding_element_fruit", "wedding_element_flowers"],
  "5": ["wedding_element_wood"],
  "6": ["wedding_element_iron"],
  "7": ["wedding_element_wool", "wedding_element_copper"],
  "8": ["wedding_element_bronze"],
  "9": ["wedding_element_pottery"],
  "10": ["wedding_element_tin", "wedding_element_aluminium"],
  "11": ["wedding_element_steel"],
  "12": ["wedding_element_silk"],
  "13": ["wedding_element_lace"],
  "14": ["wedding_element_ivory"],
  "15": ["wedding_element_crystal"],
  "20": ["wedding_element_porcelain"],
  "25": ["wedding_element_silver"],
  "30": ["wedding_element_pearl"],
  "35": ["wedding_element_corals"],
  "40": ["wedding_element_ruby"],
  "45": ["wedding_element_sapphire"],
  "50": ["wedding_element_gold"],
  "55": ["wedding_element_emerald"],
  "60": ["wedding_element_diamonds"],
  "70": ["wedding_element_platinum"],
  "75": ["wedding_element_diamonds", "wedding_element_gold"],
  "85": ["wedding_element_moonstone", "wedding_element_wine"]
};

const Map<String, List<String>> _anniversariesUS =
{
  "1": ["wedding_element_cotton", "wedding_element_paper"],
  "2": ["wedding_element_paper", "wedding_element_cotton"],
  "3": ["wedding_element_leather"],
  "4": ["wedding_element_linen", "wedding_element_silk"],
  "5": ["wedding_element_wood"],
  "6": ["wedding_element_sugar"],
  "7": ["wedding_element_wool"],
  "8": ["wedding_element_brass", "wedding_element_salt"],
  "9": ["wedding_element_copper"],
  "10": ["wedding_element_tin"],
  "12": ["wedding_element_silk", "wedding_element_finelinen"],
  "15": ["wedding_element_crystal"],
  "20": ["wedding_element_porcelain"],
  "25": ["wedding_element_silver"],
  "30": ["wedding_element_pearl"],
  "35": ["wedding_element_corals"],
  "40": ["wedding_element_ruby"],
  "45": ["wedding_element_sapphire"],
  "50": ["wedding_element_gold"],
  "55": ["wedding_element_emerald"],
  "60": ["wedding_element_diamonds"],
  "65": ["wedding_element_bluesapphire"],
  "70": ["wedding_element_platinum"],
  "75": ["wedding_element_diamonds", "wedding_element_gold"],
  "80": ["wedding_element_oak"],
  "85": ["wedding_element_wine"],
  "90": ["wedding_element_granite"]
};

const Map<String, List<String>> _anniversariesNL =
{
  "1": ["wedding_element_cotton"],
  "2": ["wedding_element_paper", "wedding_element_leather"],
  "2.5": ["wedding_element_aluminium"],
  "3": ["wedding_element_leather", "wedding_element_wheat"],
  "4": ["wedding_element_silk", "wedding_element_wax"],
  "5": ["wedding_element_wood"],
  "6": ["wedding_element_iron"],
  "7": ["wedding_element_wool"],
  "8": ["wedding_element_bronze"],
  "9": ["wedding_element_pottery"],
  "10": ["wedding_element_tin"],
  "11": ["wedding_element_steel"],
  "12": ["wedding_element_linen", "wedding_element_silk"],
  "12.5": ["wedding_element_copper"],
  "13": ["wedding_element_lace"],
  "14": ["wedding_element_ivory"],
  "15": ["wedding_element_crystal"],
  "16": ["wedding_element_sapphire"],
  "17": ["wedding_element_rose"],
  "18": ["wedding_element_turquoise"],
  "19": ["wedding_element_linen"],
  "20": ["wedding_element_porcelain"],
  "25": ["wedding_element_silver"],
  "30": ["wedding_element_pearl"],
  "35": ["wedding_element_corals", "wedding_element_ruby"],
  "37.5": ["wedding_element_aluminium"],
  "40": ["wedding_element_ruby", "wedding_element_emerald"],
  "45": ["wedding_element_sapphire"],
  "50": ["wedding_element_gold"],
  "55": ["wedding_element_emerald", "wedding_element_orchid"],
  "60": ["wedding_element_diamonds"],
  "65": ["wedding_element_brilliant"],
  "70": ["wedding_element_platinum"],
  "75": ["wedding_element_alabaster"],
  "80": ["wedding_element_oak"],
  "90": ["wedding_element_granite"]
};

const Map<String, List<String>> _anniversariesSW =
{
  "1": ["wedding_element_cotton"],
  "2": ["wedding_element_paper"],
  "3": ["wedding_element_leather"],
  "4": ["wedding_element_flowers", "wedding_element_fruit"],
  "5": ["wedding_element_wood"],
  "6": ["wedding_element_iron"],
  "7": ["wedding_element_copper"],
  "8": ["wedding_element_bronze"],
  "9": ["wedding_element_linen", "wedding_element_willows", "wedding_element_ceramics"],
  "10": ["wedding_element_tin", "wedding_element_aluminium"],
  "11": ["wedding_element_steel"],
  "12": ["wedding_element_silk"],
  "12.5": ["wedding_element_copper"],
  "13": ["wedding_element_lace"],
  "14": ["wedding_element_ivory"],
  "15": ["wedding_element_crystal"],
  "20": ["wedding_element_porcelain"],
  "25": ["wedding_element_silver"],
  "30": ["wedding_element_pearl"],
  "35": ["wedding_element_corals"],
  "40": ["wedding_element_ruby"],
  "45": ["wedding_element_sapphire"],
  "50": ["wedding_element_gold"],
  "55": ["wedding_element_emerald"],
  "60": ["wedding_element_diamonds"],
  "65": ["wedding_element_crownjewels"],
  "70": ["wedding_element_iron"],
  "75": ["wedding_element_iron", "wedding_element_diamonds"],
  "80": ["wedding_element_platinum"],
  "85": ["wedding_element_moonstone"],
  "90": ["wedding_element_stone"]
};

const Map<String, List<String>> _anniversariesDK =
{
  "1": ["wedding_element_paper"],
  "2": ["wedding_element_cotton"],
  "3": ["wedding_element_leather"],
  "4": ["wedding_element_flowers", "wedding_element_hyacinth"],
  "5": ["wedding_element_wood"],
  "6": ["wedding_element_sugar"],
  "7": ["wedding_element_wool"],
  "8": ["wedding_element_bronze"],
  "9": ["wedding_element_willows", "wedding_element_straw"],
  "10": ["wedding_element_tin"],
  "11": ["wedding_element_steel", "wedding_element_amber"],
  "12": ["wedding_element_silk"],
  "12.5": ["wedding_element_copper"],
  "13": ["wedding_element_lace"],
  "14": ["wedding_element_ivory"],
  "15": ["wedding_element_crystal"],
  "16": ["wedding_element_moon"],
  "17": ["wedding_element_amethyst"],
  "18": ["wedding_element_daisy", "wedding_element_satin"],
  "19": ["wedding_element_garnet"],
  "20": ["wedding_element_porcelain"],
  "21": ["wedding_element_turquoise"],
  "22": ["wedding_element_alliance"],
  "23": ["wedding_element_tulip"],
  "24": ["wedding_element_carat"],
  "25": ["wedding_element_silver"],
  "30": ["wedding_element_pearl"],
  "35": ["wedding_element_corals"],
  "37.5": ["wedding_element_electron"],
  "40": ["wedding_element_ruby"],
  "45": ["wedding_element_sapphire"],
  "50": ["wedding_element_gold"],
  "55": ["wedding_element_emerald"],
  "60": ["wedding_element_diamonds"],
  "65": ["wedding_element_bluecrowndiamond"],
  "70": ["wedding_element_iron"],
  "75": ["wedding_element_nuclear"],
  "80": ["wedding_element_oak"],
  "90": ["wedding_element_granite"]
};

const Map<String, List<String>> _anniversariesFR =
{
  "1": ["wedding_element_cotton"],
  "2": ["Cuir"],
  "3": ["Froment"],
  "4": ["Cire"],
  "5": ["Bois"],
  "6": ["Chypre"],
  "7": ["Laine"],
  "8": ["Coquelicot"],
  "9": ["Faïence"],
  "10": ["Étain"],
  "11": ["Corail"],
  "12": ["Soie"],
  "13": ["Muguet"],
  "14": ["wedding_element_lead"],
  "15": ["wedding_element_crystal"],
  "16": ["wedding_element_sapphire"],
  "17": ["wedding_element_rose"],
  "18": ["wedding_element_turquoise"],
  "19": ["wedding_element_cretonne"],
  "20": ["wedding_element_porcelain"],
  "21": ["Opale"],
  "22": ["Bronze"],
  "23": ["Béryl"],
  "24": ["Satin"],
  "25": ["Argent"],
  "26": ["Jade"],
  "27": ["Acajou"],
  "28": ["Nickel"],
  "29": ["Velours"],
  "30": ["Perle"],
  "31": ["Basane"],
  "32": ["Cuivre"],
  "33": ["Porphyre"],
  "34": ["Ambre"],
  "35": ["Rubis"],
  "36": ["Mousseline"],
  "37": ["Papier"],
  "38": ["Mercure"],
  "39": ["Crêpe"],
  "40": ["Émeraude"],
  "41": ["Fer"],
  "42": ["Nacre"],
  "43": ["Flanelle"],
  "44": ["Topaze"],
  "45": ["Vermeil"],
  "46": ["Lavande"],
  "47": ["Cachemire"],
  "48": ["Améthyste"],
  "49": ["Cèdre"],
  "50": ["Or"],
  "51": ["Camélia"],
  "52": ["Tourmaline"],
  "53": ["Merisier"],
  "54": ["Zibeline"],
  "55": ["wedding_element_orchid"],
  "56": ["Buis/lapis-lazuli"],
  "57": ["Azalée"],
  "58": ["Érable"],
  "59": ["Olivier/vison"],
  "60": ["Diamant"],
  "61": ["Platane"],
  "62": ["Ivoire"],
  "63": ["Lilas"],
  "64": ["Astrakan"],
  "65": ["Palissandre"],
  "66": ["Jasmin"],
  "67": ["Chinchilla"],
  "68": ["wedding_element_granite"],
  "69": ["Mélèze"],
  "70": ["wedding_element_platinum"],
  "71": ["Ocre"],
  "72": ["wedding_element_titanium"],
  "73": ["Fonte"],
  "74": ["Sienne"],
  "75": ["Albâtre"],
  "76": ["Zinc"],
  "77": ["Silice"],
  "78": ["Ébène"],
  "79": ["Bambou"],
  "80": ["Chêne"],
  "81": ["Cornaline"],
  "82": ["Grenat"],
  "83": ["Vanille"],
  "84": ["Iris"],
  "85": ["Uranium"],
  "86": ["Jaspe"],
  "87": ["Psilocybe"],
  "88": ["Pehuen"],
  "89": ["Onyx"],
  "90": ["wedding_element_granite"],
  "91": ["Héliodore"],
  "92": ["Lys"],
  "93": ["Lapis-lazuli"],
  "94": ["Péridot"],
  "95": ["Adansonia"],
  "96": ["Potasse"],
  "97": ["Tourmaline noire"],
  "98": ["If"],
  "99": ["Araucaria"],
  "100": ["Eau"]
};

const Map<String, List<String>> _anniversariesES =
{
  "1": ["Papel"],
  "2": ["Algodón"],
  "3": ["Cuero"],
  "4": ["Lino"],
  "5": ["Madera"],
  "6": ["Hierro"],
  "7": ["Lana"],
  "8": ["Bronce"],
  "9": ["Arcilla"],
  "10": ["Aluminio"],
  "11": ["Acero"],
  "12": ["Seda"],
  "13": ["Encaje"],
  "14": ["Marfil"],
  "15": ["Cristal"],
  "16": ["Hiedra"],
  "17": ["Alhelí"],
  "18": ["Cuarzo"],
  "19": ["Madreselva"],
  "20": ["Porcelana"],
  "21": ["Roble"],
  "22": ["Cobre"],
  "23": ["Agua"],
  "24": ["wedding_element_granite"],
  "25": ["Plata"],
  "26": ["Rosas"],
  "27": ["Azabache"],
  "28": ["Ámbar"],
  "29": ["Granate"],
  "30": ["Perla"],
  "31": ["Ébano"],
  "32": ["Cobre"],
  "33": ["Estaño"],
  "34": ["Amapola"],
  "35": ["Coral"],
  "36": ["Sílex"],
  "37": ["Piedra"],
  "38": ["Jade"],
  "39": ["Ágata"],
  "40": ["Rubí"],
  "41": ["Topacio"],
  "42": ["Jaspe"],
  "43": ["Ópalo"],
  "44": ["Turquesa"],
  "45": ["Zafiro"],
  "46": ["Nácar"],
  "47": ["Amatista"],
  "48": ["Feldespato"],
  "49": ["Circón"],
  "50": ["Oro"],
  "55": ["Esmeralda"],
  "60": ["Diamante"],
  "65": ["wedding_element_platinum"],
  "70": ["wedding_element_titanium"],
  "75": ["Brillantes"],
  "80": ["Roble"],
  "85": ["wedding_element_marble"],
  "90": ["wedding_element_granite"],
  "95": ["wedding_element_onyx"],
  "100": ["Hueso"]
};

const Map<String, List<String>> _anniversariesIT =
{
  "1": ["wedding_element_paper", "wedding_element_watches", "wedding_element_carnation"],
  "2": ["wedding_element_cotton", "wedding_element_porcelain", "wedding_element_liliesofthevalley"],
  "3": ["wedding_element_leather", "wedding_element_glass", "wedding_element_crystal", "wedding_element_sunflower"],
  "4": ["wedding_element_linen", "wedding_element_householdappliances", "wedding_element_hydrangea"],
  "5": ["wedding_element_wood", "wedding_element_silverware", "wedding_element_aster"],
  "6": ["wedding_element_iron", "wedding_element_wood", "wedding_element_calla"],
  "7": ["wedding_element_wool", "wedding_element_stationery", "wedding_element_freesia"],
  "8": ["wedding_element_bronze", "wedding_element_lace", "wedding_element_linen", "wedding_element_syringa"],
  "9": ["wedding_element_clay", "wedding_element_leather", "wedding_element_strelitzia"],
  "10": ["wedding_element_aluminium", "wedding_element_pan", "wedding_element_lotusflowers"],
  "11": ["wedding_element_maplewood", "wedding_element_jewellery", "wedding_element_tulip"],
  "12": ["wedding_element_silk", "wedding_element_pearl", "wedding_element_gemstones", "wedding_element_peony"],
  "13": ["wedding_element_lace", "wedding_element_fur", "wedding_element_chrysanthemum"],
  "14": ["wedding_element_ivory", "wedding_element_plasticjewellery", "wedding_element_whitedahlia"],
  "15": ["wedding_element_crystal", "wedding_element_wristwatch", "wedding_element_rose"],
  "16": ["wedding_element_ivy", "wedding_element_silverware"],
  "17": ["wedding_element_violet", "wedding_element_furniture"],
  "18": ["wedding_element_quartz", "wedding_element_porcelain"],
  "19": ["wedding_element_honeysuckle", "wedding_element_bronze", "wedding_element_sweetpea"],
  "20": ["wedding_element_porcelain", "wedding_element_platinum", "wedding_element_astro"],
  "21": ["wedding_element_oak", "wedding_element_brass", "wedding_element_nickel"],
  "22": ["wedding_element_bronze", "wedding_element_copper"],
  "23": ["wedding_element_water", "wedding_element_silverplated"],
  "24": ["wedding_element_silk", "wedding_element_musicalinstruments"],
  "25": ["wedding_element_silver", "wedding_element_sterlingsilver", "wedding_element_iris"],
  "26": ["wedding_element_rose"],
  "27": ["wedding_element_mahogany"],
  "28": ["wedding_element_amber", "wedding_element_orchid"],
  "29": ["wedding_element_velvet"],
  "30": ["wedding_element_pearl", "wedding_element_diamonds", "wedding_element_lily"],
  "31": ["wedding_element_ebony"],
  "32": ["wedding_element_copper"],
  "33": ["wedding_element_tin"],
  "34": ["wedding_element_ampoule"],
  "35": ["wedding_element_corals"],
  "36": ["wedding_element_silica"],
  "37": ["wedding_element_stone"],
  "38": ["wedding_element_jade"],
  "39": ["wedding_element_agate"],
  "40": ["wedding_element_ruby", "wedding_element_gladiolus"],
  "41": ["wedding_element_topaz"],
  "42": ["wedding_element_jasper"],
  "43": ["wedding_element_opal"],
  "44": ["wedding_element_turquoise"],
  "45": ["wedding_element_sapphire"],
  "46": ["wedding_element_motherofpearl"],
  "47": ["wedding_element_amethyst"],
  "48": ["wedding_element_feldspar"],
  "49": ["wedding_element_zircon"],
  "50": ["wedding_element_gold", "wedding_element_yelloworpurplerose"],
  "55": ["wedding_element_emerald"],
  "60": ["wedding_element_diamonds"],
  "65": ["wedding_element_stone"],
  "70": ["wedding_element_titanium"],
  "75": ["wedding_element_platinum"],
  "80": ["wedding_element_oak"],
  "85": ["wedding_element_marble"],
  "90": ["wedding_element_granite"],
  "95": ["wedding_element_onyx"],
  "100": ["wedding_element_ashes", "wedding_element_bone", "wedding_element_porphyry"]
};
