part of 'package:gc_wizard/tools/uncategorized/wedding_anniversaries/logic/wedding_anniversaries.dart';

/*
Sources:
https://de.wikipedia.org/wiki/Hochzeitstag
https://en.wikipedia.org/wiki/Wedding_anniversary
https://nl.wikipedia.org/wiki/Trouwdag
https://da.wikipedia.org/wiki/Bryllupsdag
https://sv.wikipedia.org/wiki/Lista_över_namn_på_bröllopsdagar
https://fr.wikipedia.org/wiki/Anniversaire_de_mariage
https://es.wikipedia.org/wiki/Aniversario_de_bodas
https://it.wikipedia.org/wiki/Anniversario_di_matrimonio

https://www.welt-der-zahlen.info/hochzeitstage.html
https://www.trouwplannen.nl/vieren-van-huwelijksjubileum/
https://bruiloftinspiratie.nl/alle-jubilea-van-het-huwelijk/
https://skyfly.nl/nieuws/alle-bruiloftsjaren-op-een-rij/
https://historiek.net/jubilea-benamingen-en-kleuren/156360/
https://madeformoments.nl/hoe-heten-jubileumjaren
https://www.wimmeeussen.be/nl/nieuws/huwelijksverjaardag-belgie
https://www.huwelijk.be/nuttige-tips/huwelijksverjaardagen.asp
https://www.locomix.eu/nl/blog/huwelijksjubileum-oftewel-de-huwelijksverjaardag/
*/

const Map<String, List<String>> _anniversariesDE =
{
  '0': ['wedding_element_green', 'wedding_element_white'],
  '0.75': ['wedding_element_beer'],
  '1': ['wedding_element_paper', 'wedding_element_cotton'],
  '2': ['wedding_element_cotton', 'wedding_element_paper', 'wedding_element_leather'],
  '3': ['wedding_element_leather', 'wedding_element_fruit', 'wedding_element_firs', 'wedding_element_wheat'],
  '4': ['wedding_element_silk', 'wedding_element_amber', 'wedding_element_linen', 'wedding_element_wine', 'wedding_element_wax'],
  '5': ['wedding_element_wood', 'wedding_element_gum', 'wedding_element_creampuff', 'wedding_element_diligence', 'wedding_element_ox', 'wedding_element_bull'],
  '6': ['wedding_element_sugar', 'wedding_element_ox', 'wedding_element_tin', 'wedding_element_iron', 'wedding_element_cyprus'],
  '6.25': ['wedding_element_mutton', 'wedding_element_tin'],
  '6.5': ['wedding_element_tin'],
  '7': ['wedding_element_copper', 'wedding_element_brass', 'wedding_element_wool', 'wedding_element_friendship'],
  '8': ['wedding_element_sheetmetal', 'wedding_element_poppy', 'wedding_element_stoneware', 'wedding_element_salt', 'wedding_element_nickel', 'wedding_element_bronze'],
  '9': [ 'wedding_element_ceramics', 'wedding_element_porcelain', 'wedding_element_glass', 'wedding_element_crystal', 'wedding_element_ox', 'wedding_element_water', 'wedding_element_willows'],
  '10': ['wedding_element_bronze', 'wedding_element_rose', 'wedding_element_wood', 'wedding_element_glass', 'wedding_element_sheetmetal', 'wedding_element_tin', 'wedding_element_ox'],
  '11': ['wedding_element_steel', 'wedding_element_coral', 'wedding_element_shrovetide'],
  '12': ['wedding_element_silk', 'wedding_element_soil', 'wedding_element_linen', 'wedding_element_tin', 'wedding_element_nickel', 'wedding_element_violet'],
  '12.5': ['wedding_element_sheetmetal', 'wedding_element_copper', 'wedding_element_nickel', 'wedding_element_medium', 'wedding_element_tin', 'wedding_element_bronze', 'wedding_element_violet', 'wedding_element_parsley'],
  '13': ['wedding_element_violet', 'wedding_element_liliesofthevalley', 'wedding_element_salt', 'wedding_element_lace'],
  '14': ['wedding_element_ivory', 'wedding_element_agate', 'wedding_element_lead', 'wedding_element_blue'],
  '15': ['wedding_element_glass', 'wedding_element_crystal', 'wedding_element_pluennen', 'wedding_element_rags', 'wedding_element_bottles', 'wedding_element_violet'],
  '16': ['wedding_element_sapphire'],
  '17': ['wedding_element_orchid','wedding_element_rose', 'wedding_element_soup'],
  '18': ['wedding_element_turquoise'],
  '19': ['wedding_element_motherofpearl', 'wedding_element_cretonne'],
  '20': ['wedding_element_porcelain', 'wedding_element_copper', 'wedding_element_chrysanthemum', 'wedding_element_thorns'],
  '21': ['wedding_element_beeches', 'wedding_element_opal'],
  '22': ['wedding_element_bronze', 'wedding_element_tourmaline'],
  '23': ['wedding_element_beryl', 'wedding_element_titanium'],
  '24': ['wedding_element_satin', 'wedding_element_silk'],
  '25': ['wedding_element_silver'],
  '26': ['wedding_element_jade', 'wedding_element_oak'],
  '27': ['wedding_element_jute', 'wedding_element_mahogany'],
  '28': ['wedding_element_nickel', 'wedding_element_carnation'],
  '29': ['wedding_element_ebony', 'wedding_element_velvet'],
  '30': ['wedding_element_pearl', 'wedding_element_gingerbread', 'wedding_element_lansquenet'],
  '31': ['wedding_element_limetree'],
  '32': ['wedding_element_copper', 'wedding_element_soap', 'wedding_element_lapislazuli'],
  '33': ['wedding_element_porphyry', 'wedding_element_tin'],
  '33.3': ['wedding_element_garlic'],
  '34': ['wedding_element_tin'],
  '35': ['wedding_element_canvas', 'wedding_element_coral', 'wedding_element_linen'],
  '36': ['wedding_element_emerald'],
  '37': ['wedding_element_malachit'],
  '37.5': ['wedding_element_aluminium'],
  '38': ['wedding_element_fire', 'wedding_element_mercury'],
  '39': ['wedding_element_sun', 'wedding_element_krepp'],
  '40': ['wedding_element_ruby', 'wedding_element_garnet', 'wedding_element_emerald'],
  '41': ['wedding_element_birches', 'wedding_element_iron'],
  '42': ['wedding_element_garnet', 'wedding_element_motherofpearl'],
  '43': ['wedding_element_lead', 'wedding_element_flannel'],
  '44': ['wedding_element_stars', 'wedding_element_topaz'],
  '45': ['wedding_element_brass', 'wedding_element_sapphire', 'wedding_element_edelweiss', 'wedding_element_platinum', 'wedding_element_tourmaline'],
  '46': ['wedding_element_lavender', 'wedding_element_marble'],
  '47': ['wedding_element_cashmere', 'wedding_element_sapphire'],
  '48': ['wedding_element_amethyst', 'wedding_element_diadem'],
  '49': ['wedding_element_cedar', 'wedding_element_uranus'],
  '50': ['wedding_element_gold'],
  '51': ['wedding_element_willows'],
  '52': ['wedding_element_topaz'],
  '53': ['wedding_element_uranium'],
  '54': ['wedding_element_zeus'],
  '55': ['wedding_element_platinum', 'wedding_element_jewellery', 'wedding_element_sapphire', 'wedding_element_emerald'],
  '56': ['wedding_element_aster'],
  '57': ['wedding_element_jade'],
  '58': ['wedding_element_angels'],
  '59': ['wedding_element_tides'],
  '60': ['wedding_element_diamond'],
  '61': ['wedding_element_elms'],
  '62': ['wedding_element_aquamarine'],
  '63': ['wedding_element_mercury'],
  '64': ['wedding_element_heaven'],
  '65': ['wedding_element_iron'],
  '66': ['wedding_element_chives'],
  '67': ['wedding_element_stone'],
  '68': ['wedding_element_granite'],
  '69': ['wedding_element_larche'],
  '70': ['wedding_element_graces', 'wedding_element_platinum', 'wedding_element_copper'],
  '71': ['wedding_element_ochre'],
  '72': ['wedding_element_graces'],
  '72.5': ['wedding_element_jewellery'],
  '73': ['wedding_element_castiron'],
  '74': ['wedding_element_apple'],
  '75': ['wedding_element_crownjewels', 'wedding_element_radium', 'wedding_element_stone', 'wedding_element_alabaster', 'wedding_element_graces', 'wedding_element_iron'],
  '76': ['wedding_element_cypresses'],
  '77': ['wedding_element_lavender'],
  '78': ['wedding_element_ebony'],
  '79': ['wedding_element_coffee'],
  '80': ['wedding_element_oak'],
  '81':	['wedding_element_cocoa'],
  '82':	['wedding_element_carnation'],
  '83':	['wedding_element_begonias'],
  '84':	['wedding_element_chrysanthemum'],
  '85':	['wedding_element_angels'],
  '86':	['wedding_element_hydrangea'],
  '87':	['wedding_element_maple'],
  '88':	['wedding_element_pears'],
  '89':	['wedding_element_figs'],
  '90':	['wedding_element_marble'],
  '91':	['wedding_element_pine'],
  '92':	['wedding_element_lily'],
  '93':	['wedding_element_lapislazuli'],
  '94':	['wedding_element_palms'],
  '95':	['wedding_element_sandalwood'],
  '96':	['wedding_element_olive'],
  '97':	['wedding_element_firs'],
  '98':	['wedding_element_pine'],
  '99':	['wedding_element_willows'],
  '100': ['wedding_element_heaven']
};

const Map<String, List<String>> _anniversariesUK =
{
  '1': ['wedding_element_paper'],
  '2': ['wedding_element_cotton'],
  '3': ['wedding_element_leather'],
  '4': ['wedding_element_fruit', 'wedding_element_flowers'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_iron'],
  '7': ['wedding_element_wool', 'wedding_element_copper'],
  '8': ['wedding_element_bronze'],
  '9': ['wedding_element_pottery'],
  '10': ['wedding_element_tin', 'wedding_element_aluminium'],
  '11': ['wedding_element_steel'],
  '12': ['wedding_element_silk'],
  '13': ['wedding_element_lace'],
  '14': ['wedding_element_ivory'],
  '15': ['wedding_element_crystal'],
  '20': ['wedding_element_porcelain'],
  '25': ['wedding_element_silver'],
  '30': ['wedding_element_pearl'],
  '35': ['wedding_element_coral'],
  '40': ['wedding_element_ruby'],
  '45': ['wedding_element_sapphire'],
  '50': ['wedding_element_gold'],
  '55': ['wedding_element_emerald'],
  '60': ['wedding_element_diamond'],
  '70': ['wedding_element_platinum'],
  '75': ['wedding_element_diamond', 'wedding_element_gold'],
  '85': ['wedding_element_moonstone', 'wedding_element_wine']
};

const Map<String, List<String>> _anniversariesUS =
{
  '1': ['wedding_element_cotton', 'wedding_element_paper'],
  '2': ['wedding_element_paper', 'wedding_element_cotton'],
  '3': ['wedding_element_leather'],
  '4': ['wedding_element_linen', 'wedding_element_silk'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_sugar'],
  '7': ['wedding_element_wool'],
  '8': ['wedding_element_brass', 'wedding_element_salt'],
  '9': ['wedding_element_copper'],
  '10': ['wedding_element_tin'],
  '12': ['wedding_element_silk', 'wedding_element_finelinen'],
  '15': ['wedding_element_crystal'],
  '20': ['wedding_element_porcelain'],
  '25': ['wedding_element_silver'],
  '30': ['wedding_element_pearl'],
  '35': ['wedding_element_coral'],
  '40': ['wedding_element_ruby'],
  '45': ['wedding_element_sapphire'],
  '50': ['wedding_element_gold'],
  '55': ['wedding_element_emerald'],
  '60': ['wedding_element_diamond'],
  '65': ['wedding_element_bluesapphire'],
  '70': ['wedding_element_platinum'],
  '75': ['wedding_element_diamond', 'wedding_element_gold'],
  '80': ['wedding_element_oak'],
  '85': ['wedding_element_wine'],
  '90': ['wedding_element_granite']
};

const Map<String, List<String>> _anniversariesNL =
{
  '1': ['wedding_element_cotton'],
  '2': ['wedding_element_paper', 'wedding_element_leather'],
  '2.5': ['wedding_element_aluminium'],
  '3': ['wedding_element_leather', 'wedding_element_wheat'],
  '4': ['wedding_element_silk', 'wedding_element_wax'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_iron'],
  '7': ['wedding_element_wool'],
  '8': ['wedding_element_bronze'],
  '9': ['wedding_element_pottery'],
  '10': ['wedding_element_tin'],
  '11': ['wedding_element_steel'],
  '12': ['wedding_element_linen', 'wedding_element_silk'],
  '12.5': ['wedding_element_copper'],
  '13': ['wedding_element_lace'],
  '14': ['wedding_element_ivory'],
  '15': ['wedding_element_crystal'],
  '16': ['wedding_element_sapphire'],
  '17': ['wedding_element_rose'],
  '18': ['wedding_element_turquoise'],
  '19': ['wedding_element_linen'],
  '20': ['wedding_element_porcelain'],
  '25': ['wedding_element_silver'],
  '30': ['wedding_element_pearl'],
  '35': ['wedding_element_coral', 'wedding_element_ruby'],
  '37.5': ['wedding_element_aluminium'],
  '40': ['wedding_element_ruby', 'wedding_element_emerald'],
  '45': ['wedding_element_sapphire'],
  '50': ['wedding_element_gold'],
  '55': ['wedding_element_emerald', 'wedding_element_orchid'],
  '60': ['wedding_element_diamond'],
  '65': ['wedding_element_brilliant'],
  '70': ['wedding_element_platinum'],
  '75': ['wedding_element_alabaster'],
  '80': ['wedding_element_oak'],
  '90': ['wedding_element_granite']
};

const Map<String, List<String>> _anniversariesSW =
{
  '1': ['wedding_element_cotton'],
  '2': ['wedding_element_paper'],
  '3': ['wedding_element_leather'],
  '4': ['wedding_element_flowers', 'wedding_element_fruit'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_iron'],
  '7': ['wedding_element_copper'],
  '8': ['wedding_element_bronze'],
  '9': ['wedding_element_linen', 'wedding_element_willows', 'wedding_element_ceramics'],
  '10': ['wedding_element_tin', 'wedding_element_aluminium'],
  '11': ['wedding_element_steel'],
  '12': ['wedding_element_silk'],
  '12.5': ['wedding_element_copper'],
  '13': ['wedding_element_lace'],
  '14': ['wedding_element_ivory'],
  '15': ['wedding_element_crystal'],
  '20': ['wedding_element_porcelain'],
  '25': ['wedding_element_silver'],
  '30': ['wedding_element_pearl'],
  '35': ['wedding_element_coral'],
  '40': ['wedding_element_ruby'],
  '45': ['wedding_element_sapphire'],
  '50': ['wedding_element_gold'],
  '55': ['wedding_element_emerald'],
  '60': ['wedding_element_diamond'],
  '65': ['wedding_element_crownjewels'],
  '70': ['wedding_element_iron'],
  '75': ['wedding_element_iron', 'wedding_element_diamond'],
  '80': ['wedding_element_platinum'],
  '85': ['wedding_element_moonstone'],
  '90': ['wedding_element_stone']
};

const Map<String, List<String>> _anniversariesDK =
{
  '1': ['wedding_element_paper'],
  '2': ['wedding_element_cotton'],
  '3': ['wedding_element_leather'],
  '4': ['wedding_element_flowers', 'wedding_element_hyacinth'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_sugar'],
  '7': ['wedding_element_wool'],
  '8': ['wedding_element_bronze'],
  '9': ['wedding_element_willows', 'wedding_element_straw'],
  '10': ['wedding_element_tin'],
  '11': ['wedding_element_steel', 'wedding_element_amber'],
  '12': ['wedding_element_silk'],
  '12.5': ['wedding_element_copper'],
  '13': ['wedding_element_lace'],
  '14': ['wedding_element_ivory'],
  '15': ['wedding_element_crystal'],
  '16': ['wedding_element_moon'],
  '17': ['wedding_element_amethyst'],
  '18': ['wedding_element_daisy', 'wedding_element_satin'],
  '19': ['wedding_element_garnet'],
  '20': ['wedding_element_porcelain'],
  '21': ['wedding_element_turquoise'],
  '22': ['wedding_element_alliance'],
  '23': ['wedding_element_tulip'],
  '24': ['wedding_element_carat'],
  '25': ['wedding_element_silver'],
  '30': ['wedding_element_pearl'],
  '35': ['wedding_element_coral'],
  '37.5': ['wedding_element_electron'],
  '40': ['wedding_element_ruby'],
  '45': ['wedding_element_sapphire'],
  '50': ['wedding_element_gold'],
  '55': ['wedding_element_emerald'],
  '60': ['wedding_element_diamond'],
  '65': ['wedding_element_bluecrowndiamond'],
  '70': ['wedding_element_iron'],
  '75': ['wedding_element_nuclear'],
  '80': ['wedding_element_oak'],
  '90': ['wedding_element_granite']
};

const Map<String, List<String>> _anniversariesFR =
{
  '1': ['wedding_element_cotton'],
  '2': ['wedding_element_leather'],
  '3': ['wedding_element_wheat'],
  '4': ['wedding_element_wax'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_cyprus'],
  '7': ['wedding_element_wool'],
  '8': ['wedding_element_poppy'],
  '9': ['wedding_element_faience'],
  '10': ['wedding_element_tin'],
  '11': ['wedding_element_coral'],
  '12': ['wedding_element_silk'],
  '13': ['wedding_element_liliesofthevalley'],
  '14': ['wedding_element_lead'],
  '15': ['wedding_element_crystal'],
  '16': ['wedding_element_sapphire'],
  '17': ['wedding_element_rose'],
  '18': ['wedding_element_turquoise'],
  '19': ['wedding_element_cretonne'],
  '20': ['wedding_element_porcelain'],
  '21': ['wedding_element_opal'],
  '22': ['wedding_element_bronze'],
  '23': ['wedding_element_beryl'],
  '24': ['wedding_element_satin'],
  '25': ['wedding_element_silver'],
  '26': ['wedding_element_jade'],
  '27': ['wedding_element_mahogany'],
  '28': ['wedding_element_nickel'],
  '29': ['wedding_element_velvet'],
  '30': ['wedding_element_pearl'],
  '31': ['wedding_element_sheepskin'],
  '32': ['wedding_element_copper'],
  '33': ['wedding_element_porphyry'],
  '34': ['wedding_element_amber'],
  '35': ['wedding_element_ruby'],
  '36': ['wedding_element_muslin'],
  '37': ['wedding_element_paper'],
  '38': ['wedding_element_mercury'],
  '39': ['wedding_element_krepp'],
  '40': ['wedding_element_emerald'],
  '41': ['wedding_element_iron'],
  '42': ['wedding_element_motherofpearl'],
  '43': ['wedding_element_flannel'],
  '44': ['wedding_element_topaz'],
  '45': ['wedding_element_silvergilt'],
  '46': ['wedding_element_lavender'],
  '47': ['wedding_element_cashmere'],
  '48': ['wedding_element_amethyst'],
  '49': ['wedding_element_cedar'],
  '50': ['wedding_element_gold'],
  '51': ['wedding_element_camellia'],
  '52': ['wedding_element_tourmaline'],
  '53': ['wedding_element_wildcherry'],
  '54': ['wedding_element_sable'],
  '55': ['wedding_element_orchid'],
  '56': ['wedding_element_buxus','wedding_element_lapislazuli'],
  '57': ['wedding_element_azalea'],
  '58': ['wedding_element_maple'],
  '59': ['wedding_element_olives', 'wedding_element_mink'],
  '60': ['wedding_element_diamond'],
  '61': ['wedding_element_platanus'],
  '62': ['wedding_element_ivory'],
  '63': ['wedding_element_syringa'],
  '64': ['wedding_element_astrakan'],
  '65': ['wedding_element_rosewood'],
  '66': ['wedding_element_jasmin'],
  '67': ['wedding_element_chinchilla'],
  '68': ['wedding_element_granite'],
  '69': ['wedding_element_larche'],
  '70': ['wedding_element_platinum'],
  '71': ['wedding_element_ochre'],
  '72': ['wedding_element_titanium'],
  '73': ['wedding_element_castiron'],
  '74': ['wedding_element_sienna'],
  '75': ['wedding_element_alabaster'],
  '76': ['wedding_element_zinc'],
  '77': ['wedding_element_silica'],
  '78': ['wedding_element_ebony'],
  '79': ['wedding_element_bamboo'],
  '80': ['wedding_element_oak'],
  '81': ['wedding_element_carnelian'],
  '82': ['wedding_element_garnet'],
  '83': ['wedding_element_vanilla'],
  '84': ['wedding_element_iris'],
  '85': ['wedding_element_uranium'],
  '86': ['wedding_element_jasper'],
  '87': ['wedding_element_psilocybe'],
  '88': ['wedding_element_pine'],
  '89': ['wedding_element_onyx'],
  '90': ['wedding_element_granite'],
  '91': ['wedding_element_beryl'],
  '92': ['wedding_element_lily'],
  '93': ['wedding_element_lapislazuli'],
  '94': ['wedding_element_peridot'],
  '95': ['wedding_element_baobab'],
  '96': ['wedding_element_potash'],
  '97': ['wedding_element_black_tourmaline'],
  '98': ['wedding_element_taxus'],
  '99': ['wedding_element_araucaria'],
  '100': ['wedding_element_water']
};

const Map<String, List<String>> _anniversariesES =
{
  '1': ['wedding_element_paper'],
  '2': ['wedding_element_cotton'],
  '3': ['wedding_element_leather'],
  '4': ['wedding_element_linen'],
  '5': ['wedding_element_wood'],
  '6': ['wedding_element_iron'],
  '7': ['wedding_element_wool'],
  '8': ['wedding_element_bronze'],
  '9': ['wedding_element_clay'],
  '10': ['wedding_element_aluminium'],
  '11': ['wedding_element_steel'],
  '12': ['wedding_element_silk'],
  '13': ['wedding_element_lace'],
  '14': ['wedding_element_ivory'],
  '15': ['wedding_element_crystal'],
  '16': ['wedding_element_ivy'],
  '17': ['wedding_element_wallflower'],
  '18': ['wedding_element_quartz'],
  '19': ['wedding_element_honeysuckle'],
  '20': ['wedding_element_porcelain'],
  '21': ['wedding_element_oak'],
  '22': ['wedding_element_copper'],
  '23': ['wedding_element_water'],
  '24': ['wedding_element_granite'],
  '25': ['wedding_element_silver'],
  '26': ['wedding_element_rose'],
  '27': ['wedding_element_jet'],
  '28': ['wedding_element_amber'],
  '29': ['wedding_element_agate'],
  '30': ['wedding_element_pearl'],
  '31': ['wedding_element_ebony'],
  '32': ['wedding_element_copper'],
  '33': ['wedding_element_tin'],
  '34': ['wedding_element_papaver'],
  '35': ['wedding_element_coral'],
  '36': ['wedding_element_flint'],
  '37': ['wedding_element_stone'],
  '38': ['wedding_element_jade'],
  '39': ['wedding_element_agate'],
  '40': ['wedding_element_ruby'],
  '41': ['wedding_element_topaz'],
  '42': ['wedding_element_jasper'],
  '43': ['wedding_element_opal'],
  '44': ['wedding_element_turquoise'],
  '45': ['wedding_element_sapphire'],
  '46': ['wedding_element_motherofpearl'],
  '47': ['wedding_element_amethyst'],
  '48': ['wedding_element_feldspar'],
  '49': ['wedding_element_zircon'],
  '50': ['wedding_element_gold'],
  '55': ['wedding_element_emerald'],
  '60': ['wedding_element_diamond'],
  '65': ['wedding_element_platinum'],
  '70': ['wedding_element_titanium'],
  '75': ['wedding_element_brilliant'],
  '80': ['wedding_element_oak'],
  '85': ['wedding_element_marble'],
  '90': ['wedding_element_granite'],
  '95': ['wedding_element_onyx'],
  '100': ['wedding_element_bone']
};

const Map<String, List<String>> _anniversariesIT =
{
  '1': ['wedding_element_paper', 'wedding_element_watches', 'wedding_element_carnation'],
  '2': ['wedding_element_cotton', 'wedding_element_porcelain', 'wedding_element_liliesofthevalley'],
  '3': ['wedding_element_leather', 'wedding_element_glass', 'wedding_element_crystal', 'wedding_element_sunflower'],
  '4': ['wedding_element_linen', 'wedding_element_householdappliances', 'wedding_element_hydrangea'],
  '5': ['wedding_element_wood', 'wedding_element_silverware', 'wedding_element_aster'],
  '6': ['wedding_element_iron', 'wedding_element_wood', 'wedding_element_calla'],
  '7': ['wedding_element_wool', 'wedding_element_stationery', 'wedding_element_freesia'],
  '8': ['wedding_element_bronze', 'wedding_element_lace', 'wedding_element_linen', 'wedding_element_syringa'],
  '9': ['wedding_element_clay', 'wedding_element_leather', 'wedding_element_strelitzia'],
  '10': ['wedding_element_aluminium', 'wedding_element_pan', 'wedding_element_lotusflowers'],
  '11': ['wedding_element_maple', 'wedding_element_jewellery', 'wedding_element_tulip'],
  '12': ['wedding_element_silk', 'wedding_element_pearl', 'wedding_element_gemstones', 'wedding_element_peony'],
  '13': ['wedding_element_lace', 'wedding_element_fur', 'wedding_element_chrysanthemum'],
  '14': ['wedding_element_ivory', 'wedding_element_plasticjewellery', 'wedding_element_whitedahlia'],
  '15': ['wedding_element_crystal', 'wedding_element_wristwatch', 'wedding_element_rose'],
  '16': ['wedding_element_ivy', 'wedding_element_silverware'],
  '17': ['wedding_element_violet', 'wedding_element_furniture'],
  '18': ['wedding_element_quartz', 'wedding_element_porcelain'],
  '19': ['wedding_element_honeysuckle', 'wedding_element_bronze', 'wedding_element_sweetpea'],
  '20': ['wedding_element_porcelain', 'wedding_element_platinum', 'wedding_element_astro'],
  '21': ['wedding_element_oak', 'wedding_element_brass', 'wedding_element_nickel'],
  '22': ['wedding_element_bronze', 'wedding_element_copper'],
  '23': ['wedding_element_water', 'wedding_element_silverplated'],
  '24': ['wedding_element_silk', 'wedding_element_musicalinstruments'],
  '25': ['wedding_element_silver', 'wedding_element_sterlingsilver', 'wedding_element_iris'],
  '26': ['wedding_element_rose'],
  '27': ['wedding_element_mahogany'],
  '28': ['wedding_element_amber', 'wedding_element_orchid'],
  '29': ['wedding_element_velvet'],
  '30': ['wedding_element_pearl', 'wedding_element_diamond', 'wedding_element_lily'],
  '31': ['wedding_element_ebony'],
  '32': ['wedding_element_copper'],
  '33': ['wedding_element_tin'],
  '34': ['wedding_element_ampoule'],
  '35': ['wedding_element_coral'],
  '36': ['wedding_element_silica'],
  '37': ['wedding_element_stone'],
  '38': ['wedding_element_jade'],
  '39': ['wedding_element_agate'],
  '40': ['wedding_element_ruby', 'wedding_element_gladiolus'],
  '41': ['wedding_element_topaz'],
  '42': ['wedding_element_jasper'],
  '43': ['wedding_element_opal'],
  '44': ['wedding_element_turquoise'],
  '45': ['wedding_element_sapphire'],
  '46': ['wedding_element_motherofpearl'],
  '47': ['wedding_element_amethyst'],
  '48': ['wedding_element_feldspar'],
  '49': ['wedding_element_zircon'],
  '50': ['wedding_element_gold', 'wedding_element_yelloworpurplerose'],
  '55': ['wedding_element_emerald'],
  '60': ['wedding_element_diamond'],
  '65': ['wedding_element_stone'],
  '70': ['wedding_element_titanium'],
  '75': ['wedding_element_platinum'],
  '80': ['wedding_element_oak'],
  '85': ['wedding_element_marble'],
  '90': ['wedding_element_granite'],
  '95': ['wedding_element_onyx'],
  '100': ['wedding_element_ashes', 'wedding_element_bone', 'wedding_element_porphyry']
};
