part of 'gcwizard_scipt_test.dart';

List<Map<String, Object?>> _inputsGraphicToExpected = [
  // graphic
  'STROKE': _GCWizardScriptClassFunctionDefinition(_stroke, 1, functionReturn: false),
  'CIRCLE': _GCWizardScriptClassFunctionDefinition(_circle, 3, functionReturn: false),
  'LINE': _GCWizardScriptClassFunctionDefinition(_line, 4, functionReturn: false),
  'POINT': _GCWizardScriptClassFunctionDefinition(_point, 2, functionReturn: false),
  'ARC': _GCWizardScriptClassFunctionDefinition(_arc, 5, functionReturn: false),
  'PIE': _GCWizardScriptClassFunctionDefinition(_pie, 5, functionReturn: false),
  'COLOR': _GCWizardScriptClassFunctionDefinition(_color, 3, functionReturn: false),
  'FILL': _GCWizardScriptClassFunctionDefinition(_fill, 1, functionReturn: false),
  'TEXT': _GCWizardScriptClassFunctionDefinition(_text, 4, functionReturn: false),
  'BOX': _GCWizardScriptClassFunctionDefinition(_box, 4, functionReturn: false),
  'OVAL': _GCWizardScriptClassFunctionDefinition(_oval, 4, functionReturn: false),

  {'code' : 'print STROKE(10)', 'expectedOutput' : '10'},
  {'code' : 'print STROKE(10.0)', 'expectedOutput' : '10'},
  {'code' : 'print CIRCLE(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print CIRCLE(10, 10, 20)', 'expectedOutput' : ''},
  {'code' : 'print CIRCLE(10.0, 10.0, 20.0)', 'expectedOutput' : ''},
  {'code' : 'print LINE(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print LINE(10, 10, 20, 20)', 'expectedOutput' : ''},
  {'code' : 'print LINE(10.0, 10.0, 20.0, 20.0)', 'expectedOutput' : ''},

  {'code' : 'print BOX(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print BOX(10, 10, 20, 20)', 'expectedOutput' : ''},

  {'code' : 'print ABS(-10)', 'expectedOutput' : '10'},
  {'code' : 'print ABS(-10.0)', 'expectedOutput' : '10.0'},
  {'code' : 'print ARC(10, 10, 10.0, 90, 180.0)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print ARC(10, 10, 10.0, 90, 180.0)', 'expectedOutput' : ''},
  {'code' : 'print ASC(10)', 'expectedOutput' : '0', 'error': 'gcwizard_script_casting_error'},
  {'code' : 'print ASC("A)', 'expectedOutput' : '', 'error': 'gcwizard_script_casting_error'},
  {'code' : 'print ASC("A")', 'expectedOutput' : '65'},
  {'code' : 'print BWW(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print BWW("TEST", 0 , 0)', 'expectedOutput' : '64'},
  {'code' : 'print BWW("TEST", 0 , 1)', 'expectedOutput' : '10'},
  {'code' : 'print BWW("TEST", 0 , 1.0)', 'expectedOutput' : '10'},
  {'code' : 'print COS(10)', 'expectedOutput' : '-0.8390715290764524'},
  {'code' : 'print COS(10.0)', 'expectedOutput' : '-0.8390715290764524'},
  {'code' : 'print DEG(10)', 'expectedOutput' : '572.9577951308232'},
  {'code' : 'print DEG(10.0)', 'expectedOutput' : '572.9577951308232'},
  {'code' : 'print EXP(10)', 'expectedOutput' : '22026.465794806718'},
  {'code' : 'print FAC(10)', 'expectedOutput' : '3628800.0'},
  {'code' : 'print GGT(12, 3)', 'expectedOutput' : '3'},
  {'code' : 'print KGV(10, 3)', 'expectedOutput' : '30.0'},
  {'code' : 'print LEN(10)', 'expectedOutput' : '0', 'error': 'gcwizard_script_casting_error'},
  {'code' : 'print LEN("10")', 'expectedOutput' : '2'},
  {'code' : 'print LOG(10)', 'expectedOutput' : '1.0'},
  {'code' : 'print MID(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print MID(10, 5)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print MID("MIDTEST", 4, 4)', 'expectedOutput' : 'TEST'},
  {'code' : 'print MOD(10)', 'expectedOutput' : '0', 'error': 'gcwizard_script_casting_error'},
  {'code' : 'print MOD(10, 3)', 'expectedOutput' : '1'},
  {'code' : 'print MOD(10.0, 3)', 'expectedOutput' : '1.0'},
  {'code' : 'print MOD(10, 3.0)', 'expectedOutput' : '1.0'},
  {'code' : 'print PIE(10)', 'expectedOutput' : ''},
  {'code' : 'print PIE(10, 10, 10.0, 90, 180.0)', 'expectedOutput' : ''},
  {'code' : 'print POW(10)', 'expectedOutput' : '0', 'error': 'gcwizard_script_casting_error'},
  {'code' : 'print POW(10, 2)', 'expectedOutput' : '100'},
  {'code' : 'print POW(10.0, 2)', 'expectedOutput' : '100.0'},
  {'code' : 'print RAD(10)', 'expectedOutput' : '0.17453292519943295'},
  {'code' : 'print RAD(10.0)', 'expectedOutput' : '0.17453292519943295'},
  // {'code' : 'print RND(10)', 'expectedOutput' : '0.3894802723601313'},
  // {'code' : 'print RND(10.0)', 'expectedOutput' : '0.3894802723601313'},
  {'code' : 'print SGN(10)', 'expectedOutput' : '1'},
  {'code' : 'print SGN(10.0)', 'expectedOutput' : '1'},
  {'code' : 'print SGN(0)', 'expectedOutput' : '0'},
  {'code' : 'print SGN(-10)', 'expectedOutput' : '-1'},
  {'code' : 'print SIN(10)', 'expectedOutput' : '-0.5440211108893698'},
  {'code' : 'print SQR(10)', 'expectedOutput' : '100'},
  {'code' : 'print SQR(10.0)', 'expectedOutput' : '100.0'},
  {'code' : 'print STR(10)', 'expectedOutput' : '10'},
  {'code' : 'print TAN(10)', 'expectedOutput' : '0.6483608274590866'},
  {'code' : 'print VAL(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print VAL("10")', 'expectedOutput' : '10.0'},

  {'code' : 'print ACOS(1)', 'expectedOutput' : ''},
  {'code' : 'print ASIN(1)', 'expectedOutput' : ''},
  {'code' : 'print ATAN(1)', 'expectedOutput' : ''},
  {'code' : 'print BASE(10)', 'expectedOutput' : ''},
  {'code' : 'print CEIL(10)', 'expectedOutput' : ''},
  {'code' : 'print CHAR(10)', 'expectedOutput' : ''},
  {'code' : 'print FILL(10)', 'expectedOutput' : ''},
  {'code' : 'print FRAC(10)', 'expectedOutput' : ''},
  {'code' : 'print HASH(10)', 'expectedOutput' : ''},
  {'code' : 'print LEFT(10)', 'expectedOutput' : ''},
  {'code' : 'print LINE(10)', 'expectedOutput' : ''},
  {'code' : 'print OVAL(10)', 'expectedOutput' : ''},
  {'code' : 'print QSUM(10)', 'expectedOutput' : ''},
  {'code' : 'print ROTX(10)', 'expectedOutput' : ''},
  {'code' : 'print SQRT(10)', 'expectedOutput' : ''},
  {'code' : 'print TEXT(10)', 'expectedOutput' : ''},
];