import "package:flutter_test/flutter_test.dart";
import 'package:gc_wizard/logic/tools/crypto_and_encodings/numeral_words.dart';
import 'package:gc_wizard/utils/common_utils.dart';

void main(){
  group("NumeralWords.decodeNumeralwordsEntireWords:", () {
    List<Map<String, dynamic>> _inputsToExpected = [
      {'input' : '', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('', '', 'numeralwords_language_empty')]},
      {'input' : 'fünfundzwanzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('25', 'fuenfundzwanzig', 'numeralwords_language_deu')]},
      {'input' : 'hundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'hunderteins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101', 'hunderteins', 'numeralwords_language_deu')]},
      {'input' : 'hundertundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101', 'hunderteins', 'numeralwords_language_deu')]},
      {'input' : 'einhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'einshundert', 'numeralwords_language_deu')]},
      {'input' : 'einhunderteins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101', 'einshunderteins', 'numeralwords_language_deu')]},
      {'input' : 'einhundertundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101', 'einshunderteins', 'numeralwords_language_deu')]},
      {'input' : 'hundertfünfundzwanzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('125', 'hundertfuenfundzwanzig', 'numeralwords_language_deu')]},
      {'input' : 'abc einhundertfünfundzwanzig abc', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('125', 'einshundertfuenfundzwanzig', 'numeralwords_language_deu')]},
      {'input' : 'zweihundertfünfundzwanzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('225', 'zweihundertfuenfundzwanzig', 'numeralwords_language_deu')]},
      {'input' : 'tausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'eintausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'einstausend', 'numeralwords_language_deu')]},
      {'input' : 'zweitausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('2000', 'zweitausend', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100000', 'hunderttausend', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100100', 'hunderttausendhundert', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendeinhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100100', 'hunderttausendeinshundert', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendhunderteins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100101', 'hunderttausendhunderteins', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendhundertundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100101', 'hunderttausendhunderteins', 'numeralwords_language_deu')]},
      {'input' : 'einhunderttausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100000', 'einshunderttausend', 'numeralwords_language_deu')]},
      {'input' : 'einhunderttausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100001', 'einshunderttausendeins', 'numeralwords_language_deu')]},
      {'input' : 'hunderteinstausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101001', 'hunderteinstausendeins', 'numeralwords_language_deu')]},
      {'input' : 'hundertundeinstausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101001', 'hunderteinstausendeins', 'numeralwords_language_deu')]},
      {'input' : 'einhundertundeinstausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('101001', 'einshunderteinstausendeins', 'numeralwords_language_deu')]},
      {'input' : 'einhunderttausendundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100001', 'einshunderttausendeins', 'numeralwords_language_deu')]},
      {'input' : 'zweihunderttausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('200000', 'zweihunderttausend', 'numeralwords_language_deu')]},
      {'input' : 'fünfundzwanzigtausendsiebenhundertzweiundvierzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('25742', 'fuenfundzwanzigtausendsiebenhundertzweiundvierzig', 'numeralwords_language_deu')]},
      {'input' : 'dreihundertdreiunddreißigtausenddreihundertunddreiunddreißig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('333333', 'dreihundertdreiunddreissigtausenddreihundertdreiunddreissig', 'numeralwords_language_deu')]},

      {'input' : 'one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},
      {'input' : 'ten', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('10', 'ten', 'numeralwords_language_eng')]},
      {'input' : 'abc ten def one abc', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('10', 'ten', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},

      {'input' : 'fifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'fiftyone', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : []},
      {'input' : 'fifty-one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('51', 'fifty-one', 'numeralwords_language_eng')]},
      {'input' : 'fifty one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},

      {'input' : 'hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'a hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'onehundred', 'numeralwords_language_eng')]},
      {'input' : 'one hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'onehundred', 'numeralwords_language_eng')]},
      {'input' : 'onehundredfifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('150', 'onehundredfifty', 'numeralwords_language_eng')]},
      {'input' : 'one hundred fifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'onehundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'a hundred and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('155', 'onehundredfifty-five', 'numeralwords_language_eng')]},
      {'input' : 'two hundred and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('255', 'twohundredfifty-five', 'numeralwords_language_eng')]},

      {'input' : 'thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng')]},
      {'input' : 'a thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'onethousand', 'numeralwords_language_eng')]},
      {'input' : 'one thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'onethousand', 'numeralwords_language_eng')]},
      {'input' : 'one hundred thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100000', 'onehundredthousand', 'numeralwords_language_eng')]},
      {'input' : 'onethousandfifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1050', 'onethousandfifty', 'numeralwords_language_eng')]},
      {'input' : 'one thousand fifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'onethousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'a thousand and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1055', 'onethousandfifty-five', 'numeralwords_language_eng')]},
      {'input' : 'two thousand and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('2055', 'twothousandfifty-five', 'numeralwords_language_eng')]},

      {'input' : 'thousandhundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1100', 'thousandhundred', 'numeralwords_language_eng')]},
      {'input' : 'thousand hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'a thousand and hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1100', 'onethousandhundred', 'numeralwords_language_eng')]},
      {'input' : 'a thousand and onehundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1100', 'onethousandonehundred', 'numeralwords_language_eng')]},
      {'input' : 'onethousand and onehundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('1100', 'onethousandonehundred', 'numeralwords_language_eng')]},
      {'input' : 'a hundredthousandhundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100100', 'onehundredthousandhundred', 'numeralwords_language_eng')]},
      {'input' : 'a hundredthousandhundredone', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('100101', 'onehundredthousandhundredone', 'numeralwords_language_eng')]},
      {'input' : 'twohundredseventy-fivethousandhundred and one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('275101', 'twohundredseventy-fivethousandhundredone', 'numeralwords_language_eng')]},
      
      {'input' : 'huit dwa seize sis one two eins', 'language' : NumeralWordsLanguage.ALL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('8', 'huit', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('2', 'dwa', 'numeralwords_language_pol'),
                            NumeralWordsDecodeOutput('', '', 'numeralwords_language_rus'),
                            NumeralWordsDecodeOutput('16', 'seize', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('6', 'sis', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('2', 'two', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'fuenf fünf kvin cinq пять lul five zéro', 'language' : NumeralWordsLanguage.ALL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('5', 'kvin', 'numeralwords_language_epo'),
                            NumeralWordsDecodeOutput('5', 'cinq', 'numeralwords_language_fra'),
//                            NumeralWordsDecodeOutput('5', 'пять', 'numeralwords_language_kyr'),
                            NumeralWordsDecodeOutput('5', 'lul', 'numeralwords_language_vol'),
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('0', 'zero', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('', '', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('', '', 'numeralwords_language_ita'),
                            NumeralWordsDecodeOutput('', '', 'numeralwords_language_pol'),
                            NumeralWordsDecodeOutput('', '', 'numeralwords_language_por'),
        ]},
    ];

    _inputsToExpected.forEach((elem) {
      test('input: ${elem['input']}, language: ${elem['language']}, decodeMode: ${elem['decodeMode']}', () {
        var _actual = decodeNumeralwords(removeAccents(elem['input'].toString().toLowerCase()), elem['language'], elem['decodeMode']);
        var length = elem['expectedOutput'].length;
        for (int i = 0; i < length; i++) {
          expect(_actual[i].number, elem['expectedOutput'][i].number);
          expect(_actual[i].numWord, elem['expectedOutput'][i].numWord);
          expect(_actual[i].language, elem['expectedOutput'][i].language);
        }
      });
    });
  });

  group("NumeralWords.decodeNumeralwordsEntireWordsAsParts:", () {
    List<Map<String, dynamic>> _inputsToExpected = [
      {'input' : '', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false, 'expectedOutput' : ''},
      {'input' : 'fünfundzwanzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('20', 'zwanzig', 'numeralwords_language_deu')]},
      {'input' : 'hundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'hunderteins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'hundertundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'einhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'einhunderteins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'einhundertundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'hundertfünfundzwanzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('20', 'zwanzig', 'numeralwords_language_deu')]},
      {'input' : 'abc einhundertfünfundzwanzig abc', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('20', 'zwanzig', 'numeralwords_language_deu')]},
      {'input' : 'zweihundertfünfundzwanzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('20', 'zwanzig', 'numeralwords_language_deu')]},
      {'input' : 'tausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'eintausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'zweitausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendeinhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendhunderteins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'hunderttausendhundertundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'einhunderttausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'einhunderttausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'hunderteinstausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'hundertundeinstausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'einhundertundeinstausendeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'einhunderttausendundeins', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'zweihunderttausend', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu')]},
      {'input' : 'fünfundzwanzigtausendsiebenhundertzweiundvierzig', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('20', 'zwanzig', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1000', 'tausend', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('7', 'sieben', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('4', 'vier', 'numeralwords_language_deu')]},

      {'input' : 'one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},
      {'input' : 'ten', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('10', 'ten', 'numeralwords_language_eng')]},
      {'input' : 'abc ten def one abc', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('10', 'ten', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},

      {'input' : 'fifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'fiftyone', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},
      {'input' : 'fifty-one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},
      {'input' : 'fifty one', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},

      {'input' : 'hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'a hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'one hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'onehundredfifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'one hundred fifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'a hundred and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng') ,
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng')]},
      {'input' : 'two hundred and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'two', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng') ,
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng')]},

      {'input' : 'thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng')]},
      {'input' : 'a thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng')]},
      {'input' : 'one thousand', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng')]},
      {'input' : 'onethousandfifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'one thousand fifty', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'a thousand and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng')]},
      {'input' : 'two thousand and fifty-five', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'two', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng')]},

      {'input' : 'thousandhundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),]},
      {'input' : 'thousand hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),]},
      {'input' : 'a thousand and hundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),]},
      {'input' : 'a thousand and onehundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),]},
      {'input' : 'onethousand and onehundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'a hundredthousandhundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'a hundredthousandhundredone', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},
      {'input' : 'twohundredseventy-fivethousandhundredandone', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'two', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('7', 'seven', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('70', 'seventy', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1000', 'thousand', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng')]},

      {'input' : 'huit cinq seize sis one two eins', 'language' : NumeralWordsLanguage.ALL, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('8', 'huit', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('5', 'cinq', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('16', 'seize', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('6', 'sei', 'numeralwords_language_ita'),
                            NumeralWordsDecodeOutput('6', 'zes', 'numeralwords_language_nld'),
                            NumeralWordsDecodeOutput('6', 'sis', 'numeralwords_language_fra'),
                            NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('2', 'two', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
    ];

    _inputsToExpected.forEach((elem) {
      test('input: ${elem['input']}, language: ${elem['language']}, decodeMode: ${elem['decodeMode']}', () {
        var _actual = decodeNumeralwords(removeAccents(elem['input'].toString().toLowerCase()), elem['language'], elem['decodeMode']);
        var length = elem['expectedOutput'].length;
        for (int i = 0; i < length; i++) {
          expect(_actual[i].number, elem['expectedOutput'][i].number);
          expect(_actual[i].numWord, elem['expectedOutput'][i].numWord);
          expect(_actual[i].language, elem['expectedOutput'][i].language);
        }
      });
    });
  });

  group("NumeralWords.decodeNumeralwordsWordParts:", () {
    List<Map<String, dynamic>> _inputsToExpected = [
      {'input' : 'Susi wacht einsam während Vater und Mutter zweifelnd Sand sieben. Null Bock, denkt sich Jörg. Ich lasse fünfe grade sein und kegel lieber alle Neune!', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('8', 'acht', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('7', 'sieben', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('0', 'null', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('5', 'fuenf', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('9', 'neun', 'numeralwords_language_deu')]},

      {'input' : 'Hui trällert Balthasar. Null Bock auf nichts sondern den Sessel hüten um nicht die gute Laune zu verlieren. Und wahrlich, das ist ok.', 'language' : NumeralWordsLanguage.ALL, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('8', 'huit', 'numeralwords_language_fra'),
          NumeralWordsDecodeOutput('1', 'bal', 'numeralwords_language_vol'),
          NumeralWordsDecodeOutput('0', 'null', 'numeralwords_language_deu'),
          NumeralWordsDecodeOutput('', 'nul', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'nul', 'numeralwords_language_nld'),
          NumeralWordsDecodeOutput('', 'nul', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('9', 'ni', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'ni', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('1', 'en', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'en', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('', 'en', 'numeralwords_language_swe'),
          NumeralWordsDecodeOutput('6', 'ses', 'numeralwords_language_epo'),
          NumeralWordsDecodeOutput('10', 'ten', 'numeralwords_language_eng'),
          NumeralWordsDecodeOutput('1', 'en', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'en', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('', 'en', 'numeralwords_language_swe'),
          NumeralWordsDecodeOutput('1', 'um', 'numeralwords_language_por'),
          NumeralWordsDecodeOutput('9', 'ni', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'ni', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('2', 'tel', 'numeralwords_language_vol'),
          NumeralWordsDecodeOutput('1', 'un', 'numeralwords_language_fra'),
          NumeralWordsDecodeOutput('', 'une', 'numeralwords_language_fra'),
          NumeralWordsDecodeOutput('1', 'en', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'en', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('', 'en', 'numeralwords_language_swe'),
          NumeralWordsDecodeOutput('1', 'un', 'numeralwords_language_fra'),
          NumeralWordsDecodeOutput('2', 'dwa', 'numeralwords_language_pol'),
          NumeralWordsDecodeOutput('', 'dwa', 'numeralwords_language_rus'),
          NumeralWordsDecodeOutput('6', 'sis', 'numeralwords_language_fra'),
          NumeralWordsDecodeOutput('100', 'sto', 'numeralwords_language_pol'),
          NumeralWordsDecodeOutput('', 'sto', 'numeralwords_language_rus'),
          NumeralWordsDecodeOutput('2', 'to', 'numeralwords_language_dnk'),
          NumeralWordsDecodeOutput('', 'to', 'numeralwords_language_nor'),
          NumeralWordsDecodeOutput('8', 'ok', 'numeralwords_language_epo'),
        ]},

      {'input' : 'Gen Norden wand er sich. Zweiundfünfzig Tage lang wanderte er an der Elbe entlang. Als die Gegend immer flacher wurde, kam er ins Grübeln. Da er sich nicht auskannte, fragte er mal diesen und mal jenen Einheimischen, wo es in diesen Landen Berge geben konnte. Erst der fünfundzwanzigste verriet ihm, dass es weiter östlich ein paar Berge neben einem großen See gab. Erleichtert gab Rübezahl dem Mann als Dank vierhundertunddreißig Taler. Rübezahl wand sich also nach Osten und wanderte weiter durch dieses Land. Im Morgengrauen des dreizehnten Tages kam er an einer großen Siedlung vorbei, die an einer Wasserkreuzung mit drei Flussarmen lag und sieben Brücken hatte. Hinter der Siedlung, zwischen zwei der drei Flussarme, entdeckte er einen großen See. Dies musste der See sein, von dem ihm erzählt wurde. Als sich der Morgennebel lichtete, erblickte er hinter dem See eine Bergkette, bestehend aus 2 Gipfeln. Der eine war dreihundertfünfundneunzig und der andere gar vierhundertundfünfundsechzig Meter hoch. Für diese Gegend also zusammen gewaltige … Meter. Schnellen Schrittes erreichte er den Fuß der Bergkette. Er suchte eine Weile nach einem passenden Versteck für sein Goldenes Drachenei. An einer flachen, offenen Stelle wurde er eines Wegelagerers gewahr. Er belegte ihn mit einem tausendjährigen TAPIR-Fluch und verbannte ihn in ein enges Grab, bewacht von 7 schwarz-weißen. Unbemerkt konnte er nun ein geeignetes Objekt finden, um sein Goldenes Drachenei darin zu verstecken. Zur Absicherung baute er noch ein paar Hürden ein, und sicherte das Ganze noch mit einem Schloss.', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('52', 'zweiundfuenfzig', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('25', 'fuenfundzwanzig', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('430', 'vierhundertdreissig', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('13', 'dreizehn', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('3', 'drei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('7', 'sieben', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('3', 'drei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('2', '2', 'numeralwords_language_num'),
                            NumeralWordsDecodeOutput('395', 'dreihundertfuenfundneunzig', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('465', 'vierhundertfuenfundsechzig', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('7', '7', 'numeralwords_language_num')]},

      {'input' : 'einszwei', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu')]},
      {'input' : 'einszw', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'eins', 'numeralwords_language_deu')]},
      {'input' : 'abczweihundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'zwei', 'numeralwords_language_deu'),
                            NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'abchundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},
      {'input' : 'abceinhundert', 'language' : NumeralWordsLanguage.DEU, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundert', 'numeralwords_language_deu')]},

      {'input' : 'abchundred', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'abc hundreddef', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'abconehundreddef def', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng')]},
      {'input' : 'onehundredfiftydef', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'abcone hundred fiftydef', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('1', 'one', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng')]},
      {'input' : 'abca hundred and fifty-fivedef', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng')]},
      {'input' : 'abctwo hundred and fifty-fivedef', 'language' : NumeralWordsLanguage.ENG, 'decodeMode' : false,
        'expectedOutput' : [NumeralWordsDecodeOutput('2', 'two', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('100', 'hundred', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('50', 'fifty', 'numeralwords_language_eng'),
                            NumeralWordsDecodeOutput('5', 'five', 'numeralwords_language_eng')]},
    ];

    _inputsToExpected.forEach((elem) {
      test('input: ${elem['input']}, language: ${elem['language']}, decodeMode: ${elem['decodeMode']}', () {
        var _actual = decodeNumeralwords(removeAccents(elem['input'].toString().toLowerCase()), elem['language'], elem['decodeMode']);
        var length = elem['expectedOutput'].length;
        for (int i = 0; i < length; i++) {
          expect(_actual[i].number, elem['expectedOutput'][i].number);
          expect(_actual[i].numWord, elem['expectedOutput'][i].numWord);
          expect(_actual[i].language, elem['expectedOutput'][i].language);
        }
      });
    });
  });

  group("NumeralWords.decodeNumeralwordsEntireWordsVOL:", () {
    List<Map<String, dynamic>> _inputsToExpected = [
      {'input' : '', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('', '', 'numeralwords_language_empty')]},
      {'input' : 'fünfundzwanzig', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : []},

      {'input' : 'degbal', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('11', 'degbal', 'numeralwords_language_vol')]},
      {'input' : 'teldegtel', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('22', 'teldegtel', 'numeralwords_language_vol')]},
      {'input' : 'tumteldegkil', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('123', 'tumteldegkil', 'numeralwords_language_vol')]},
      {'input' : 'teldegfol', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('24', 'teldegfol', 'numeralwords_language_vol')]},
      {'input' : 'telmil kiltumfoldeglul', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('2345', 'telmilkiltumfoldeglul', 'numeralwords_language_vol')]},
      {'input' : 'tummäl', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('106', 'tummael', 'numeralwords_language_vol')]},
      {'input' : 'veldeg', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('70', 'veldeg', 'numeralwords_language_vol')]},
      {'input' : 'jölmil', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('8000', 'joelmil', 'numeralwords_language_vol')]},
      {'input' : 'teltum', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('200', 'teltum', 'numeralwords_language_vol')]},
      {'input' : 'degmil', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('10000', 'degmil', 'numeralwords_language_vol')]},
      {'input' : 'jöltumveldegmälmil kiltumteldegzül', 'language' : NumeralWordsLanguage.VOL, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('876329', 'joeltumveldegmaelmilkiltumteldegzuel', 'numeralwords_language_vol')]},
    ];

    _inputsToExpected.forEach((elem) {
      test('input: ${elem['input']}, language: ${elem['language']}, decodeMode: ${elem['decodeMode']}', () {
        var _actual = decodeNumeralwords(removeAccents(elem['input'].toString().toLowerCase()), elem['language'], elem['decodeMode']);
        var length = elem['expectedOutput'].length;
        for (int i = 0; i < length; i++) {
          expect(_actual[i].number, elem['expectedOutput'][i].number);
          expect(_actual[i].numWord, elem['expectedOutput'][i].numWord);
          expect(_actual[i].language, elem['expectedOutput'][i].language);
        }
      });
    });
  });

  group("NumeralWords.decodeNumeralwordsEntireWordsEPO:", () {
    List<Map<String, dynamic>> _inputsToExpected = [
      {'input' : '', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('', '', 'numeralwords_language_empty')]},
      {'input' : 'fünfundzwanzig', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : []},

      {'input' : 'dek du', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('12', 'dekdu', 'numeralwords_language_epo')]},
      {'input' : 'kvardek tri', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('43', 'kvardektri', 'numeralwords_language_epo')]},
      {'input' : 'naudek ok', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('98', 'naudekok', 'numeralwords_language_epo')]},
      {'input' : 'tricent', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('300', 'tricent', 'numeralwords_language_epo')]},
      {'input' : 'kvincent naudek ok', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('598', 'kvincentnaudekok', 'numeralwords_language_epo')]},
      {'input' : 'sep mil dudek kvar', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('7024', 'sepmildudekkvar', 'numeralwords_language_epo')]},
      {'input' : 'nau mil okcent dek kvin', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('9815', 'naumilokcentdekkvin', 'numeralwords_language_epo')]},
      {'input' : 'kvarcent tridek kvin mil sescent okdek nau', 'language' : NumeralWordsLanguage.EPO, 'decodeMode' : true,
        'expectedOutput' : [NumeralWordsDecodeOutput('435689', 'kvarcenttridekkvinmilsescentokdeknau', 'numeralwords_language_epo')]},
    ];

    _inputsToExpected.forEach((elem) {
      test('input: ${elem['input']}, language: ${elem['language']}, decodeMode: ${elem['decodeMode']}', () {
        var _actual = decodeNumeralwords(removeAccents(elem['input'].toString().toLowerCase()), elem['language'], elem['decodeMode']);
        var length = elem['expectedOutput'].length;
        for (int i = 0; i < length; i++) {
          expect(_actual[i].number, elem['expectedOutput'][i].number);
          expect(_actual[i].numWord, elem['expectedOutput'][i].numWord);
          expect(_actual[i].language, elem['expectedOutput'][i].language);
        }
      });
    });
  });
}