enum SubstitutionBreakerAlphabet { ENGLISH, GERMAN, DUTCH, SPANISH, POLISH, GREEK, FRENCH, RUSSIAN }

enum SubstitutionBreakerErrorCode {
  OK,
  MAX_ROUNDS_PARAMETER,
  CONSOLIDATE_PARAMETER,
  TEXT_TOO_SHORT,
  ALPHABET_TOO_LONG,
  WRONG_GENERATE_TEXT
}