part of 'gcwizard_scipt_test.dart';

// ignore: unused_element
List<Map<String, Object?>> _inputsGraphicToExpected = [
  {'code' : 'print STROKE(10)', 'expectedOutput' : '10'},
  {'code' : 'print STROKE(10.0)', 'expectedOutput' : '10'},
  {'code' : 'print CIRCLE(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print CIRCLE(10, 10, 20)', 'expectedOutput' : ''},
  {'code' : 'print CIRCLE(10.0, 10.0, 20.0)', 'expectedOutput' : ''},
  {'code' : 'print LINE(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print LINE(10, 10, 20, 20)', 'expectedOutput' : ''},
  {'code' : 'print LINE(10.0, 10.0, 20.0, 20.0)', 'expectedOutput' : ''},
  {'code' : 'print POINT(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print POINT(10.0, 10.0)', 'expectedOutput' : ''},
  {'code' : 'print ARC(10, 10, 10.0, 90, 180.0)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print ARC(10, 10, 10.0, 90, 180.0)', 'expectedOutput' : ''},
  {'code' : 'print PIE(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print PIE(10, 10, 10.0, 90, 180.0)', 'expectedOutput' : ''},
  {'code' : 'print COLOR(10.0)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print COLOR(10.0, 10.0, 10.0)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print COLOR(10, 10, 10)', 'expectedOutput' : ''},
  {'code' : 'print FILL("10")', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print FILL(10)', 'expectedOutput' : ''},
  {'code' : 'print FILL(10.0)', 'expectedOutput' : ''},
  {'code' : 'print TEXT("10", "10")', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print TEXT("10", 10, 10, 10)', 'expectedOutput' : ''},
  {'code' : 'print BOX(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print BOX(10, 10, 20, 20)', 'expectedOutput' : ''},
  {'code' : 'print OVAL(10)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print OVAL("10", 10, 20, 20)', 'expectedOutput' : '', 'error': 'gcwizard_script_syntax_error'},
  {'code' : 'print OVAL(10, 10, 20, 20)', 'expectedOutput' : ''},
];