/*
 * Copyright (C) 2003-2018 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

part of 'package:gc_wizard/tools/coords/format_converter/logic/external_libs/mapcode/mapcode.dart';

const isofullname = [
"Vatican (Holy See) (_ City State)",
"Monaco (Principality of _)",
"Gibraltar",
"Tokelau",
"Cocos Islands (Keeling Islands)",
"Saint-Barthelemy (Collectivity of _)",
"Nauru (Republic of _)",
"Tuvalu",
"Macau (Aomen)",
"Sint Maarten",
"Saint Martin (Collectivity of _)",
"Norfolk and Philip Island (Philip Island) (Norfolk Island)",
"Pitcairn Islands (Pitcairn, Henderson, Ducie and Oeno Islands)",
"Bouvet Island",
"Bermuda (Somers Isles)",
"British Indian Ocean Territory",
"San Marino (Republic of _)",
"Guernsey (Bailiwick of _)",
"Anguilla",
"Montserrat",
"Jersey (Bailiwick of _)",
"Christmas Island",
"Wallis and Futuna (Futuna) (Wallis) (Collectivity of the _ Islands)",
"British Virgin Islands (Virgin Islands, British)",
"Liechtenstein (Principality of _)",
"Aruba",
"Marshall Islands (Republic of the _)",
"American Samoa (Samoa, American)",
"Cook Islands",
"Saint Pierre and Miquelon (Miquelon) (Saint Pierre) (Collectivity of _)",
"Niue",
"Saint Kitts and Nevis (Nevis) (Saint Kitts) (Federation of _)",
"Cayman islands",
"Bonaire, St Eustasuis and Saba (Bonaire) (Saba) (St Eustasius)",
"Maldives (Republic of _)",
"Saint Helena, Ascension and Tristan da Cunha (Saint Helena) (Ascension) (Tristan da Cunha)",
"Malta (Republic of _)",
"Grenada",
"Virgin Islands of the United States (US Virgin Islands) (American Virgin Islands)",
"Mayotte (Maore)",
"Svalbard and Jan Mayen (Svalbard) (Jan Mayen) (Spitsbergen)",
"Saint Vincent and the Grenadines (Saint Vincent) (Grenadines)",
"Heard Island and McDonald Islands (Heard Island) (McDonald Islands)",
"Barbados",
"Antigua and Barbuda (Antigua) (Barbuda)",
"Curacao",
"Seychelles (Republic of _)",
"Palau (Republic of _)",
"Northern Mariana Islands (Commonwealth of the _)",
"Andorra (Principality of _) (Principality of the Valleys of _)",
"Guam",
"Isle of Mann (Mann)",
"Saint Lucia",
"Micronesia (Federated States of Micronesia)",
"Singapore (Republic of _)",
"Tonga (Kingdom of _)",
"Dominica (Commonwealth of _)",
"Bahrain (Kingdom of _)",
"Kiribati (Republic of _)",
"Turks and Caicos Islands (Turks Islands) (Caicos Islands)",
"Sao Tome and Principe (Sao Tome) (Principe) (Democratic Republic of _)",
"Hong Kong (Xianggang)",
"Martinique",
"Faroe Islands",
"Guadeloupe",
"Comoros (Union of the _)",
"Mauritius (Republic of _)",
"Reunion",
"Luxembourg (Grand Duchy of _)",
"Samoa (Independent State of _)",
"South Georgia and the South Sandwich Islands (South Georgia) (South Sandwich Islands)",
"French Polynesia (Collectivity of _)",
"Cape Verde (Cabo Verde) (Republic of Cabo Verde)",
"Trinidad and Tobago (Republic of _) (Trinidad) (Tobago)",
"Brunei (Nation of _, the Abode of Peace)",
"French Southern and Antarctic Lands",
"Puerto Rico (Commonwealth of _)",
"Cyprus (Republic of _)",
"Lebanon (Lebanese Republic)",
"Jamaica",
"Gambia (The Gambia) (Republic of the _)",
"Qatar (State of _)",
"Falkland Islands (The Falklands)",
"Vanuatu (Republic of _)",
"Montenegro",
"Bahamas (Commonwealth of the _)",
"Timor-Leste (Democratic Republic of _) (East Timor)",
"Swaziland (Kingdom of _)",
"Kuwait (State of _)",
"Fiji (Republic of _)",
"New Caledonia",
"Slovenia (Republic of _)",
"Israel (State of _)",
"Palestinian territories (State of Palestine)",
"El Salvador (Republic of _)",
"Belize",
"Djibouti (Republic of _)",
"Macedonia (Republic of _) (FYROM) (Former Yugoslav Republic of Macedonia)",
"Rwanda (Republic of _)",
"Haiti (Republic of _)",
"Burundi (Republic of _)",
"Equatorial Guinea (Republic of _)",
"Albania (Republic of _)",
"Solomon Islands",
"Armenia (Republic of _)",
"Lesotho (Kingdom of _)",
"Belgium (Kingdom of _)",
"Moldova (Republic of _)",
"Guinea-Bissau (Republic of _)",
"Taiwan (Republic of China)",
"Bhutan (Kingdom of _)",
"Switzerland (Swiss Confederation)",
"Netherlands (The Netherlands) (Kingdom of the _)",
"Denmark (Kingdom of _)",
"Estonia (Republic of _)",
"Dominican Republic",
"Slovakia (Slovak Republic)",
"Costa Rica (Republic of _)",
"Bosnia and Herzegovina",
"Croatia (Republic of _)",
"Togo (Togolese Republic)",
"Latvia (Republic of _)",
"Lithuania (Republic of _)",
"Sri Lanka (Democratic Socialist Republic of _)",
"Georgia",
"Ireland (Republic of _)",
"Sierra Leone (Republic of _)",
"Panama (Republic of _)",
"Czech Republic",
"French Guiana (Guiana)",
"United Arab Emirates (Emirates)",
"Austria (Republic of _)",
"Azerbaijan (Republic of _)",
"Serbia (Republic of _)",
"Jordan (Hashemite Kingdom of _) (Kingdom of _)",
"Portugal (Portuguese Republic)",
"Hungary (Republic of _)",
"South Korea (Republic of Korea) (Korea, South)",
"Iceland",
"Guatemala (Republic of _)",
"Cuba (Republic of _)",
"Bulgaria (Republic of _)",
"Liberia (Republic of _)",
"Honduras (Republic of _)",
"Benin (Republic of _)",
"Eritrea (State of _)",
"Malawi (Republic of _)",
"North Korea (Democratic People's Republic of Korea) (Korea, North)",
"Nicaragua (Republic of _)",
"Greece (Hellenic Republic) (Hellas)",
"Tajikistan (Republic of _)",
"Bangladesh (People's Republic of _)",
"Nepal (Federal Democratic Republic of _)",
"Tunisia (Tunisian Republic) (Republic of _)",
"Suriname (Republic of _)",
"Uruguay (Eastern Republic of _)",
"Cambodia (Kingdom of _)",
"Syria (Syrian Arab Republic)",
"Senegal (Republic of _)",
"Kyrgyzstan (Kyrgyz Republic)",
"Belarus (Republic of _)",
"Guyana (Co-operative Republic of _)",
"Laos (Lao People's Democratic Republic)",
"Romania",
"Ghana (Republic of _)",
"Uganda (Republic of _)",
"United Kingdom (Scotland) (Great Britain) (England) (Northern Ireland) (Ireland, Northern) (Britain) (United Kingdom of Great Britain and Northern Ireland)",
"Guinea (Republic of _) (Guinea-Conakry)",
"Ecuador (Republic of _)",
"Western Sahara (Sahrawi Arab Democratic Republic)",
"Gabon (Gabonese Republic)",
"New Zealand",
"Burkina Faso",
"Philippines (Republic of the _)",
"Italy (Italian Republic)",
"Oman (Sultanate of _)",
"Poland (Republic of _)",
"Ivory Coast (Cote d'Ivoire) (Republic of Cote d'Ivoire)",
"Norway (Kingdom of _)",
"Malaysia",
"Vietnam (Socialist Republic of _)",
"Finland (Republic of _)",
"Congo-Brazzaville (West Congo) (Republic of the Congo)",
"Germany (Federal Republic of _)",
"Japan",
"Zimbabwe (Republic of _)",
"Paraguay (Republic of _)",
"Iraq (Republic of _)",
"Morocco (Kingdom of _)",
"Uzbekistan (Republic of _)",
"Sweden (Kingdom of _)",
"Papua New Guinea (Independent State of _)",
"Cameroon (Republic of _)",
"Turkmenistan",
"Spain (Kingdom of _)",
"Thailand (Kingdom of _)",
"Yemen (Republic of _)",
"France (French Republic)",
"Aaland Islands",
"Kenya (Republic of _)",
"Botswana (Republic of _)",
"Madagascar (Republic of _)",
"Ukraine",
"South Sudan (Republic of _)",
"Central African Republic",
"Somalia (Federal Republic of _)",
"Afghanistan (Islamic Republic of _)",
"Myanmar (Republic of the Union of _) (Burma)",
"Zambia (Republic of _)",
"Chile (Republic of _)",
"Turkey (Republic of _)",
"Pakistan (Islamic Republic of _)",
"Mozambique (Republic of _)",
"Namibia (Republic of _)",
"Venezuela (Bolivarian Republic of _)",
"Nigeria (Federal Republic of _)",
"Tanzania (United Republic of _)",
"Egypt (Arab Republic of _)",
"Mauritania (Islamic Republic of _)",
"Bolivia (Plurinational State of _)",
"Ethiopia (Federal Democratic Republic of _)",
"Colombia (Republic of _)",
"South Africa (Republic of _)",
"Mali (Republic of _)",
"Angola (Republic of _)",
"Niger (Republic of _)",
"Chad (Republic of _)",
"Peru (Republic of _)",
"Mongolia",
"Iran (Persia) (Islamic Republic of _)",
"Libya",
"Sudan (Republic of the _)",
"Indonesia (Republic of _)",
"Federal District",
"Tlaxcala",
"Morelos",
"Aguascalientes",
"Colima",
"Queretaro",
"Hidalgo",
"Mexico State",
"Tabasco",
"Nayarit",
"Guanajuato",
"Puebla",
"Yucatan",
"Quintana Roo",
"Sinaloa",
"Campeche",
"Michoacan",
"San Luis Potosi",
"Guerrero",
"Nuevo Leon (New Leon)",
"Baja California",
"Veracruz",
"Chiapas",
"Baja California Sur",
"Zacatecas",
"Jalisco",
"Tamaulipas",
"Oaxaca",
"Durango",
"Coahuila",
"Sonora",
"Chihuahua",
"Greenland",
"Saudi Arabia (Kingdom of _)",
"Congo-Kinshasa (Democratic Republic of the Congo) (East Congo)",
"Algeria (People's Democratic Republic of _)",
"Kazakhstan (Republic of _)",
"Argentina (Argentine Republic)",
"Daman and Diu",
"Dadra and Nagar Haveli (Dadra) (Nagar Haveli)",
"Chandigarh",
"Andaman and Nicobar (Andaman) (Nicobar)",
"Lakshadweep",
"Delhi (National Capital Territory of _)",
"Meghalaya",
"Nagaland",
"Manipur",
"Tripura",
"Mizoram",
"Sikkim",
"Punjab",
"Haryana",
"Arunachal Pradesh",
"Assam",
"Bihar",
"Uttarakhand",
"Goa",
"Kerala",
"Tamil Nadu",
"Himachal Pradesh",
"Jammu and Kashmir (Jammu) (Kashmir)",
"Chhattisgarh",
"Jharkhand",
"Karnataka",
"Rajasthan",
"Odisha (Orissa)",
"Gujarat",
"West Bengal",
"Madhya Pradesh",
"Telangana",
"Andhra Pradesh",
"Maharashtra",
"Uttar Pradesh",
"Puducherry",
"New South Wales",
"Australian Capital Territory",
"Jervis Bay Territory",
"Northern Territory",
"South Australia",
"Tasmania",
"Victoria",
"Western Australia",
"Queensland",
"Distrito Federal",
"Sergipe",
"Alagoas",
"Rio de Janeiro",
"Espirito Santo",
"Rio Grande do Norte",
"Paraiba",
"Santa Catarina",
"Pernambuco",
"Amapa",
"Ceara",
"Acre",
"Parana",
"Roraima",
"Rondonia",
"Sao Paulo",
"Piaui",
"Tocantins",
"Rio Grande do Sul",
"Maranhao",
"Goias",
"Mato Grosso do Sul",
"Bahia",
"Minas Gerais",
"Mato Grosso",
"Para",
"Amazonas",
"District of Columbia (Washington, D.C.)",
"Rhode Island",
"Delaware",
"Connecticut",
"New Jersey",
"New Hampshire",
"Vermont",
"Massachusetts (Commonwealth of _)",
"Hawaii",
"Maryland",
"West Virginia",
"South Carolina",
"Maine",
"Indiana",
"Kentucky (Commonwealth of _)",
"Tennessee",
"Virginia (Commonwealth of _)",
"Ohio",
"Pennsylvania (Commonwealth of _)",
"Mississippi",
"Louisiana",
"Alabama",
"Arkansas",
"North Carolina",
"New York",
"Iowa",
"Illinois",
"Georgia",
"Wisconsin",
"Florida",
"Missouri",
"Oklahoma",
"North Dakota",
"Washington",
"South Dakota",
"Nebraska",
"Kansas",
"Idaho",
"Utah",
"Minnesota",
"Michigan",
"Wyoming",
"Oregon",
"Colorado",
"Nevada",
"Arizona",
"New Mexico",
"Montana",
"California",
"Texas",
"Alaska",
"British Columbia",
"Alberta",
"Ontario",
"Quebec",
"Saskatchewan",
"Manitoba",
"Newfoundland and Labrador (Newfoundland) (Labrador)",
"New Brunswick",
"Nova Scotia",
"Prince Edward Island",
"Yukon",
"Northwest Territories",
"Nunavut",
"India (Republic of _)",
"Australia (Commonwealth of _)",
"Brazil (Federative Republic of _)",
"USA (United States of America) (America)",
"Mexico (United Mexican States)",
"Moscow",
"Saint Petersburg",
"Kaliningrad Oblast",
"Ingushetia",
"Adygea Republic",
"North Ossetia-Alania Republic",
"Kabardino-Balkar Republic",
"Karachay-Cherkess Republic",
"Chechen Republic (Chechnya) (Ichkeria)",
"Chuvash Republic",
"Ivanovo Oblast",
"Lipetsk Oblast",
"Oryol Oblast",
"Tula Oblast",
"Belgorod Oblast",
"Vladimir Oblast",
"Kursk Oblast",
"Kaluga Oblast",
"Tambov Oblast",
"Bryansk Oblast",
"Yaroslavl Oblast",
"Ryazan Oblast",
"Astrakhan Oblast",
"Moscow Oblast",
"Smolensk Oblast",
"Dagestan Republic",
"Voronezh Oblast",
"Novgorod Oblast",
"Pskov Oblast",
"Kostroma Oblast",
"Stavropol Krai",
"Krasnodar Krai",
"Kalmykia Republic",
"Tver Oblast",
"Leningrad Oblast",
"Rostov Oblast",
"Volgograd Oblast",
"Vologda Oblast",
"Murmansk Oblast",
"Karelia Republic",
"Nenets Autonomous Okrug",
"Komi Republic",
"Arkhangelsk Oblast",
"Mordovia Republic",
"Nizhny Novgorod Oblast",
"Penza Oblast",
"Kirov Oblast",
"Mari El Republic",
"Orenburg Oblast",
"Ulyanovsk Oblast",
"Perm Krai",
"Bashkortostan Republic",
"Udmurt Republic",
"Tatarstan Republic",
"Samara Oblast",
"Saratov Oblast",
"Yamalo-Nenets",
"Khanty-Mansi",
"Sverdlovsk Oblast",
"Tyumen Oblast",
"Kurgan Oblast",
"Chelyabinsk Oblast",
"Buryatia Republic",
"Zabaykalsky Krai",
"Irkutsk Oblast",
"Novosibirsk Oblast",
"Tomsk Oblast",
"Omsk Oblast",
"Khakassia Republic",
"Kemerovo Oblast",
"Altai Republic",
"Altai Krai",
"Tuva Republic",
"Krasnoyarsk Krai",
"Magadan Oblast",
"Chukotka Okrug",
"Kamchatka Krai",
"Sakhalin Oblast",
"Primorsky Krai",
"Jewish Autonomous Oblast",
"Khabarovsk Krai",
"Amur Oblast",
"Sakha Republic (Yakutia Republic)",
"Canada",
"Russia (Russian Federation)",
"Shanghai Municipality",
"Tianjin Municipality",
"Beijing Municipality",
"Hainan Province",
"Ningxia Hui Autonomous Region",
"Chongqing Municipality",
"Zhejiang Province",
"Jiangsu Province",
"Fujian Province",
"Anhui Province",
"Liaoning Province",
"Shandong Province",
"Shanxi Province",
"Jiangxi Province",
"Henan Province",
"Guizhou Province",
"Guangdong Province",
"Hubei Province",
"Jilin Province",
"Hebei Province (Yanzhao Province)",
"Shaanxi Province",
"Nei Mongol Autonomous Region (Inner Mongolia)",
"Heilongjiang Province",
"Hunan Province",
"Guangxi Zhuang Autonomous Region",
"Sichuan Province",
"Yunnan Province",
"Xizang Autonomous Region (Tibet)",
"Gansu Province",
"Qinghai Province (Tsinghai Province)",
"Xinjiang Uyghur Autonomous Region",
"China (People's Republic of _)",
"United States Minor Outlying Islands",
"Clipperton Island",
"Antarctica",
"International (Worldwide) (Earth)",
"?"];

