// https://en.wikipedia.org/wiki/IAU_designated_constellations
// https://de.wikipedia.org/wiki/Liste_der_Sternbilder
// https://www.iau.org/public/themes/constellations/

part of 'package:gc_wizard/tools/science_and_technology/astronomy/iau_constellation/logic/iau_constellation.dart';

enum IAU_CONSTELLATION_SORT { CONSTELLATION, NAME, STAR, AREA, VISIBILIY, MAGNITUDO }

Map<IAU_CONSTELLATION_SORT, String> IAU_SORT = {
  IAU_CONSTELLATION_SORT.CONSTELLATION : 'iau_constellation_iauname',
  IAU_CONSTELLATION_SORT.NAME : 'iau_constellation_name',
  IAU_CONSTELLATION_SORT.STAR : 'iau_constellation_star',
  IAU_CONSTELLATION_SORT.AREA : 'iau_constellation_area',
  IAU_CONSTELLATION_SORT.VISIBILIY : 'iau_constellation_visibility',
  IAU_CONSTELLATION_SORT.MAGNITUDO : 'iau_constellation_magnitudo',
};

Map<String, Map<String, String>> IAU_CONSTELLATION = {
  "Andromeda": {
    "constellation": "Andromeda",
    "IAU": "And",
    "NASA": "Andr",
    "brightest_star": "Sirrah",
    "name": "iau_constellation_andromeda",
    "position": "N",
    "area": "722.278",
    "visibility": "90° N - 37° S",
    "magnitudo": "2.07"
  },
  "Antlia": {
    "constellation": "Antlia",
    "IAU": "Ant",
    "NASA": "Antl",
    "brightest_star": "α Antliae",
    "name": "iau_constellation_antlia",
    "position": "S",
    "area": "238.901",
    "visibility": "50° N - 90° S",
    "magnitudo": "4.22"
  },
  "Apus": {
    "constellation": "Apus",
    "IAU": "Aps",
    "NASA": "Apus",
    "brightest_star": "α Apodis",
    "name": "iau_constellation_apus",
    "position": "S",
    "area": "206.327",
    "visibility": "07° N - 90° S",
    "magnitudo": "3.83"
  },
  "Aquarius": {
    "constellation": "Aquarius",
    "IAU": "Aqr",
    "NASA": "Aqar",
    "brightest_star": "Sadalsuud",
    "name": "iau_constellation_aquarius",
    "position": "S n",
    "area": "979.854",
    "visibility": "65° N - 87° S",
    "magnitudo": "2.9"
  },
  "Aquila": {
    "constellation": "Aquila",
    "IAU": "Aql",
    "NASA": "Aqil",
    "brightest_star": "Altair",
    "name": "iau_constellation_aquila",
    "position": "N S",
    "area": "652.473",
    "visibility": "78° N - 71° S",
    "magnitudo": "0.76"
  },
  "Ara": {
    "constellation": "Ara",
    "IAU": "Ara",
    "NASA": "Arae",
    "brightest_star": "β Arae",
    "name": "iau_constellation_ara",
    "position": "S",
    "area": "237.057",
    "visibility": "25° N - 90° S",
    "magnitudo": "2.85"
  },
  "Aries": {
    "constellation": "Aries",
    "IAU": "Ari",
    "NASA": "Arie",
    "brightest_star": "Hamal",
    "name": "iau_constellation_aries",
    "position": "N",
    "area": "441.395",
    "visibility": "90° N - 59° S",
    "magnitudo": "2.01"
  },
  "Auriga": {
    "constellation": "Auriga",
    "IAU": "Aur",
    "NASA": "Auri",
    "brightest_star": "Capella",
    "name": "iau_constellation_auriga",
    "position": "N",
    "area": "657.438",
    "visibility": "90° N - 34° S",
    "magnitudo": "0.03"
  },
  "Boötes": {
    "constellation": "Boötes",
    "IAU": "Boo",
    "NASA": "Boot",
    "brightest_star": "Arcturus",
    "name": "iau_constellation_bootes",
    "position": "N",
    "area": "906.831",
    "visibility": "90° N - 50° S",
    "magnitudo": "−0,05"
  },
  "Caelum": {
    "constellation": "Caelum",
    "IAU": "Cae",
    "NASA": "Cael",
    "brightest_star": "α Caeli",
    "name": "iau_constellation_caelum",
    "position": "S",
    "area": "124.865",
    "visibility": "41° N - 90° S",
    "magnitudo": "4.45"
  },
  "Camelopardalis": {
    "constellation": "Camelopardalis",
    "IAU": "Cam",
    "NASA": "Caml",
    "brightest_star": "β Camelopardalis",
    "name": "iau_constellation_camelopardalis",
    "position": "N",
    "area": "756.828",
    "visibility": "90° N - 37° S",
    "magnitudo": "4.03"
  },
  "Cancer": {
    "constellation": "Cancer",
    "IAU": "Cnc",
    "NASA": "Canc",
    "brightest_star": "Tarf",
    "name": "iau_constellation_cancer",
    "position": "N",
    "area": "505.872",
    "visibility": "90° N - 60° S",
    "magnitudo": "3.52"
  },
  "Canes Venatici": {
    "constellation": "Canes Venatici",
    "IAU": "CVn",
    "NASA": "CVen",
    "brightest_star": "Cor Caroli",
    "name": "iau_constellation_canes_venatici",
    "position": "N",
    "area": "465.194",
    "visibility": "90° N - 38° S",
    "magnitudo": "2.8"
  },
  "Canis Major": {
    "constellation": "Canis Major",
    "IAU": "CMa",
    "NASA": "CMaj",
    "brightest_star": "Sirius",
    "name": "iau_constellation_canis_major",
    "position": "S",
    "area": "380.118",
    "visibility": "57° N - 90° S",
    "magnitudo": "−1,44"
  },
  "Canis Minor": {
    "constellation": "Canis Minor",
    "IAU": "CMi",
    "NASA": "CMin",
    "brightest_star": "Procyon",
    "name": "iau_constellation_canis_minor",
    "position": "N s",
    "area": "183.367",
    "visibility": "89° N - 77° S",
    "magnitudo": "0.37"
  },
  "Capricornus": {
    "constellation": "Capricornus",
    "IAU": "Cap",
    "NASA": "Capr",
    "brightest_star": "Deneb Algedi",
    "name": "iau_constellation_capricornus",
    "position": "S",
    "area": "413.947",
    "visibility": "62° N - 90° S",
    "magnitudo": "2.73"
  },
  "Carina": {
    "constellation": "Carina",
    "IAU": "Car",
    "NASA": "Cari",
    "brightest_star": "Canopus",
    "name": "iau_constellation_carina",
    "position": "S",
    "area": "494.184",
    "visibility": "14° N - 90° S",
    "magnitudo": "−0,62"
  },
  "Cassiopeia": {
    "constellation": "Cassiopeia",
    "IAU": "Cas",
    "NASA": "Cass",
    "brightest_star": "Schedar",
    "name": "iau_constellation_cassiopeia",
    "position": "N",
    "area": "598.407",
    "visibility": "90° N - 12° S",
    "magnitudo": "2.23"
  },
  "Centaurus": {
    "constellation": "Centaurus",
    "IAU": "Cen",
    "NASA": "Cent",
    "brightest_star": "Rigil Kentaurus",
    "name": "iau_constellation_centaurus",
    "position": "S",
    "area": "1,060.42",
    "visibility": "25° N - 90° S",
    "magnitudo": "−0,01"
  },
  "Cepheus": {
    "constellation": "Cepheus",
    "IAU": "Cep",
    "NASA": "Ceph",
    "brightest_star": "Alderamin",
    "name": "iau_constellation_cepheus",
    "position": "N",
    "area": "587.787",
    "visibility": "90° N - 10° S",
    "magnitudo": "2.45"
  },
  "Cetus": {
    "constellation": "Cetus",
    "IAU": "Cet",
    "NASA": "Ceti",
    "brightest_star": "Diphda",
    "name": "iau_constellation_cetus",
    "position": "S n",
    "area": "1,231.41",
    "visibility": "70° N - 90° S",
    "magnitudo": "2.04"
  },
  "Chamaeleon": {
    "constellation": "Chamaeleon",
    "IAU": "Cha",
    "NASA": "Cham",
    "brightest_star": "α Chamaeleontis",
    "name": "iau_constellation_chamaeleon",
    "position": "S",
    "area": "131.592",
    "visibility": "07° N - 90° S",
    "magnitudo": "4.05"
  },
  "Circinus": {
    "constellation": "Circinus",
    "IAU": "Cir",
    "NASA": "Circ",
    "brightest_star": "α Circini",
    "name": "iau_constellation_circinus",
    "position": "S",
    "area": "93.353",
    "visibility": "20° N - 90° S",
    "magnitudo": "3.19"
  },
  "Columba": {
    "constellation": "Columba",
    "IAU": "Col",
    "NASA": "Colm",
    "brightest_star": "Phact",
    "name": "iau_constellation_columba",
    "position": "S",
    "area": "270.184",
    "visibility": "41° N - 90° S",
    "magnitudo": "2.65"
  },
  "Coma Berenices": {
    "constellation": "Coma Berenices",
    "IAU": "Com",
    "NASA": "Coma",
    "brightest_star": "β Comae Berenices",
    "name": "iau_constellation_coma_berenices",
    "position": "N",
    "area": "386.475",
    "visibility": "90° N - 56° S",
    "magnitudo": "4.26"
  },
  "Corona Australis": {
    "constellation": "Corona Australis",
    "IAU": "CrA",
    "NASA": "CorA",
    "brightest_star": "Meridiana",
    "name": "iau_constellation_corona_australis",
    "position": "S",
    "area": "127.696",
    "visibility": "44° N - 90° S",
    "magnitudo": "4.1"
  },
  "Corona Borealis": {
    "constellation": "Corona Borealis",
    "IAU": "CrB",
    "NASA": "CorB",
    "brightest_star": "Alphecca",
    "name": "iau_constellation_corona_borealis",
    "position": "N",
    "area": "178.71",
    "visibility": "90° N - 50° S",
    "magnitudo": "2.21"
  },
  "Corvus": {
    "constellation": "Corvus",
    "IAU": "Crv",
    "NASA": "Corv",
    "brightest_star": "Gienah",
    "name": "iau_constellation_corvus",
    "position": "S",
    "area": "183.801",
    "visibility": "65° N - 90° S",
    "magnitudo": "2.59"
  },
  "Crater": {
    "constellation": "Crater",
    "IAU": "Crt",
    "NASA": "Crat",
    "brightest_star": "δ Crateris",
    "name": "iau_constellation_crater",
    "position": "S",
    "area": "282.398",
    "visibility": "65° N - 90° S",
    "magnitudo": "3.56"
  },
  "Crux": {
    "constellation": "Crux",
    "IAU": "Cru",
    "NASA": "Cruc",
    "brightest_star": "Acrux",
    "name": "iau_constellation_crux",
    "position": "S",
    "area": "68.447",
    "visibility": "25° N - 90° S",
    "magnitudo": "0.77"
  },
  "Cygnus": {
    "constellation": "Cygnus",
    "IAU": "Cyg",
    "NASA": "Cygn",
    "brightest_star": "Deneb",
    "name": "iau_constellation_cygnus",
    "position": "N",
    "area": "803.983",
    "visibility": "90° N - 29° S",
    "magnitudo": "1.25"
  },
  "Delphinus": {
    "constellation": "Delphinus",
    "IAU": "Del",
    "NASA": "Dlph",
    "brightest_star": "Rotanev",
    "name": "iau_constellation_delphinus",
    "position": "N",
    "area": "188.549",
    "visibility": "90° N - 70° S",
    "magnitudo": "3.63"
  },
  "Dorado": {
    "constellation": "Dorado",
    "IAU": "Dor",
    "NASA": "Dora",
    "brightest_star": "α Doradus",
    "name": "iau_constellation_dorado",
    "position": "S",
    "area": "179.173",
    "visibility": "20° N - 90° S",
    "magnitudo": "3.3"
  },
  "Draco": {
    "constellation": "Draco",
    "IAU": "Dra",
    "NASA": "Drac",
    "brightest_star": "Eltanin",
    "name": "iau_constellation_draco",
    "position": "N",
    "area": "1,082.95",
    "visibility": "90° N - 15° S",
    "magnitudo": "2.24"
  },
  "Equuleus": {
    "constellation": "Equuleus",
    "IAU": "Equ",
    "NASA": "Equl",
    "brightest_star": "Kitalpha",
    "name": "iau_constellation_equuleus",
    "position": "N",
    "area": "71.641",
    "visibility": "90° N - 77° S",
    "magnitudo": "3.92"
  },
  "Eridanus": {
    "constellation": "Eridanus",
    "IAU": "Eri",
    "NASA": "Erid",
    "brightest_star": "Achernar",
    "name": "iau_constellation_eridanus",
    "position": "S n",
    "area": "1,137.92",
    "visibility": "32° N - 89° S",
    "magnitudo": "0.5"
  },
  "Fornax": {
    "constellation": "Fornax",
    "IAU": "For",
    "NASA": "Forn",
    "brightest_star": "Dalim",
    "name": "iau_constellation_fornax",
    "position": "S",
    "area": "397.502",
    "visibility": "50° N - 90° S",
    "magnitudo": "3.87"
  },
  "Gemini": {
    "constellation": "Gemini",
    "IAU": "Gem",
    "NASA": "Gemi",
    "brightest_star": "Pollux",
    "name": "iau_constellation_gemini",
    "position": "N",
    "area": "513.761",
    "visibility": "90° N - 60° S",
    "magnitudo": "1.16"
  },
  "Grus": {
    "constellation": "Grus",
    "IAU": "Gru",
    "NASA": "Grus",
    "brightest_star": "Alnair",
    "name": "iau_constellation_grus",
    "position": "S",
    "area": "365.513",
    "visibility": "35° N - 90° S",
    "magnitudo": "1.74"
  },
  "Hercules": {
    "constellation": "Hercules",
    "IAU": "Her",
    "NASA": "Herc",
    "brightest_star": "Kornephoros",
    "name": "iau_constellation_hercules",
    "position": "N",
    "area": "1,225.15",
    "visibility": "90° N - 39° S",
    "magnitudo": "2.78"
  },
  "Horologium": {
    "constellation": "Horologium",
    "IAU": "Hor",
    "NASA": "Horo",
    "brightest_star": "α Horologii",
    "name": "iau_constellation_horologium",
    "position": "S",
    "area": "248.885",
    "visibility": "20° N - 90° S",
    "magnitudo": "3.85"
  },
  "Hydra": {
    "constellation": "Hydra",
    "IAU": "Hya",
    "NASA": "Hyda",
    "brightest_star": "Alphard",
    "name": "iau_constellation_hydra",
    "position": "S n",
    "area": "1,302.84",
    "visibility": "55° N - 83° S",
    "magnitudo": "1.98"
  },
  "Hydrus": {
    "constellation": "Hydrus",
    "IAU": "Hyi",
    "NASA": "Hydi",
    "brightest_star": "β Hydri",
    "name": "iau_constellation_hydrus",
    "position": "S",
    "area": "243.035",
    "visibility": "08° N - 90° S",
    "magnitudo": "2.8"
  },
  "Indus": {
    "constellation": "Indus",
    "IAU": "Ind",
    "NASA": "Indi",
    "brightest_star": "α Indi",
    "name": "iau_constellation_indus",
    "position": "S",
    "area": "294.006",
    "visibility": "16° N - 90° S",
    "magnitudo": "3.11"
  },
  "Lacerta": {
    "constellation": "Lacerta",
    "IAU": "Lac",
    "NASA": "Lacr",
    "brightest_star": "α Lacertae",
    "name": "iau_constellation_lacerta",
    "position": "N",
    "area": "200.688",
    "visibility": "90° N - 40° S",
    "magnitudo": "3.77"
  },
  "Leo": {
    "constellation": "Leo",
    "IAU": "Leo",
    "NASA": "Leon",
    "brightest_star": "Regulus",
    "name": "iau_constellation_leo",
    "position": "N s",
    "area": "946.964",
    "visibility": "83° N - 57° S",
    "magnitudo": "1.36"
  },
  "Leo Minor": {
    "constellation": "Leo Minor",
    "IAU": "LMi",
    "NASA": "LMin",
    "brightest_star": "Praecipua",
    "name": "iau_constellation_leo_minor",
    "position": "N",
    "area": "231.956",
    "visibility": "90° N - 48° S",
    "magnitudo": "3.83"
  },
  "Lepus": {
    "constellation": "Lepus",
    "IAU": "Lep",
    "NASA": "Leps",
    "brightest_star": "Arneb",
    "name": "iau_constellation_lepus",
    "position": "S",
    "area": "290.291",
    "visibility": "60° N - 90° S",
    "magnitudo": "2.58"
  },
  "Libra": {
    "constellation": "Libra",
    "IAU": "Lib",
    "NASA": "Libr",
    "brightest_star": "Zubeneschamali",
    "name": "iau_constellation_libra",
    "position": "S",
    "area": "538.052",
    "visibility": "60° N - 90° S",
    "magnitudo": "2.61"
  },
  "Lupus": {
    "constellation": "Lupus",
    "IAU": "Lup",
    "NASA": "Lupi",
    "brightest_star": "α Lupi",
    "name": "iau_constellation_lupus",
    "position": "S",
    "area": "333.683",
    "visibility": "35° N - 90° S",
    "magnitudo": "2.29"
  },
  "Lynx": {
    "constellation": "Lynx",
    "IAU": "Lyn",
    "NASA": "Lync",
    "brightest_star": "α Lyncis",
    "name": "iau_constellation_lynx",
    "position": "N",
    "area": "545.386",
    "visibility": "90° N - 35° S",
    "magnitudo": "3.13"
  },
  "Lyra": {
    "constellation": "Lyra",
    "IAU": "Lyr",
    "NASA": "Lyra",
    "brightest_star": "Vega",
    "name": "iau_constellation_lyra",
    "position": "N",
    "area": "286.476",
    "visibility": "90° N - 29° S",
    "magnitudo": "0.03"
  },
  "Mensa": {
    "constellation": "Mensa",
    "IAU": "Men",
    "NASA": "Mens",
    "brightest_star": "α Mensae",
    "name": "iau_constellation_mensa",
    "position": "S",
    "area": "153.484",
    "visibility": "05° N - 90° S",
    "magnitudo": "5.09"
  },
  "Microscopium": {
    "constellation": "Microscopium",
    "IAU": "Mic",
    "NASA": "Micr",
    "brightest_star": "γ Microscopii",
    "name": "iau_constellation_microscopium",
    "position": "S",
    "area": "209.513",
    "visibility": "45° N - 90° S",
    "magnitudo": "4.67"
  },
  "Monoceros": {
    "constellation": "Monoceros",
    "IAU": "Mon",
    "NASA": "Mono",
    "brightest_star": "β Monocerotis",
    "name": "iau_constellation_monoceros",
    "position": "S N",
    "area": "481.569",
    "visibility": "75° N - 85° S",
    "magnitudo": "3.76"
  },
  "Musca": {
    "constellation": "Musca",
    "IAU": "Mus",
    "NASA": "Musc",
    "brightest_star": "α Muscae",
    "name": "iau_constellation_musca",
    "position": "S",
    "area": "138.355",
    "visibility": "10° N - 90° S",
    "magnitudo": "2.69"
  },
  "Norma": {
    "constellation": "Norma",
    "IAU": "Nor",
    "NASA": "Norm",
    "brightest_star": "γ2 Normae",
    "name": "iau_constellation_norma",
    "position": "S",
    "area": "165.29",
    "visibility": "30° N - 90° S",
    "magnitudo": "4.02"
  },
  "Octans": {
    "constellation": "Octans",
    "IAU": "Oct",
    "NASA": "Octn",
    "brightest_star": "ν Octantis",
    "name": "iau_constellation_octans",
    "position": "S",
    "area": "291.045",
    "visibility": "05° N - 90° S",
    "magnitudo": "3.76"
  },
  "Ophiuchus": {
    "constellation": "Ophiuchus",
    "IAU": "Oph",
    "NASA": "Ophi",
    "brightest_star": "Rasalhague",
    "name": "iau_constellation_ophiuchus",
    "position": "S N",
    "area": "948.34",
    "visibility": "80° N - 80° S",
    "magnitudo": "2.08"
  },
  "Orion": {
    "constellation": "Orion",
    "IAU": "Ori",
    "NASA": "Orio",
    "brightest_star": "Rigel",
    "name": "iau_constellation_orion",
    "position": "N S",
    "area": "594.12",
    "visibility": "85° N - 75° S",
    "magnitudo": "0.12"
  },
  "Pavo": {
    "constellation": "Pavo",
    "IAU": "Pav",
    "NASA": "Pavo",
    "brightest_star": "Peacock",
    "name": "iau_constellation_pavo",
    "position": "S",
    "area": "377.666",
    "visibility": "15° N - 90° S",
    "magnitudo": "1.94"
  },
  "Pegasus": {
    "constellation": "Pegasus",
    "IAU": "Peg",
    "NASA": "Pegs",
    "brightest_star": "Enif",
    "name": "iau_constellation_pegasus",
    "position": "N",
    "area": "1,120.79",
    "visibility": "90° N - 65° S",
    "magnitudo": "2.38"
  },
  "Perseus": {
    "constellation": "Perseus",
    "IAU": "Per",
    "NASA": "Pers",
    "brightest_star": "Mirfak",
    "name": "iau_constellation_perseus",
    "position": "N",
    "area": "614.997",
    "visibility": "90° N - 35° S",
    "magnitudo": "1.79"
  },
  "Phoenix": {
    "constellation": "Phoenix",
    "IAU": "Phe",
    "NASA": "Phoe",
    "brightest_star": "Ankaa",
    "name": "iau_constellation_phoenix",
    "position": "S",
    "area": "469.319",
    "visibility": "32° N - 90° S",
    "magnitudo": "2.39"
  },
  "Pictor": {
    "constellation": "Pictor",
    "IAU": "Pic",
    "NASA": "Pict",
    "brightest_star": "α Pictoris",
    "name": "iau_constellation_pictor",
    "position": "S",
    "area": "246.739",
    "visibility": "25° N - 90° S",
    "magnitudo": "3.27"
  },
  "Pisces": {
    "constellation": "Pisces",
    "IAU": "Psc",
    "NASA": "Pisc",
    "brightest_star": "Alpherg",
    "name": "iau_constellation_pisces",
    "position": "N s",
    "area": "889.417",
    "visibility": "84° N - 56° S",
    "magnitudo": "3.62"
  },
  "Piscis Austrinus": {
    "constellation": "Piscis Austrinus",
    "IAU": "PsA",
    "NASA": "PscA",
    "brightest_star": "Fomalhaut",
    "name": "iau_constellation_piscis_austrinus",
    "position": "S",
    "area": "245.375",
    "visibility": "50° N - 90° S",
    "magnitudo": "1.16"
  },
  "Puppis": {
    "constellation": "Puppis",
    "IAU": "Pup",
    "NASA": "Pupp",
    "brightest_star": "Naos",
    "name": "iau_constellation_puppis",
    "position": "S",
    "area": "673.434",
    "visibility": "39° N - 90° S",
    "magnitudo": "2.21"
  },
  "Pyxis": {
    "constellation": "Pyxis",
    "IAU": "Pyx",
    "NASA": "Pyxi",
    "brightest_star": "α Pyxidis",
    "name": "iau_constellation_pyxis",
    "position": "S",
    "area": "220.833",
    "visibility": "53° N - 90° S",
    "magnitudo": "3.68"
  },
  "Reticulum": {
    "constellation": "Reticulum",
    "IAU": "Ret",
    "NASA": "Reti",
    "brightest_star": "α Reticuli",
    "name": "iau_constellation_reticulum",
    "position": "S",
    "area": "113.936",
    "visibility": "23° N - 90° S",
    "magnitudo": "3.33"
  },
  "Sagitta": {
    "constellation": "Sagitta",
    "IAU": "Sge",
    "NASA": "Sgte",
    "brightest_star": "γ Sagittae",
    "name": "iau_constellation_sagitta",
    "position": "N",
    "area": "79.923",
    "visibility": "90° N - 70° S",
    "magnitudo": "3.51"
  },
  "Sagittarius": {
    "constellation": "Sagittarius",
    "IAU": "Sgr",
    "NASA": "Sgtr",
    "brightest_star": "Kaus Australis",
    "name": "iau_constellation_sagittarius",
    "position": "S",
    "area": "867.432",
    "visibility": "55° N - 90° S",
    "magnitudo": "1.85"
  },
  "Scorpius": {
    "constellation": "Scorpius",
    "IAU": "Sco",
    "NASA": "Scor",
    "brightest_star": "Antares",
    "name": "iau_constellation_scorpius",
    "position": "S",
    "area": "496.783",
    "visibility": "44° N - 90° S",
    "magnitudo": "1.06"
  },
  "Sculptor": {
    "constellation": "Sculptor",
    "IAU": "Scl",
    "NASA": "Scul",
    "brightest_star": "α Sculptoris",
    "name": "iau_constellation_sculptor",
    "position": "S",
    "area": "474.764",
    "visibility": "50° N - 90° S",
    "magnitudo": "4.27"
  },
  "Scutum": {
    "constellation": "Scutum",
    "IAU": "Sct",
    "NASA": "Scut",
    "brightest_star": "α Scuti",
    "name": "iau_constellation_scutum",
    "position": "S",
    "area": "109.114",
    "visibility": "74° N - 64° S",
    "magnitudo": "3.85"
  },
  "Serpens": {
    "constellation": "Serpens",
    "IAU": "Ser",
    "NASA": "Serp",
    "brightest_star": "Unukalhai",
    "name": "iau_constellation_serpens",
    "position": "N S",
    "area": "636.928",
    "visibility": "74° N - 64° S",
    "magnitudo": "2.63"
  },
  "Sextans": {
    "constellation": "Sextans",
    "IAU": "Sex",
    "NASA": "Sext",
    "brightest_star": "α Sextantis",
    "name": "iau_constellation_sextans",
    "position": "S N",
    "area": "313.515",
    "visibility": "78° N - 83° S",
    "magnitudo": "4.49"
  },
  "Taurus": {
    "constellation": "Taurus",
    "IAU": "Tau",
    "NASA": "Taur",
    "brightest_star": "Aldebaran",
    "name": "iau_constellation_taurus",
    "position": "N s",
    "area": "797.249",
    "visibility": "90° N - 65° S",
    "magnitudo": "0.85"
  },
  "Telescopium": {
    "constellation": "Telescopium",
    "IAU": "Tel",
    "NASA": "Tele",
    "brightest_star": "α Telescopii",
    "name": "iau_constellation_telescopium",
    "position": "S",
    "area": "251.512",
    "visibility": "33° N - 90° S",
    "magnitudo": "3.51"
  },
  "Triangulum": {
    "constellation": "Triangulum",
    "IAU": "Tri",
    "NASA": "Tria",
    "brightest_star": "β Trianguli",
    "name": "iau_constellation_triangulum",
    "position": "N",
    "area": "131.847",
    "visibility": "90° N - 50° S",
    "magnitudo": "3"
  },
  "Triangulum Australe": {
    "constellation": "Triangulum Australe",
    "IAU": "TrA",
    "NASA": "TrAu",
    "brightest_star": "Atria",
    "name": "iau_constellation_triangulum_australe",
    "position": "S",
    "area": "109.978",
    "visibility": "20° N - 90° S",
    "magnitudo": "1.91"
  },
  "Tucana": {
    "constellation": "Tucana",
    "IAU": "Tuc",
    "NASA": "Tucn",
    "brightest_star": "α Tucanae",
    "name": "iau_constellation_tucana",
    "position": "S",
    "area": "294.557",
    "visibility": "15° N - 90° S",
    "magnitudo": "2.86"
  },
  "Ursa Major": {
    "constellation": "Ursa Major",
    "IAU": "UMa",
    "NASA": "UMaj",
    "brightest_star": "Alioth",
    "name": "iau_constellation_ursa_major",
    "position": "N",
    "area": "1,279.66",
    "visibility": "90° N - 17° S",
    "magnitudo": "1.76"
  },
  "Ursa Minor": {
    "constellation": "Ursa Minor",
    "IAU": "UMi",
    "NASA": "UMin",
    "brightest_star": "Polaris",
    "name": "iau_constellation_ursa_minor",
    "position": "N",
    "area": "255.864",
    "visibility": "90° N - 10° S",
    "magnitudo": "1.97"
  },
  "Vela": {
    "constellation": "Vela",
    "IAU": "Vel",
    "NASA": "Velr",
    "brightest_star": "γ2 Velorum",
    "name": "iau_constellation_vela",
    "position": "S",
    "area": "499.649",
    "visibility": "33° N - 90° S",
    "magnitudo": "1.75"
  },
  "Virgo": {
    "constellation": "Virgo",
    "IAU": "Vir",
    "NASA": "Virg",
    "brightest_star": "Spica",
    "name": "iau_constellation_virgo",
    "position": "S N",
    "area": "1,294.43",
    "visibility": "67° N - 76° S",
    "magnitudo": "0.92"
  },
  "Volans": {
    "constellation": "Volans",
    "IAU": "Vol",
    "NASA": "Voln",
    "brightest_star": "β Volantis",
    "name": "iau_constellation_volans",
    "position": "S",
    "area": "141.354",
    "visibility": "14° N - 90° S",
    "magnitudo": "3.77"
  },
  "Vulpecula": {
    "constellation": "Vulpecula",
    "IAU": "Vul",
    "NASA": "Vulp",
    "brightest_star": "Anser",
    "name": "iau_constellation_vulpecula",
    "position": "N",
    "area": "268.165",
    "visibility": "90° N - 55° S",
    "magnitudo": "4.44"
  }
};
