// https://en.wikipedia.org/wiki/IAU_designated_constellations
// https://de.wikipedia.org/wiki/Liste_der_Sternbilder
// https://www.iau.org/public/themes/constellations/

part of 'package:gc_wizard/tools/science_and_technology/astronomy/iau_constellation/logic/iau_constellation.dart';

class Constellation {
  late final String ConstellationName;
  late final String IAU;
  late final String NASA;
  late final String Star;
  late final String name;
  late final String position;
  late final double area;
  late final String visibility;
  late final double magnitudo;

  Constellation(
      {required this.ConstellationName,
      required this.IAU,
      required this.NASA,
      required this.Star,
      required this.name,
      required this.position,
      required this.area,
      required this.visibility,
      required this.magnitudo});
}

final List<Constellation> allConstellations = [
  Constellation(
      ConstellationName: "Andromeda",
      IAU: "And",
      NASA: "Andr",
      Star: "Sirrah",
      name: "iau_constellation_andromeda",
      position: "N",
      area: 722.278,
      visibility: "90° N - 37° S",
      magnitudo: 2.07),
  Constellation(
      ConstellationName: "Antlia",
      IAU: "Ant",
      NASA: "Antl",
      Star: "α Antliae",
      name: "iau_constellation_antlia",
      position: "S",
      area: 238.901,
      visibility: "50° N - 90° S",
      magnitudo: 4.22),
  Constellation(
      ConstellationName: "Apus",
      IAU: "Aps",
      NASA: "Apus",
      Star: "α Apodis",
      name: "iau_constellation_apus",
      position: "S",
      area: 206.327,
      visibility: "07° N - 90° S",
      magnitudo: 3.83),
  Constellation(
      ConstellationName: "Aquarius",
      IAU: "Aqr",
      NASA: "Aqar",
      Star: "Sadalsuud",
      name: "iau_constellation_aquarius",
      position: "S n",
      area: 979.854,
      visibility: "65° N - 87° S",
      magnitudo: 2.9),
  Constellation(
      ConstellationName: "Aquila",
      IAU: "Aql",
      NASA: "Aqil",
      Star: "Altair",
      name: "iau_constellation_aquila",
      position: "N S",
      area: 652.473,
      visibility: "78° N - 71° S",
      magnitudo: 0.76),
  Constellation(
      ConstellationName: "Ara",
      IAU: "Ara",
      NASA: "Arae",
      Star: "β Arae",
      name: "iau_constellation_ara",
      position: "S",
      area: 237.057,
      visibility: "25° N - 90° S",
      magnitudo: 2.85),
  Constellation(
      ConstellationName: "Aries",
      IAU: "Ari",
      NASA: "Arie",
      Star: "Hamal",
      name: "iau_constellation_aries",
      position: "N",
      area: 441.395,
      visibility: "90° N - 59° S",
      magnitudo: 2.01),
  Constellation(
      ConstellationName: "Auriga",
      IAU: "Aur",
      NASA: "Auri",
      Star: "Capella",
      name: "iau_constellation_auriga",
      position: "N",
      area: 657.438,
      visibility: "90° N - 34° S",
      magnitudo: 0.03),
  Constellation(
      ConstellationName: "Boötes",
      IAU: "Boo",
      NASA: "Boot",
      Star: "Arcturus",
      name: "iau_constellation_bootes",
      position: "N",
      area: 906.831,
      visibility: "90° N - 50° S",
      magnitudo: -0.05),
  Constellation(
      ConstellationName: "Caelum",
      IAU: "Cae",
      NASA: "Cael",
      Star: "α Caeli",
      name: "iau_constellation_caelum",
      position: "S",
      area: 124.865,
      visibility: "41° N - 90° S",
      magnitudo: 4.45),
  Constellation(
      ConstellationName: "Camelopardalis",
      IAU: "Cam",
      NASA: "Caml",
      Star: "β Camelopardalis",
      name: "iau_constellation_camelopardalis",
      position: "N",
      area: 756.828,
      visibility: "90° N - 37° S",
      magnitudo: 4.03),
  Constellation(
      ConstellationName: "Cancer",
      IAU: "Cnc",
      NASA: "Canc",
      Star: "Tarf",
      name: "iau_constellation_cancer",
      position: "N",
      area: 505.872,
      visibility: "90° N - 60° S",
      magnitudo: 3.52),
  Constellation(
      ConstellationName: "Canes Venatici",
      IAU: "CVn",
      NASA: "CVen",
      Star: "Cor Caroli",
      name: "iau_constellation_canes_venatici",
      position: "N",
      area: 465.194,
      visibility: "90° N - 38° S",
      magnitudo: 2.8),
  Constellation(
      ConstellationName: "Canis Major",
      IAU: "CMa",
      NASA: "CMaj",
      Star: "Sirius",
      name: "iau_constellation_canis_major",
      position: "S",
      area: 380.118,
      visibility: "57° N - 90° S",
      magnitudo: -1.44),
  Constellation(
      ConstellationName: "Canis Minor",
      IAU: "CMi",
      NASA: "CMin",
      Star: "Procyon",
      name: "iau_constellation_canis_minor",
      position: "N s",
      area: 183.367,
      visibility: "89° N - 77° S",
      magnitudo: 0.37),
  Constellation(
      ConstellationName: "Capricornus",
      IAU: "Cap",
      NASA: "Capr",
      Star: "Deneb Algedi",
      name: "iau_constellation_capricornus",
      position: "S",
      area: 413.947,
      visibility: "62° N - 90° S",
      magnitudo: 2.73),
  Constellation(
      ConstellationName: "Carina",
      IAU: "Car",
      NASA: "Cari",
      Star: "Canopus",
      name: "iau_constellation_carina",
      position: "S",
      area: 494.184,
      visibility: "14° N - 90° S",
      magnitudo: -0.62),
  Constellation(
      ConstellationName: "Cassiopeia",
      IAU: "Cas",
      NASA: "Cass",
      Star: "Schedar",
      name: "iau_constellation_cassiopeia",
      position: "N",
      area: 598.407,
      visibility: "90° N - 12° S",
      magnitudo: 2.23),
  Constellation(
      ConstellationName: "Centaurus",
      IAU: "Cen",
      NASA: "Cent",
      Star: "Rigil Kentaurus",
      name: "iau_constellation_centaurus",
      position: "S",
      area: 1060.42,
      visibility: "25° N - 90° S",
      magnitudo: -0.01),
  Constellation(
      ConstellationName: "Cepheus",
      IAU: "Cep",
      NASA: "Ceph",
      Star: "Alderamin",
      name: "iau_constellation_cepheus",
      position: "N",
      area: 587.787,
      visibility: "90° N - 10° S",
      magnitudo: 2.45),
  Constellation(
      ConstellationName: "Cetus",
      IAU: "Cet",
      NASA: "Ceti",
      Star: "Diphda",
      name: "iau_constellation_cetus",
      position: "S n",
      area: 1231.41,
      visibility: "70° N - 90° S",
      magnitudo: 2.04),
  Constellation(
      ConstellationName: "Chamaeleon",
      IAU: "Cha",
      NASA: "Cham",
      Star: "α Chamaeleontis",
      name: "iau_constellation_chamaeleon",
      position: "S",
      area: 131.592,
      visibility: "07° N - 90° S",
      magnitudo: 4.05),
  Constellation(
      ConstellationName: "Circinus",
      IAU: "Cir",
      NASA: "Circ",
      Star: "α Circini",
      name: "iau_constellation_circinus",
      position: "S",
      area: 93.353,
      visibility: "20° N - 90° S",
      magnitudo: 3.19),
  Constellation(
      ConstellationName: "Columba",
      IAU: "Col",
      NASA: "Colm",
      Star: "Phact",
      name: "iau_constellation_columba",
      position: "S",
      area: 270.184,
      visibility: "41° N - 90° S",
      magnitudo: 2.65),
  Constellation(
      ConstellationName: "Coma Berenices",
      IAU: "Com",
      NASA: "Coma",
      Star: "β Comae Berenices",
      name: "iau_constellation_coma_berenices",
      position: "N",
      area: 386.475,
      visibility: "90° N - 56° S",
      magnitudo: 4.26),
  Constellation(
      ConstellationName: "Corona Australis",
      IAU: "CrA",
      NASA: "CorA",
      Star: "Meridiana",
      name: "iau_constellation_corona_australis",
      position: "S",
      area: 127.696,
      visibility: "44° N - 90° S",
      magnitudo: 4.1),
  Constellation(
      ConstellationName: "Corona Borealis",
      IAU: "CrB",
      NASA: "CorB",
      Star: "Alphecca",
      name: "iau_constellation_corona_borealis",
      position: "N",
      area: 178.71,
      visibility: "90° N - 50° S",
      magnitudo: 2.21),
  Constellation(
      ConstellationName: "Corvus",
      IAU: "Crv",
      NASA: "Corv",
      Star: "Gienah",
      name: "iau_constellation_corvus",
      position: "S",
      area: 183.801,
      visibility: "65° N - 90° S",
      magnitudo: 2.59),
  Constellation(
      ConstellationName: "Crater",
      IAU: "Crt",
      NASA: "Crat",
      Star: "δ Crateris",
      name: "iau_constellation_crater",
      position: "S",
      area: 282.398,
      visibility: "65° N - 90° S",
      magnitudo: 3.56),
  Constellation(
      ConstellationName: "Crux",
      IAU: "Cru",
      NASA: "Cruc",
      Star: "Acrux",
      name: "iau_constellation_crux",
      position: "S",
      area: 68.447,
      visibility: "25° N - 90° S",
      magnitudo: 0.77),
  Constellation(
      ConstellationName: "Cygnus",
      IAU: "Cyg",
      NASA: "Cygn",
      Star: "Deneb",
      name: "iau_constellation_cygnus",
      position: "N",
      area: 803.983,
      visibility: "90° N - 29° S",
      magnitudo: 1.25),
  Constellation(
      ConstellationName: "Delphinus",
      IAU: "Del",
      NASA: "Dlph",
      Star: "Rotanev",
      name: "iau_constellation_delphinus",
      position: "N",
      area: 188.549,
      visibility: "90° N - 70° S",
      magnitudo: 3.63),
  Constellation(
      ConstellationName: "Dorado",
      IAU: "Dor",
      NASA: "Dora",
      Star: "α Doradus",
      name: "iau_constellation_dorado",
      position: "S",
      area: 179.173,
      visibility: "20° N - 90° S",
      magnitudo: 3.3),
  Constellation(
      ConstellationName: "Draco",
      IAU: "Dra",
      NASA: "Drac",
      Star: "Eltanin",
      name: "iau_constellation_draco",
      position: "N",
      area: 1082.95,
      visibility: "90° N - 15° S",
      magnitudo: 2.24),
  Constellation(
      ConstellationName: "Equuleus",
      IAU: "Equ",
      NASA: "Equl",
      Star: "Kitalpha",
      name: "iau_constellation_equuleus",
      position: "N",
      area: 71.641,
      visibility: "90° N - 77° S",
      magnitudo: 3.92),
  Constellation(
      ConstellationName: "Eridanus",
      IAU: "Eri",
      NASA: "Erid",
      Star: "Achernar",
      name: "iau_constellation_eridanus",
      position: "S n",
      area: 1137.92,
      visibility: "32° N - 89° S",
      magnitudo: 0.5),
  Constellation(
      ConstellationName: "Fornax",
      IAU: "For",
      NASA: "Forn",
      Star: "Dalim",
      name: "iau_constellation_fornax",
      position: "S",
      area: 397.502,
      visibility: "50° N - 90° S",
      magnitudo: 3.87),
  Constellation(
      ConstellationName: "Gemini",
      IAU: "Gem",
      NASA: "Gemi",
      Star: "Pollux",
      name: "iau_constellation_gemini",
      position: "N",
      area: 513.761,
      visibility: "90° N - 60° S",
      magnitudo: 1.16),
  Constellation(
      ConstellationName: "Grus",
      IAU: "Gru",
      NASA: "Grus",
      Star: "Alnair",
      name: "iau_constellation_grus",
      position: "S",
      area: 365.513,
      visibility: "35° N - 90° S",
      magnitudo: 1.74),
  Constellation(
      ConstellationName: "Hercules",
      IAU: "Her",
      NASA: "Herc",
      Star: "Kornephoros",
      name: "iau_constellation_hercules",
      position: "N",
      area: 1225.15,
      visibility: "90° N - 39° S",
      magnitudo: 2.78),
  Constellation(
      ConstellationName: "Horologium",
      IAU: "Hor",
      NASA: "Horo",
      Star: "α Horologii",
      name: "iau_constellation_horologium",
      position: "S",
      area: 248.885,
      visibility: "20° N - 90° S",
      magnitudo: 3.85),
  Constellation(
      ConstellationName: "Hydra",
      IAU: "Hya",
      NASA: "Hyda",
      Star: "Alphard",
      name: "iau_constellation_hydra",
      position: "S n",
      area: 1302.84,
      visibility: "55° N - 83° S",
      magnitudo: 1.98),
  Constellation(
      ConstellationName: "Hydrus",
      IAU: "Hyi",
      NASA: "Hydi",
      Star: "β Hydri",
      name: "iau_constellation_hydrus",
      position: "S",
      area: 243.035,
      visibility: "08° N - 90° S",
      magnitudo: 2.8),
  Constellation(
      ConstellationName: "Indus",
      IAU: "Ind",
      NASA: "Indi",
      Star: "α Indi",
      name: "iau_constellation_indus",
      position: "S",
      area: 294.006,
      visibility: "16° N - 90° S",
      magnitudo: 3.11),
  Constellation(
      ConstellationName: "Lacerta",
      IAU: "Lac",
      NASA: "Lacr",
      Star: "α Lacertae",
      name: "iau_constellation_lacerta",
      position: "N",
      area: 200.688,
      visibility: "90° N - 40° S",
      magnitudo: 3.77),
  Constellation(
      ConstellationName: "Leo",
      IAU: "Leo",
      NASA: "Leon",
      Star: "Regulus",
      name: "iau_constellation_leo",
      position: "N s",
      area: 946.964,
      visibility: "83° N - 57° S",
      magnitudo: 1.36),
  Constellation(
      ConstellationName: "Leo Minor",
      IAU: "LMi",
      NASA: "LMin",
      Star: "Praecipua",
      name: "iau_constellation_leo_minor",
      position: "N",
      area: 231.956,
      visibility: "90° N - 48° S",
      magnitudo: 3.83),
  Constellation(
      ConstellationName: "Lepus",
      IAU: "Lep",
      NASA: "Leps",
      Star: "Arneb",
      name: "iau_constellation_lepus",
      position: "S",
      area: 290.291,
      visibility: "60° N - 90° S",
      magnitudo: 2.58),
  Constellation(
      ConstellationName: "Libra",
      IAU: "Lib",
      NASA: "Libr",
      Star: "Zubeneschamali",
      name: "iau_constellation_libra",
      position: "S",
      area: 538.052,
      visibility: "60° N - 90° S",
      magnitudo: 2.61),
  Constellation(
      ConstellationName: "Lupus",
      IAU: "Lup",
      NASA: "Lupi",
      Star: "α Lupi",
      name: "iau_constellation_lupus",
      position: "S",
      area: 333.683,
      visibility: "35° N - 90° S",
      magnitudo: 2.29),
  Constellation(
      ConstellationName: "Lynx",
      IAU: "Lyn",
      NASA: "Lync",
      Star: "α Lyncis",
      name: "iau_constellation_lynx",
      position: "N",
      area: 545.386,
      visibility: "90° N - 35° S",
      magnitudo: 3.13),
  Constellation(
      ConstellationName: "Lyra",
      IAU: "Lyr",
      NASA: "Lyra",
      Star: "Vega",
      name: "iau_constellation_lyra",
      position: "N",
      area: 286.476,
      visibility: "90° N - 29° S",
      magnitudo: 0.03),
  Constellation(
      ConstellationName: "Mensa",
      IAU: "Men",
      NASA: "Mens",
      Star: "α Mensae",
      name: "iau_constellation_mensa",
      position: "S",
      area: 153.484,
      visibility: "05° N - 90° S",
      magnitudo: 5.09),
  Constellation(
      ConstellationName: "Microscopium",
      IAU: "Mic",
      NASA: "Micr",
      Star: "γ Microscopii",
      name: "iau_constellation_microscopium",
      position: "S",
      area: 209.513,
      visibility: "45° N - 90° S",
      magnitudo: 4.67),
  Constellation(
      ConstellationName: "Monoceros",
      IAU: "Mon",
      NASA: "Mono",
      Star: "β Monocerotis",
      name: "iau_constellation_monoceros",
      position: "S N",
      area: 481.569,
      visibility: "75° N - 85° S",
      magnitudo: 3.76),
  Constellation(
      ConstellationName: "Musca",
      IAU: "Mus",
      NASA: "Musc",
      Star: "α Muscae",
      name: "iau_constellation_musca",
      position: "S",
      area: 138.355,
      visibility: "10° N - 90° S",
      magnitudo: 2.69),
  Constellation(
      ConstellationName: "Norma",
      IAU: "Nor",
      NASA: "Norm",
      Star: "γ2 Normae",
      name: "iau_constellation_norma",
      position: "S",
      area: 165.29,
      visibility: "30° N - 90° S",
      magnitudo: 4.02),
  Constellation(
      ConstellationName: "Octans",
      IAU: "Oct",
      NASA: "Octn",
      Star: "ν Octantis",
      name: "iau_constellation_octans",
      position: "S",
      area: 291.045,
      visibility: "05° N - 90° S",
      magnitudo: 3.76),
  Constellation(
      ConstellationName: "Ophiuchus",
      IAU: "Oph",
      NASA: "Ophi",
      Star: "Rasalhague",
      name: "iau_constellation_ophiuchus",
      position: "S N",
      area: 948.34,
      visibility: "80° N - 80° S",
      magnitudo: 2.08),
  Constellation(
      ConstellationName: "Orion",
      IAU: "Ori",
      NASA: "Orio",
      Star: "Rigel",
      name: "iau_constellation_orion",
      position: "N S",
      area: 594.12,
      visibility: "85° N - 75° S",
      magnitudo: 0.12),
  Constellation(
      ConstellationName: "Pavo",
      IAU: "Pav",
      NASA: "Pavo",
      Star: "Peacock",
      name: "iau_constellation_pavo",
      position: "S",
      area: 377.666,
      visibility: "15° N - 90° S",
      magnitudo: 1.94),
  Constellation(
      ConstellationName: "Pegasus",
      IAU: "Peg",
      NASA: "Pegs",
      Star: "Enif",
      name: "iau_constellation_pegasus",
      position: "N",
      area: 1120.79,
      visibility: "90° N - 65° S",
      magnitudo: 2.38),
  Constellation(
      ConstellationName: "Perseus",
      IAU: "Per",
      NASA: "Pers",
      Star: "Mirfak",
      name: "iau_constellation_perseus",
      position: "N",
      area: 614.997,
      visibility: "90° N - 35° S",
      magnitudo: 1.79),
  Constellation(
      ConstellationName: "Phoenix",
      IAU: "Phe",
      NASA: "Phoe",
      Star: "Ankaa",
      name: "iau_constellation_phoenix",
      position: "S",
      area: 469.319,
      visibility: "32° N - 90° S",
      magnitudo: 2.39),
  Constellation(
      ConstellationName: "Pictor",
      IAU: "Pic",
      NASA: "Pict",
      Star: "α Pictoris",
      name: "iau_constellation_pictor",
      position: "S",
      area: 246.739,
      visibility: "25° N - 90° S",
      magnitudo: 3.27),
  Constellation(
      ConstellationName: "Pisces",
      IAU: "Psc",
      NASA: "Pisc",
      Star: "Alpherg",
      name: "iau_constellation_pisces",
      position: "N s",
      area: 889.417,
      visibility: "84° N - 56° S",
      magnitudo: 3.62),
  Constellation(
      ConstellationName: "Piscis Austrinus",
      IAU: "PsA",
      NASA: "PscA",
      Star: "Fomalhaut",
      name: "iau_constellation_piscis_austrinus",
      position: "S",
      area: 245.375,
      visibility: "50° N - 90° S",
      magnitudo: 1.16),
  Constellation(
      ConstellationName: "Puppis",
      IAU: "Pup",
      NASA: "Pupp",
      Star: "Naos",
      name: "iau_constellation_puppis",
      position: "S",
      area: 673.434,
      visibility: "39° N - 90° S",
      magnitudo: 2.21),
  Constellation(
      ConstellationName: "Pyxis",
      IAU: "Pyx",
      NASA: "Pyxi",
      Star: "α Pyxidis",
      name: "iau_constellation_pyxis",
      position: "S",
      area: 220.833,
      visibility: "53° N - 90° S",
      magnitudo: 3.68),
  Constellation(
      ConstellationName: "Reticulum",
      IAU: "Ret",
      NASA: "Reti",
      Star: "α Reticuli",
      name: "iau_constellation_reticulum",
      position: "S",
      area: 113.936,
      visibility: "23° N - 90° S",
      magnitudo: 3.33),
  Constellation(
      ConstellationName: "Sagitta",
      IAU: "Sge",
      NASA: "Sgte",
      Star: "γ Sagittae",
      name: "iau_constellation_sagitta",
      position: "N",
      area: 79.923,
      visibility: "90° N - 70° S",
      magnitudo: 3.51),
  Constellation(
      ConstellationName: "Sagittarius",
      IAU: "Sgr",
      NASA: "Sgtr",
      Star: "Kaus Australis",
      name: "iau_constellation_sagittarius",
      position: "S",
      area: 867.432,
      visibility: "55° N - 90° S",
      magnitudo: 1.85),
  Constellation(
      ConstellationName: "Scorpius",
      IAU: "Sco",
      NASA: "Scor",
      Star: "Antares",
      name: "iau_constellation_scorpius",
      position: "S",
      area: 496.783,
      visibility: "44° N - 90° S",
      magnitudo: 1.06),
  Constellation(
      ConstellationName: "Sculptor",
      IAU: "Scl",
      NASA: "Scul",
      Star: "α Sculptoris",
      name: "iau_constellation_sculptor",
      position: "S",
      area: 474.764,
      visibility: "50° N - 90° S",
      magnitudo: 4.27),
  Constellation(
      ConstellationName: "Scutum",
      IAU: "Sct",
      NASA: "Scut",
      Star: "α Scuti",
      name: "iau_constellation_scutum",
      position: "S",
      area: 109.114,
      visibility: "74° N - 64° S",
      magnitudo: 3.85),
  Constellation(
      ConstellationName: "Serpens",
      IAU: "Ser",
      NASA: "Serp",
      Star: "Unukalhai",
      name: "iau_constellation_serpens",
      position: "N S",
      area: 636.928,
      visibility: "74° N - 64° S",
      magnitudo: 2.63),
  Constellation(
      ConstellationName: "Sextans",
      IAU: "Sex",
      NASA: "Sext",
      Star: "α Sextantis",
      name: "iau_constellation_sextans",
      position: "S N",
      area: 313.515,
      visibility: "78° N - 83° S",
      magnitudo: 4.49),
  Constellation(
      ConstellationName: "Taurus",
      IAU: "Tau",
      NASA: "Taur",
      Star: "Aldebaran",
      name: "iau_constellation_taurus",
      position: "N s",
      area: 797.249,
      visibility: "90° N - 65° S",
      magnitudo: 0.85),
  Constellation(
      ConstellationName: "Telescopium",
      IAU: "Tel",
      NASA: "Tele",
      Star: "α Telescopii",
      name: "iau_constellation_telescopium",
      position: "S",
      area: 251.512,
      visibility: "33° N - 90° S",
      magnitudo: 3.51),
  Constellation(
      ConstellationName: "Triangulum",
      IAU: "Tri",
      NASA: "Tria",
      Star: "β Trianguli",
      name: "iau_constellation_triangulum",
      position: "N",
      area: 131.847,
      visibility: "90° N - 50° S",
      magnitudo: 3),
  Constellation(
      ConstellationName: "Triangulum Australe",
      IAU: "TrA",
      NASA: "TrAu",
      Star: "Atria",
      name: "iau_constellation_triangulum_australe",
      position: "S",
      area: 109.978,
      visibility: "20° N - 90° S",
      magnitudo: 1.91),
  Constellation(
      ConstellationName: "Tucana",
      IAU: "Tuc",
      NASA: "Tucn",
      Star: "α Tucanae",
      name: "iau_constellation_tucana",
      position: "S",
      area: 294.557,
      visibility: "15° N - 90° S",
      magnitudo: 2.86),
  Constellation(
      ConstellationName: "Ursa Major",
      IAU: "UMa",
      NASA: "UMaj",
      Star: "Alioth",
      name: "iau_constellation_ursa_major",
      position: "N",
      area: 1279.66,
      visibility: "90° N - 17° S",
      magnitudo: 1.76),
  Constellation(
      ConstellationName: "Ursa Minor",
      IAU: "UMi",
      NASA: "UMin",
      Star: "Polaris",
      name: "iau_constellation_ursa_minor",
      position: "N",
      area: 255.864,
      visibility: "90° N - 10° S",
      magnitudo: 1.97),
  Constellation(
      ConstellationName: "Vela",
      IAU: "Vel",
      NASA: "Velr",
      Star: "γ2 Velorum",
      name: "iau_constellation_vela",
      position: "S",
      area: 499.649,
      visibility: "33° N - 90° S",
      magnitudo: 1.75),
  Constellation(
      ConstellationName: "Virgo",
      IAU: "Vir",
      NASA: "Virg",
      Star: "Spica",
      name: "iau_constellation_virgo",
      position: "S N",
      area: 1294.43,
      visibility: "67° N - 76° S",
      magnitudo: 0.92),
  Constellation(
      ConstellationName: "Volans",
      IAU: "Vol",
      NASA: "Voln",
      Star: "β Volantis",
      name: "iau_constellation_volans",
      position: "S",
      area: 141.354,
      visibility: "14° N - 90° S",
      magnitudo: 3.77),
  Constellation(
      ConstellationName: "Vulpecula",
      IAU: "Vul",
      NASA: "Vulp",
      Star: "Anser",
      name: "iau_constellation_vulpecula",
      position: "N",
      area: 268.165,
      visibility: "90° N - 55° S",
      magnitudo: 4.44)
];
